### ISSUE TITLE
/AE, /OE, /Oslash, /ae, /oe, and /oslash accross all styles

### ISSUE THREAD

**Issue by LisaHuang2017** [arrowtype/recursive#105]
These glyphs are still missing in the Italic styles in Mono:
- /ae
-/oslash
-/AE
-/Oslash

Plus their combinations with diacritics.

**Comment by thundernixon** [comment]
Thanks, @LisaHuang2017! Great first issue, and thanks for catching this.

**Comment by thundernixon** [comment]
From what I can tell, the /AE and /Oslash actually are in all mono fonts, but the lowercase versions are missing. I think the title says that, but the issue text doesn't quite make it clear.

ae

	 /ae is in:
		 • Recursive Mono Linear B
		 • Recursive Mono Linear A
		 • Recursive Mono Linear C
		 • Recursive Mono Casual A
		 • Recursive Mono Casual C
		 • Recursive Mono Casual B

		 ...but not in:
			 • Recursive Mono Linear C Slanted
			 • Recursive Mono Linear B Slanted
			 • Recursive Mono Linear A Slanted
			 • Recursive Mono Casual A Slanted
			 • Recursive Mono Casual B Slanted
			 • Recursive Mono Casual C Slanted

--------------------------------------------------------------
oslash

	 /oslash is in:
		 • Recursive Mono Linear B
		 • Recursive Mono Linear A
		 • Recursive Mono Linear C
		 • Recursive Mono Casual A
		 • Recursive Mono Casual C
		 • Recursive Mono Casual B

		 ...but not in:
			 • Recursive Mono Linear C Slanted
			 • Recursive Mono Linear B Slanted
			 • Recursive Mono Linear A Slanted
			 • Recursive Mono Casual A Slanted
			 • Recursive Mono Casual B Slanted
			 • Recursive Mono Casual C Slanted

**Comment by thundernixon** [comment]
However, while this work is being done, I think it would make sense to combine the work of making sure that these four glyphs are also in the Sans masters:

AE

	 /AE is in:
		 • Recursive Sans Linear C
		 • Recursive Sans Linear B
		 • Recursive Sans Linear A
		 • Recursive Sans Casual C
		 • Recursive Sans Casual A
		 • Recursive Sans Casual B

		 ...but not in:
			 • Recursive Sans Casual A Slanted
			 • Recursive Sans Linear C Slanted
			 • Recursive Sans Linear B Slanted
			 • Recursive Sans Linear A Slanted
			 • Recursive Sans Casual C Slanted
			 • Recursive Sans Casual B Slanted

--------------------------------------------------------------
Oslash

	 /Oslash is in:
		 • Recursive Sans Linear C
		 • Recursive Sans Linear B
		 • Recursive Sans Linear A
		 • Recursive Sans Casual C
		 • Recursive Sans Casual A
		 • Recursive Sans Casual B

		 ...but not in:
			 • Recursive Sans Casual A Slanted
			 • Recursive Sans Linear C Slanted
			 • Recursive Sans Linear B Slanted
			 • Recursive Sans Linear A Slanted
			 • Recursive Sans Casual C Slanted
			 • Recursive Sans Casual B Slanted

--------------------------------------------------------------
ae

	 /ae is in:
		 • Recursive Sans Linear C
		 • Recursive Sans Linear B
		 • Recursive Sans Linear A
		 • Recursive Sans Casual C
		 • Recursive Sans Casual A
		 • Recursive Sans Casual B

		 ...but not in:
			 • Recursive Sans Casual A Slanted
			 • Recursive Sans Linear C Slanted
			 • Recursive Sans Linear B Slanted
			 • Recursive Sans Linear A Slanted
			 • Recursive Sans Casual C Slanted
			 • Recursive Sans Casual B Slanted

--------------------------------------------------------------
oslash

	 /oslash is in:
		 • Recursive Sans Linear C
		 • Recursive Sans Linear B
		 • Recursive Sans Linear A
		 • Recursive Sans Casual C
		 • Recursive Sans Casual A
		 • Recursive Sans Casual B

		 ...but not in:
			 • Recursive Sans Casual A Slanted
			 • Recursive Sans Linear C Slanted
			 • Recursive Sans Linear B Slanted
			 • Recursive Sans Linear A Slanted
			 • Recursive Sans Casual C Slanted
			 • Recursive Sans Casual B Slanted

**Comment by KatjaSchimmel** [comment]
I updated /AE /ae /OE /oe /Oslash /oslash in all upright master in Mono and Sans. Copied them to Slanted masters and did all italic corrections there (skewed, corrected some slanted curves, corrected the wavyness in Casual Slanted styles). Also, I checked the consistency of all widths and re-build /AEacute /aeacute /Oslashacute and /oslashacute with gylph construction.
