### ISSUE TITLE
Correct spacing of copied punctuation in Sans Slanted masters

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#107]
The following punctuation glyphs need to be newly copied into the Sans masters from updated Mono masters, then adjusted and respaced.

The widths should stay consistent for other masters, but the sidebearings will change. I have copied the previous punctuation to a new layer, `proportional`, to make it simple to adjust newly-copied versions to the correct width and (relatively) correct spacing.

Punctuation and metrics in Recursive Sans Casual B:

| glyph | width | LSB | RSB |
| :--- | :--- | :--- | :--- |
| asterisk             | 500 | 44 | 44 |
| braceleft            | 500 | 56 | 29 |
| braceright           | 500 | 29 | 56 |
| bracketleft          | 400 | 40 | 31 |
| bracketright         | 400 | 31 | 40 |
| grave                | 350 | 42 | 42 |
| parenleft            | 400 | 50 | -20 |
| parenright           | 400 | -20 | 50 |
| period               | 300 | 46 | 46 |
| periodcentered       | 300 | 46 | 46 |

**Comment by arrowtype** [comment]
This was completed as part of separate work, and is fine as of release 1.047.
