### ISSUE TITLE
Sans: bring midpoint of /W up to cap height

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#110]
It was an early design decision to make the Sans /W a bit like the mono /W, with a lowered midpoint. I no longer like this decision so much, so I plan to change it.

**Comment by arrowtype** [comment]
Making the W 950 units wide (used to be 900) to fit this change.

Also to do:
- [ ] update anchor placement
- [ ] regenerate W-based diacritics

**Comment by arrowtype** [comment]
Done in sources; will build into a release soon!
