### ISSUE TITLE
Fix compatibility in Mono masters for new VF build

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#115]
We need to do a cycle of compatibility-matching to make things build in a better way.

Glyphs that aren't compatible, caught by FontParts `isCompatible()` check, so probably have more-obvious issues:

```
    'asterisk', 'r.italic', 'question', 'k.italic', 'parenright', 'ringacute', 'dotlessi', 'dotlessj', 'dotbelowcomb.case', 'macron', 'underscore'
```

Incompatibility caught by `cu2qu`
```
    cu2qu.errors.IncompatibleFontsError: fonts contains incompatible glyphs:
    'E', 'L', 'Lslash', 'OE', 'ampersand', 'asciicircum', 'circumflexcomb', 'e', 'g.italic', 'g.mono', 'greaterequal', 'h', 'i', 'increment', 'j', 'less', 'lessequal', 'logicalnot', 'lozenge', 'ordfeminine', 'radical', 'trademark', 'u', 'v', 'x'
```

<details><summary><b>cu2qu incompatibility output messages</b> (Click to expand)</summary>

```
INFO:ufo2ft:Pre-processing glyphs
ERROR:cu2qu.ufo:Glyphs named 'trademark' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'Lslash' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'g.italic' have incompatible segment types:
  19: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'less' have incompatible segment types:
  7: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
  8: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'h' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'logicalnot' have incompatible segment types:
  5: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line')
  8: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'e' have incompatible segment types:
  17: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'ordfeminine' have incompatible segment types:
  24: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line')
ERROR:cu2qu.ufo:Glyphs named 'greaterequal' have incompatible segment types:
  14: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
  15: ('curve', 'curve', 'curve', 'line', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'lessequal' have incompatible segment types:
  14: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
  15: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'radical' have incompatible segment types:
  13: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
  14: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'lozenge' have incompatible segment types:
  17: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
  18: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
  22: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
  23: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'OE' have incompatible segment types:
  13: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve', 'line')
  14: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'circumflexcomb' have incompatible segment types:
  7: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve', 'curve', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'asciicircum' have incompatible segment types:
  7: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
  8: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'E' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'L' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'v' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'j' have incompatible segment types:
  12: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve', 'line', 'curve', 'curve')
  13: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve', 'line', 'curve', 'line', 'line')
  17: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve', 'line', 'curve', 'curve')
  18: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve', 'line', 'curve', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'increment' have incompatible segment types:
  12: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line', 'line', 'line')
  13: ('line', 'line', 'line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'u' have incompatible segment types:
  5: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve', 'line', 'curve', 'curve')
  7: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve', 'line', 'curve', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'x' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'g.mono' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'ampersand' have incompatible segment types:
  39: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve', 'curve', 'curve', 'curve')
  41: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve', 'line', 'line', 'line', 'line')
  42: ('curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'line', 'curve', 'curve', 'curve', 'curve')
  43: ('line', 'line', 'line', 'line', 'line', 'line', 'line', 'curve', 'line', 'line', 'line', 'line')
ERROR:cu2qu.ufo:Glyphs named 'w' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'i' have incompatible segment types:
  15: ('curve', 'line', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve', 'curve')
  18: ('line', 'curve', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line', 'line')
```

</details>

**Comment by thundernixon** [comment]
Tools that will help:

- check segments `src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-segment-types-current_glyph.py`
- check that glyphs don't have something in the `support.w.middle` layer: src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-support-layer-for-glyphs.py
- check that anchors are similar with `src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-anchor-similarity-selected-fonts.py`

Plus Prepolator and Master Tools for finding point diffs.

Maybe:
- check how character sets differ between fonts: `src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-for-charset-diff-between-selected-fonts.py`

**Comment by KatjaSchimmel** [comment]
list of glyphs to check:
/asterisk /r.italic /question /k.italic /parenright /ringacute /dotlessi /dotlessj /dotbelowcomb.case /macron /underscore /E /L /Lslash /OE /ampersand /asciicircum /circumflexcomb /e /g.italic /g.mono /greaterequal /h /i /increment /j /less /lessequal /logicalnot /lozenge /ordfeminine /radical /trademark /u /v /x

**Comment by KatjaSchimmel** [comment]
I managed to check the glyphs from /asterisk to /L today. 
There is a general issue with the design and compatibility of the /dotlessi I think:

<img width="1112" alt="Screen Shot 2019-08-07 at 16 04 41" src="https://user-images.githubusercontent.com/32390109/62631382-edc21880-b930-11e9-9198-e1c1762243c4.png">

**Comment by KatjaSchimmel** [comment]
managed to check all glyphs today. Things that came up:
- while checking the charset differences there was a problem with the glyph /fl.sans
- had to create /l.italic in Casual B Slanted
- Lisa was working on compatibility in lowercase glyphs today, too. There will be some merge conflicts tomorrow ... I will check the compatibility of the lowercase letters again after merging (/r.italic /k.italic /dotlessi /dotlessj /e /g.italic /g.mono /h /i /j /u /v /x)

**Comment by thundernixon** [comment]
Shoot, yes, there were some merge conflicts, and they got the best of me for tonight. I'll try again in the morning.

Right now, in the mono, the incompatible glyphs reported by fontparts are:

```
underscore,  dotbelowcomb.case, question, macron, ringacute, ringacute, dotlessj, parenright, dotlessi, 
```
and from cu2qu are:
```
'E', 'L', 'Lslash', 'OE', 'ampersand', 'asciicircum', 'circumflexcomb', 'g.italic', 'greaterequal', 'increment', 'less', 'lessequal', 'logicalnot', 'lozenge', 'ordfeminine', 'radical', 'trademark'
```

**Comment by LisaHuang2017** [comment]
I'll do those fixes before switching to the changes in /i and /j.

**Comment by LisaHuang2017** [comment]
These shapes makes questions and issues in interpolations and thus in compatibility... Maybe another shape of inktrap or contours should be needed?
<img width="1147" alt="Capture d’écran 2019-08-09 à 12 17 28" src="https://user-images.githubusercontent.com/32390132/62773697-166a1f80-baa3-11e9-8962-24732de31813.png">
<img width="1104" alt="Capture d’écran 2019-08-09 à 12 17 21" src="https://user-images.githubusercontent.com/32390132/62773698-1702b600-baa3-11e9-955b-d4fb926dbbc7.png">

**Comment by arrowtype** [comment]
@lisahuang2017 thanks! I hate for us to do redundant work, but maybe some is okay here. I think maybe I should try to merge Katja's work again, and potentially just reject all changes that cause merge conflicts. I believe she did do some work on symbols that might be helpful here.

As for the shape question above, we should move all those to the sharp inktrap style of the /A, /v, etc. I don't really have a preference whether there is the star-shaped corner overlap or not.

**Comment by LisaHuang2017** [comment]
I'll fix them today too :) No problem!

**Comment by arrowtype** [comment]
(so, the second image of the two is correct, whereas the top is the old style. However, I think maybe this is something Katja may have worked on?)

**Comment by LisaHuang2017** [comment]
No I worked on those glyphs and symbols, so it's normal that I fix them

**Comment by KatjaSchimmel** [comment]
I updated the symbols with new inktraps (/greater /less /increment /lozenge and so on) while I was doing the corrections in the symbols. Maybe we can have a look after Stephen merged my PR and and see which ones are still left with the old ink trap.

**Comment by LisaHuang2017** [comment]
Okay :)

**Comment by thundernixon** [comment]
Great work on this. Most of these are good, so i'll close this issue.
