### ISSUE TITLE
Make /i and /j composite glyphs from /dotlessi and /dotlessj and /dot accent

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#119]
- [ ] copy shape to /dotless thing
- [ ] give `dot` anchor to /dotless thing
- [ ] add /i and /j to glyph recipes

**Comment by LisaHuang2017** [comment]
I wonder if for situations like iogonek, as its recipe is: 
iogonek=i+ogonek@bottom
And as i=dotlessi+dotaccent@top
Would it be okay to have a glyph composed with a component that is a composite itself?
To be short, is component in component supported in the exports?

**Comment by LisaHuang2017** [comment]
Solution:
Add bottom and ogonek anchors to /dotaccentcomb, and have this recipe:
idotbelow=dotlessi+dotaccentcomb@top+dotbelowcomb@bottom
iogonek=dotlessi+dotaccentcomb@top+ogonekcomb@ogonek

So that /dotbelowcomb and /ogonekcomb attach themselves to the anchors on the previous component in the recipe.

**Comment by LisaHuang2017** [comment]
Issue resolved (with the solutions described in the previous message).
Question asked on the Robofont forum about this solution...

**Comment by thundernixon** [comment]
Just to record this for others, the proper solution, [per this response on the RF forum](https://forum.robofont.com/topic/684/is-it-possible-to-add-multiple-accents-to-a-base-glyph-with-anchors-glyph-construction), is like this:

```
iogonek = dotlessi + ogonekcomb@ogonek + dotaccentcomb@dotlessi:top
```

**Comment by thundernixon** [comment]
I think we're done with this one, but I'll open it if I find anything significant remaining. :)
