### ISSUE TITLE
Research on vertical position of /overline

### ISSUE THREAD

**Issue by KatjaSchimmel** [arrowtype/recursive#120]

**Comment by KatjaSchimmel** [comment]
corrections in the symbols are done. Just need to do some research (in other fonts) on the vertical position of the /overline glyph

**Comment by arrowtype** [comment]
![image](https://user-images.githubusercontent.com/45946693/75615874-7693e200-5b17-11ea-93bd-a3e4188730ba.png)

This is currently about the same distance above ascenders as the underscore is below the baseline. I think this is appropriate. :)
