### ISSUE TITLE
Glyphs to fix for beta 2 (incorrect shaping, temporarily-skewed italics, etc)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#129]
### Slanted versions that are skewed for Beta 1. 
- Correct in Mono and copy in if width of contours doesn't change in Sans

- [x] percent
- [x] emdash (fix, copy, widen)
- [x] perthousand
- [x] quotesinglbase
- [x] quotedblbase
- [x] dagger
- [x] daggerdbl
- [x] exclam
- [x] exclamdown
- [x] backslash
- [x] brokenbar
- [x] partialdiff
- [x] mu.math
- [x] ampersand (stephen will do this)

Sans-specfic corrections:
- [x] AE
- [x] ae
- [x] at (stephen will do this)

"Incorrect" shaping
- [x] Uring shouldn't have a connected ring (can use normal ring)
- [x] `l` in Sans light needs a sharper exit stroke, similar to `i.italic`

Possibly incorrect:
- [x] lcaron
- [x] Lcaron
- [x] Ldot

Needs adjustment in Sans:
- [x] asterisk (needs to be smaller and raised)
- [x] Y (probably should be wider, as it is in Linear C Slanted & Casual C Slanted, background layer)
- [x] Oslash
- [x] Enj
- [x] Hbar
- [x] Nhookleft
- [x] Eth, Dcroat
- [x] oe

Letters to polish (stephen will do these):
- [x] x (too light in heavy masters)
- [x] x.italic ("leans forward" in upright linear masters, also light in Heavy)
- [x] numbersign (same lean in upright & slanted, or a change? this may change w/ code ligs)
- [x] make sure straight and curly quotes are similar size

Check for kinks especially in:
- [x] s

Anchors:
- [x] /L has 'slash' in `Sans Casual B`, but no other fonts. Needs fixing & building.

**Comment by LisaHuang2017** [comment]
I'd need a discussion with @thundernixon to share the ideas of how the shapes should be :)

**Comment by arrowtype** [comment]
Next step for stephen: make simple proof and mark up changes to be made.
