### ISSUE TITLE
Commonly confused glyph pairs in source code with Mono builds

### ISSUE THREAD

**Issue by chrissimpkins** [arrowtype/recursive#13]
Stephen and Katja-

Beautiful typeface!  Love this and look forward to seeing it develop.  

I took a look at a handful of commonly confused glyphs in source code using [this specimen in the Codeface repository](https://github.com/chrissimpkins/codeface/blob/master/samplecode/compact.txt) that was collaboratively developed by a number of software developers.

I captured screenshots of that text specimen as dark on light and light on dark with syntax highlighting activated and laid this out in text editors on macOS and Windows 10.  The images in this thread are from Win 10 VS Code and are included in this archive:

[recursive-mono.zip](https://github.com/thundernixon/recursive/files/3219573/recursive-mono.zip)

Glyphs that *may* need to be addressed in order to distinguish the shapes at small sizes:

- `I` vs. `l`
- `S` vs. `5`
- `B` vs. `8`

See what you think based on the images.

Notably, the `l` and `1` look great.  This is a common issue in code fonts. :)

My 2¢!  

---

### 8px

<img width="1128" alt="8pt-light" src="https://user-images.githubusercontent.com/4249591/58372799-ecb44a00-7ef0-11e9-9f11-19bfd73baf6a.png">
<img width="1128" alt="8pt-dark" src="https://user-images.githubusercontent.com/4249591/58372800-ed4ce080-7ef0-11e9-95d7-eaed47163322.png">

### 9px

<img width="1128" alt="9pt-light" src="https://user-images.githubusercontent.com/4249591/58372671-2f752280-7eef-11e9-9ce6-c4c96c62fa54.png">
<img width="1128" alt="9pt-dark" src="https://user-images.githubusercontent.com/4249591/58372672-2f752280-7eef-11e9-841e-571c2bf1dc52.png">

### 10px

<img width="1128" alt="10pt-light" src="https://user-images.githubusercontent.com/4249591/58372676-39972100-7eef-11e9-998a-b268be373096.png">
<img width="1128" alt="10pt-dark" src="https://user-images.githubusercontent.com/4249591/58372677-39972100-7eef-11e9-99b0-594b6533d33e.png">

### 11px

<img width="1128" alt="11pt-light" src="https://user-images.githubusercontent.com/4249591/58372682-40be2f00-7eef-11e9-89ea-6158ca1fb250.png">
<img width="1128" alt="11pt-dark" src="https://user-images.githubusercontent.com/4249591/58372683-40be2f00-7eef-11e9-882b-a391a231bf48.png">

### 12px

<img width="1128" alt="12pt-dark" src="https://user-images.githubusercontent.com/4249591/58372686-4ae02d80-7eef-11e9-9b98-e0d2730697bf.png">
<img width="1128" alt="12pt-light" src="https://user-images.githubusercontent.com/4249591/58372687-4ae02d80-7eef-11e9-9b26-d9c5108d7448.png">

### 13px

<img width="1128" alt="13pt-light" src="https://user-images.githubusercontent.com/4249591/58372694-5895b300-7eef-11e9-8125-e99d4b7c2c97.png">
<img width="1128" alt="13pt-dark" src="https://user-images.githubusercontent.com/4249591/58372695-5895b300-7eef-11e9-9be4-129b83302875.png">

### 14px

<img width="1128" alt="14pt-light" src="https://user-images.githubusercontent.com/4249591/58372700-64817500-7eef-11e9-8842-729b8a27eb97.png">
<img width="1128" alt="14pt-dark" src="https://user-images.githubusercontent.com/4249591/58372701-64817500-7eef-11e9-850f-9b69ab2eb92b.png">

**Comment by arrowtype** [comment]
The fonts now have inktraps to increase the visual difference between B & 8, and stylistic sets that allows users to turn on the simplified `l` and serif-less `1`, if they feel those are too ambiguous (there is also one for `Z`, to separate it further from `2`). As for S/5, these have especially different forms in Recursive, due to the inclusion of a Serif in S.
