### ISSUE TITLE
Check that anchors are at consistent heights (esp. dot)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#135]
Stephen: write a script to check that anchors are at a consistent y position
- between all masters in the same weight (e.g. A, A slanted)
- between all related letters (dotlessi, dotlessj, dotlessi.italic, dotlessj.italic, etc)

Find a way to check that accents themselves are at a consistent height in related weights.

**Comment by arrowtype** [comment]
Closing as a duplicate of https://github.com/arrowtype/recursive/issues/190
