### ISSUE TITLE
Check /j.italic in heavy (too squished?); test duplexing of high-priority glyphs in Sans

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#136]
## Step 1: matching widths for common glyphs

These width numbers show glyphs that have inconsistent widths between different masters (the numbers aren't currently sorted in any exact order, but I intend to improve this in the future).

Because these are all basic latin glyphs, we should duplex them as soon as possible (we'll need to circle back to cover others, later).

The most common width isn't always the correct one (but usually it is). In cases such as `r`, and `r.italic`, all of these should follow the `r` and be `450` units.

Note: As you adapt italic widths for the Sans, make the serifs / “outstrokes” smaller in overall size to work within their narrow space. This is relevant to /f.italic and /r.italic (and to a lesser extent, /s.italic and /c.italic). See Sans Casual B Slanted for an approximate idea of what I’m aiming for. The "Transform" tool `T` is pretty useful for this, though obviously requires a bit of fixing after manipulation.

<details><summary><b>work done</b> (Click to expand)</summary>

You can regenerate an updated version of this report with the script `src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-for-nonconforming-widths.py`.

```
glyph              
--------------------------------------------------------------------------------------
A                     650  600  650  650  650  650  650  650  650  650  600  650

D                     650  600  650  650  650  650  650  650  650  650  600  650

E                     550  600  550  550  550  550  550  550  550  550  600  550

F                     550  600  550  550  550  550  550  550  550  550  600  550

G                     650  600  650  650  650  650  650  650  650  650  600  650

H                     650  600  650  650  650  650  650  650  650  650  600  650

I                     500  600  500  500  500  500  500  500  500  500  600  500

J                     500  600  500  500  500  500  500  500  500  500  600  500

L                     550  600  550  550  550  550  550  550  550  550  600  550

M                     800  600  800  800  800  800  800  800  800  800  600  800

N                     650  600  650  650  650  650  650  650  650  650  600  650

O                     650  650  650  650  650  650  650  650  650  650  600  650

U                     650  600  650  650  650  650  650  650  650  650  600  650

V                     650  600  650  650  650  650  650  650  650  650  600  650

W                     900  600  900  900  900  900  900  900  900  900  600  900

X                     650  600  650  650  650  650  650  650  650  650  600  650

Y                     650  600  600  600  600  600  650  600  600  600  600  600

c                     500  600  500  500  500  500  500  500  500  500  600  500

dotlessi.italic       600  600  350  600  600  600  600  350  600  600

dotlessj.italic       600  600  600  600  500  600  600  600  600  600

f                     400  600  400  400  400  400  400  400  400  400  600  400

f.italic              600  600  400  600  600  600  600  400  600  600  600  400

l                     350  350  300  300  350  350  300  350  350  300  600  350

l.italic              600  600  300  600  600  600  600  600  600  600  300

l.sans                600  600  300  600  600  600  600  350  600  600  600  350

m                     850  600  850  850  850  850  850  850  850  850  600  850

r                     450  600  450  450  450  450  450  450  450  450  600  450

r.italic              600  600  450  600  600  600  600  450  600  600  600  450

s                     550  600  550  550  550  550  550  550  550  550  600  550

t                     500  600  500  500  500  500  500  500  500  500  600  500

w                     800  600  800  800  800  800  800  800  800  800  600  800

z                     550  600  550  550  550  550  550  550  550  550  600  550
```

</details>

### Still to be done: matching alternates to their base version widths

Most `.italic` lowercase, narrowed `.mono` glyphs (the ones in the Sans masters)

- [ ] f.italic (match C weights outstrokes to those of r.italic)
- [ ] c.italic
- [ ] d.italic
- [ ] g.italic
- [ ] j.italic
- [ ] m.italic
- [ ] s.italic
- [ ] w.italic
- [ ] z.italic
- [ ] f.mono
- [ ] i.mono
- [ ] l.mono
- [ ] r.mono

## Step 2

Something much easier to fix (and worth fixing at the same time) is making the following glyphs all have widths in units of 50:

### Sans Casual A – glyphs not in units of 50

| **Glyph**            | **width** |
| -------------------- | --------: |
| ohm                  |       605 |

### Sans Casual B – glyphs not in units of 50

| **Glyph**            | **width** |
| -------------------- | --------: |
| dotlessi             |       347 |
| dotlessj             |       340 |
| iacute               |       347 |
| ibreve               |       347 |
| icircumflex          |       347 |
| idieresis            |       347 |
| igrave               |       347 |
| imacron              |       347 |
| itilde               |       347 |
| jcircumflex          |       340 |

### Sans Casual C Slanted – glyphs not in units of 50

| **Glyph**            | **width** |
| -------------------- | --------: |
| plusminus            |       602 |

### Sans Linear A – glyphs not in units of 50

| **Glyph**            | **width** |
| -------------------- | --------: |
| ordfeminine          |       601 |

### Sans Linear A Slanted – glyphs not in units of 50

| **Glyph**            | **width** |
| -------------------- | --------: |
| brevecomb            |        -1 |

## Step 3

Once the widths are good, go through each master & rebuild the diacritics, as these will need updating after the width changes. Use Glyph Construction & `src/00-recursive-scripts-for-robofont/diacritics-and-glyph_construction-recipes/diacritic-recipes-for-recursive.txt`.

**Comment by KatjaSchimmel** [comment]
managed to duplex all mentioned glyphs and re-build the diacritics with Glyph Construction yesterday. @thundernixon should have a look at the /j.italic in the Heavy styles (Linear and Casual), where the shapes had to be squeezed a lot

**Comment by thundernixon** [comment]
This is going well! With the glyph-form swapping, it's especially good. Glyphs that don't work well in the Sans, such as `j.italic`, i'm just not swapping on the Italic axis. So, the Sans Italics are slightly simpler than the mono italics. To me, that is a good thing, as they serve different purposes.
