### ISSUE TITLE
Check spacing of punctuation (and duplex)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#137]
This glyphs have had their outlines updated by being copied from the Mono masters, but this means they now have the incorrect widths. We need to reduce their overall width to look natural, but to also be duplexed (the same width) through all Sans masters and in units of 50. 

- [x] period
- [x] periodcentered
- [x] colon
- [x] comma (also make this somewhat smaller – closer in size to quotes, but only in Sans)
- [x] semicolon
- [x] parenleft
- [x] parenright
- [x] quotesingle
- [x] quoteleft
- [x] quoteright

**Comment by LisaHuang2017** [comment]
Please find the link in the repository for the proof PDF: 
recursive/src/proofs/working-proofs/081519-sans-punctuations.pdf

**Comment by LisaHuang2017** [comment]
I'd still need to check the compatibility of /quoteleft, it has a starting point that is not the same everywhere (if you look at the anchors indexes...)
