### ISSUE TITLE
Make FontTools to compile JSON of advance widths for non-600-unit glyphs

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#142]
We will show the widths of glyphs on the specimen minisite, and either cycle through glyphs or possibly let the user type their own.

Instead of doing the measurements live, we should set include a JSON file of glyphs and their widths. It would probably make sense to set the default to 600, as that covers almost all the Mono and maybe half of the Sans, and then only use a different number if one is provided. 

How I'm thinking it will work: a JSON file will include something like `{ "i": 350, "t": 450 }` etc. If a glyph is in that file, it will report its width accordingly. If it's not, it will report as `600`. 

We need a FontTools script to check a font and build this JSON.

That way, when if/when updates are made to the font in the future, I can regenerate this file to update the minisite diagram.

**Comment by arrowtype** [comment]
Completed: https://github.com/arrowtype/recursive/blob/ba3963c3d214dec471e1eec687a031eab733d31b/src/build-scripts/data-tables-for-website/get-glyph-widths-from-built-font.py
