### ISSUE TITLE
Case-sensitive punctuation

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#152]
- [x] research which punctuation to make case-sensitive
- [x] make new glyphs where height must change
- [ ] test using [OT fea code to position other case punc (e.g. `pos @case <0 40 0 0>`)](http://opentypecookbook.com/rules.html)

Gyphs that will change height:

```
parenleft parenright bracketleft bracketright braceleft braceright (maybe at)
```

Glyphs that will only change position:

```
guilsinglleft guilsinglright guillemotleft guillemotright slash backslash periodcentered bullet questiondown exclamdown hyphen endash emdash arrowleft arrowright plus minus divide
```

Number-only repositioning:

```
colon
```

Where these can be components from the normal punctuation, they should be.

**Comment by LisaHuang2017** [comment]
These are the punctuations that should have case-sensitive alternates, I believe... 

`parenleft parenright bracketleft bracketright braceleft braceright guilsinglleft guilsinglright guillemotleft guillemotright slash backslash`

**Comment by LisaHuang2017** [comment]
Added these glyphs in Sans Casual B upright first: 
```
parenleft.case parenright.case bracketleft.case bracketright.case braceleft.case braceright.case guilsinglleft.case guilsinglright.case guillemotleft.case guillemotright.case slash.case backslash.case periodcentered.case bullet.case questiondown.case exclamdown.case 
```

**Comment by LisaHuang2017** [comment]
@thundernixon Should there also be case sensitive mathematical symbols? Such as `plus minus divide` etc...

**Comment by arrowtype** [comment]
@lisahuang2017 good starter list! I think we should also include:

```
hyphen, endash, emdash, arrows
```

And yes, probably math symbols.

However, I'm remembering that there is opentype feature code that allows glyphs to be shifted relative to the base position. So, I should test adding this for any glyphs that don't change sizing for case alternates, before we add extra glyphs for these.

**Comment by LisaHuang2017** [comment]
I'll wait for you to do the test before adding the glyphs left or making more changes in this issue :)
