### ISSUE TITLE
Check inktrap angles for consistency

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#155]
Inktrap angles are intended to be as follows:
- Casual 
  - mostly horizontal or vertical
  - some angles (where strokes meet perpendicularly, as in /T)
- Casual Slanted
  - all angled, to be "perpendicular" to areas of whitespace
- Linear
  - all horizontal or vertical
- Linear Slanted
  - all horizontal or matching italic angle

For the most part, this system is followed with extreme consistency. However, there are a few glyphs which don't match this, and I'll track them here if I find them.

## Problems

Casual Slanted
- [ ] /two: has flat inktrap

**Comment by arrowtype** [comment]
Folding https://github.com/arrowtype/recursive/issues/192 into this

![image](https://user-images.githubusercontent.com/45946693/68686945-6b05b680-053a-11ea-9320-5f664d2f10a9.png)

**Comment by LisaHuang2017** [comment]
Issue #64 is related to this one.

**Comment by arrowtype** [comment]
Hey @LisaHuang2017, nice work on this so far!

I should have been more specific, but I think the previous casual /z _did_ have the correct inktrap directions, which were opposite from what is correct in the linear.

Basically, in the casual, it is the horizontal strokes which should be squishy while the spine is smooth, whereas in the Linear, the horizontals should be sturdy while the spine gets the inktrappy. So, this is the current casual, in which I think the spine gets too complex of curvature:

![image](https://user-images.githubusercontent.com/45946693/68977034-48d39900-07c5-11ea-9207-3c9c78e0d3d4.png)
