### ISSUE TITLE
Linear ExtraBold has taller vertical metrics in static fonts (mac)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#156]
Strangely, Linear ExtraBold styles have taller vertical metrics than other styles, in macOS apps like Keynote and Sketch:

![image](https://user-images.githubusercontent.com/7355414/63292800-85f6c080-c294-11e9-8999-34719a2486d4.png)

No diffs in the OS2, hhea, head, or CFF tables seem to stand out that would cause this, but obviously, I must be missing something. We'll find it soon. :)

**Comment by benkiel** [comment]
Double checked font tables again, nothing stands out. I'm going to see what happens with this when we run it though the makeOTF mastering, more answers soon-ish.

**Comment by arrowtype** [comment]
New issue here, with further detail:

https://github.com/arrowtype/recursive/issues/308

Closing this one as a duplicate.
