### ISSUE TITLE
Instances of variable font don't populate macOS style name menus well. Probably, STAT table needs fixing.

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#157]
This is likely due to the STAT table not having references for each instance.

![image](https://user-images.githubusercontent.com/7355414/63303712-9a47b700-c2ae-11e9-838d-876f4f7e79ae.png)

GFtools has the script [fix-vf-meta.py](https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-vf-meta.py) to deal with this in weight-only variable fonts. 

In Recursive, we can do one of the following to try to fix this:

- manually make a STAT table, then patch this in with `ttx -m`
- make a script to create this based on information already in the font. 

Ideally, we would do the latter, but pending time, it may make more sense to do the former.

**Comment by arrowtype** [comment]
Look at STAT patches in Open Sans.

Use format `4` blocks to patch this.

Also look into Dalton Maag STAT make: https://github.com/daltonmaag/statmake

**Comment by benkiel** [comment]
Format 4 didn't work in Windows circa Feb 19, however... (https://github.com/daltonmaag/statmake/blob/d2ab9b547ff86d46629c6f221b9f1e80b25b85ae/tests/data/Test.stylespace#L163)

**Comment by arrowtype** [comment]
In here, there are "patch" files: https://github.com/laerm0/opensans/tree/master/source

**Comment by arrowtype** [comment]
Moving this into https://github.com/arrowtype/recursive/issues/316
