### ISSUE TITLE
Can transformed components work for vietnamese diacritics? Test.

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#161]
You can use Glyph Construction to make an `ấ` like so:
```
acircumflexacute = a + acutecomb@0.8, 0, 0, 0.5, `a:top + 100`, `a:top +350` + circumflexcomb@0.8, 0, 0, 0.6, a:top, `a:top + 200`
```

This scales the diacritics in a way that allows them to fit in a reasonable place. This _should_ export well into a working variable font, but needs testing.

### Explanation of the transformation

A matrix transformation is `[xx, xy, yx, yy, x, y]`
- so, the first item scales horizontally
- the second & third do some rotation stuff
- the fourth scales vertically
- the fifth and sixth move things around in x & y directions

Relating transformation to anchor:
- We have an anchor in the /a labeled `top`, so the (x, y) transformation should be set according to that. 
- Thus, (x,y) is something like (`a:top + 100`, `a:top +350`)
- Because the rest of the transformation seems to be set based on (0,0), this (x,y) tranlation is required

**Comment by thundernixon** [comment]
Yes, it seems that the transformed components export to a variable font and work just fine.

The font in the following GIF had `acircumflexacute` added in every master with this recipe: 

```
acircumflexacute = a + acutecomb@0.8, 0, 0, 0.65, `a:top + 140`, `a:top +354` + circumflexcomb@0.9, 0, 0, 0.8, a:top, `a:top + 90`
```

![Kapture 2019-08-22 at 19 22 22](https://user-images.githubusercontent.com/7355414/63556293-34f40000-c512-11e9-926d-5197cc9cb31d.gif)

Of course, even though we now know that we _can_ add glyphs this way, it's unclear whether we _should._ The /acutecomb is really noticeably thin in the lighter weights, when the accents are added in and transformed in this way. Also, we would need a sane way to make sure that we could control the transformations enough that they wouldn't look bad in any master.

Probably, it would be quite a bit simpler to just make diacritics specific to vietnamese.

Looking at how IBM Plex does it: combined accents are pre-drawn, not as components. This may be the best approach.

![image](https://user-images.githubusercontent.com/7355414/63556543-4ab5f500-c513-11e9-897f-4c44038b424b.png)

**Comment by arrowtype** [comment]
Lisa ended up just making separate accents for the Vietnamese accents, and I think this approach is probably somewhat better. It's more obvious what to edit, and even though it adds a very small amount of data to the font, it's barely anything, and more maintainable this way.
