### ISSUE TITLE
Adjusted spacing needed in Sans masters for superiors/inferiors

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#164]
This would be best accomplished with a script that:
- sets new widths that are still tabular, but more narrow, to have more-natural spacing
- bases the width on what looks best in the heavy masters

Once you have done that, chec: 
- how these look in text and consider adjusting. They may benefit from keeping a bit of extra width
- whether this messes up alignment in fractions. If so, consider revising script to account for this.

**Comment by LisaHuang2017** [comment]
Before and after proofs for comparison:
Casual:
<img width="1587" alt="Capture d’écran 2020-01-15 à 12 15 05" src="https://user-images.githubusercontent.com/32390132/72429708-dfeeaa00-3790-11ea-8ad4-ae34456fb787.png">
<img width="1586" alt="Capture d’écran 2020-01-15 à 12 23 11" src="https://user-images.githubusercontent.com/32390132/72430693-59879780-3793-11ea-8653-4a1e65c85ebe.png">


Linear:
<img width="1587" alt="Capture d’écran 2020-01-15 à 12 15 24" src="https://user-images.githubusercontent.com/32390132/72429719-e5e48b00-3790-11ea-9cdf-385c350e69bc.png">
<img width="1588" alt="Capture d’écran 2020-01-15 à 12 32 59" src="https://user-images.githubusercontent.com/32390132/72430708-6310ff80-3793-11ea-8ed3-09bee48258e4.png">
