### ISSUE TITLE
Make script to generate charset completion report

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#168]
The full scope of the character set for Recursive is documented at [docs/00--character_set_for_google_fonts](https://github.com/arrowtype/recursive/tree/master/docs/00--character_set_for_google_fonts)  (Or at this [permalink to the current latest commit, 7739cbb](https://github.com/arrowtype/recursive/tree/7739cbb7aa812ec3c92d0bc76416592f31701eeb/docs/00--character_set_for_google_fonts))

It will be simplest to attain this character set by:

1. making a full list of expected glyph names, including alternates, ligatures, case-specific punctuation, etc.
  - this list should include unicode values where needed
2. making a script that checks UFOs against this full list and outputs a report of diffs

**Comment by LisaHuang2017** [comment]
First part of ligatures in Issue [176](https://github.com/arrowtype/recursive/issues/176)

**Comment by arrowtype** [comment]
Closed with https://github.com/arrowtype/recursive/commit/f40cbf6222d1b20ab7c0ee07f37914264ba98938
