### ISSUE TITLE
Check for kinks – especially in diagonals (/w, /v, etc) and curves (/s, /S)

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#170]
Kinks often occur in interpolations if the angle or ratio of point "handles" change.

Some kinks are inevitable in this designspace, due to big changes to curvature in slant and expression axes. We need to prioritize which kinks to seek out and reduce the severity of, and define a "margin of acceptable error" for things that won't be prominent enough to matter.

(I'll add more detail here soon.)

**Comment by LisaHuang2017** [comment]
@thundernixon Could you add the details about the corrections to do here please? Thanks :)
