### ISSUE TITLE
Bring code ligatures accross the family - part 01

### ISSUE THREAD

**Issue by LisaHuang2017** [arrowtype/recursive#176]
Some code ligatures has been designed already in the Mono B uprights, and need to be brought into the other weights and styles:
`&&`

And these below need to be sketched in B weights, validated by Stephen then brought into the other weights too:
`??, %%,  <=, >=` and `=>`

**Comment by LisaHuang2017** [comment]
Some sketches... (in Mono Casual B upright)
<img width="959" alt="Capture d’écran 2019-09-26 à 11 32 51" src="https://user-images.githubusercontent.com/32390132/65677202-7b78d500-e051-11e9-86ea-b31ff52cee2e.png">

**Comment by arrowtype** [comment]
I'm liking these sketches a lot!

One note: the `<=`, `>=`, and `=>` ligatures must be double-width (1200 units). Basically, all code ligatures must take up the same amount of space as their component glyphs, added up, so that they don't move code around when they are activated. They are good to give a little extra spacing on either side, to distinguish these combinations as "single units." However, in terms of the `<=` and `>=`, they should be somewhat larger than normal to fill most of the space.

**Comment by LisaHuang2017** [comment]
Proof PDF in /recursive/src/proofs/working-proofs/102019-code-ligatures

**Comment by arrowtype** [comment]
Awesome work so far!

Looking at these, the one thing distracting me is the `=>` ligature.

For most of the styles, it keeps the same (or almost the same) slope of the arrowhead as the other arrows. This means that, especially in the bolder weights, the arrow head starts to really bunch of and look extra heavy.

![image](https://user-images.githubusercontent.com/45946693/66729108-cf840780-ee0e-11e9-85b8-db253aba1ddd.png)

In general, I think that these arrowheads could get maybe 10 degrees steeper, and probably a bit more so in the Linear styles, where the flat lines make it more obvious that it's a pointy object. Overall, I think the steepness of `Casual B` is looking really good, and the others could match that a bit more.

Also, I think that in weights B and C, the arrowhead probably needs to get a bit thinner, to compensate for all the weight in that area, and too look more balanced with the tapered strokes that intersect into it.

**Comment by arrowtype** [comment]
Next steps for me:

- [ ] make list of all code ligatures
- [ ] adapt python script to check for completion

**Comment by arrowtype** [comment]
Next steps:
- [x] change name `f_quote.code` to `f_singlequote.code`
- [ ] find issue with asterix

**Comment by arrowtype** [comment]
Should be fixed with acaa65ca8
