### ISSUE TITLE
Check that descenders are aligned as intended

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#178]
I specifically want most descenders to be relatively short, except for "tails" that need extra space to be a bit longer – in particular, the double-story /g.

Down to `-250`:
- /g (except in weight C)
  - /g.mono (except in weight C)
- some accents 

Down to only `-200`
- /g & /g.mono in weight C
- /g.italic
- /f.italic
- /p
- /q
- /j
  - /j.italic
  - /j.mono
- /y
  - /y.italic

Currently, I'm noticing that there are quite a few times at which the `/j` or `/y` go further than intended. This needs a specific review, and fixes where

**Comment by arrowtype** [comment]
For this, it would be most effective to adapt a [drawbot script for robofont](https://robofont.com/documentation/building-tools/toolspace/drawbot/) to lay out all glyphs with descenders, plus vertical metrics. 

Maybe even better: make a script that checks the yMin in a list of glyphs. If it is below `-200`, flag it.

**Comment by LisaHuang2017** [comment]
(note: /j.mono is missing in all masters)
Mono masters: 
<img width="955" alt="Capture d’écran 2020-01-10 à 16 54 27" src="https://user-images.githubusercontent.com/32390132/72166696-03e57080-33ca-11ea-90b3-8a7a9c96ac70.png">
<img width="940" alt="Capture d’écran 2020-01-10 à 16 54 33" src="https://user-images.githubusercontent.com/32390132/72166702-05af3400-33ca-11ea-975e-3edc39ab4047.png">

Sans masters:
<img width="1182" alt="Capture d’écran 2020-01-10 à 17 05 13" src="https://user-images.githubusercontent.com/32390132/72167965-7a836d80-33cc-11ea-90b6-290aa25ea6fb.png">
<img width="1173" alt="Capture d’écran 2020-01-10 à 17 12 37" src="https://user-images.githubusercontent.com/32390132/72167966-7b1c0400-33cc-11ea-8669-61a6f79f5ce5.png">
