### ISSUE TITLE
The angle of “/” in casual style does not change with slant variation

### ISSUE THREAD

**Issue by charakterziffer** [arrowtype/recursive#183]
The slash (/) in italic/oblique casual styles seems to have the same angle as in the upright versions. So with the XPRN axis at 1 the SLNT variation no longer has an effect on the slash. The problem with this is, that the slash becomes confusable with the bar (|) in italic contexts.
(Font version 1.019, tested with static files and on https://www.recursive.design/)

BTW: What an unbelievably great font family!

**Comment by arrowtype** [comment]
Thank you for the issue and for the kind words, @charakterziffer! Thanks for fixing this, @LisaHuang2017 :)
