### ISSUE TITLE
Make script to check for consistency for accents (height, relative positioning) within weights

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#190]
Right now, there are instances of unintended variability in the positioning of accent anchors, especially between upright and slanted versions of a glyph within the same weight.

A common issue: the `top` anchor will have the same coordinate position some masters, but different positions in other masters. This is probably because different people collaborated on accents, in different masters and different phases. 

(I think I was positioning this according to the top Y coordinate of letter bounds, which are higher in bolder weights. However, thinking this through further, I am now unsure whether this is actually beneficial. So long as the top accents are designed and positioned well, the `top` anchor should seemingly be fine in the same copied position between all masters.)

Overall, this is a very minor issue, but something that would stand out in transitions / animations. So, if it comes up in proofing or in use, it would be worth evaluating again.

**Comment by LisaHuang2017** [comment]
Issue #135 is related to this one.

**Comment by arrowtype** [comment]
Thanks, Lisa! I'll close that one in favor of this one.

**Comment by arrowtype** [comment]
Fastest: we could potentially try to cycle through the built VF in Dynamo Font Gauntlet (we may need to subset it to make this work).

Another possibility: we could make a drawbot script to lay out accented characters in all masters, then visually check.

Another possibility: we could find a way to automate this further? However, I can't imagine much of a better way.

**Comment by arrowtype** [comment]
Better solution: use Type Network's video proof website.

**Comment by arrowtype** [comment]
With https://videoproof.typenetwork.com/, I was able to determine with a fairly high level of confidence that the accents maintain visual alignment through styles. I will be open to future issues on this, but I don’t expect any in the character set. (There are still outstanding issues of the font lacking a `mark` feature, https://github.com/arrowtype/recursive/issues/217).

![image](https://user-images.githubusercontent.com/45946693/101168865-16801e00-360a-11eb-8398-a209dc5ce8a5.png)
