### ISSUE TITLE
Make alternate versions of /ogonek for better connection

### ISSUE THREAD

**Issue by LisaHuang2017** [arrowtype/recursive#193]
/ogonek accent as its "default" shape doesn't connect well or in the right position in letters like /o or /e. 

More alternates should be added, and Glyphs Builder's recipes modified.

**Comment by arrowtype** [comment]
These look excellent! Thanks so much for improving this. :)
![image](https://user-images.githubusercontent.com/45946693/68046308-f452f880-fcb1-11e9-9a7b-062c21f7dcbd.png)
