### ISSUE TITLE
Arrows in Sans masters with proportional widths

### ISSUE THREAD

**Issue by LisaHuang2017** [arrowtype/recursive#194]
Especially with /leftrightarrow, which should be wider and composed with two /arrowhead as components.

**Comment by LisaHuang2017** [comment]
Added a proof pdf in this [pull request](https://github.com/arrowtype/recursive/pull/196/commits/384a575bfd6cf7853b5e50b896995c9fec533c63) or in the folder working-proofs > 092019-geometric-shapes > Recursive-arrows-mono-to-sans-20191017.pdf

**Comment by arrowtype** [comment]
These look great! Thanks for making these happen. :)
