### ISSUE TITLE
/hook has incorrect unicode – is "ocr hook" but should be something else

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#208]
![image](https://user-images.githubusercontent.com/45946693/68027689-606d3680-fc89-11e9-8e15-1d601fb6c47a.png)

- [ ] find proper unicode
- [ ] update in all masters

(Also, by the way, we don't need the OCR hook in this character set, so this is a note to not add it)

**Comment by LisaHuang2017** [comment]
(OCR) /hook (unicode 2440) is now in all masters, but had inconsistent widths (which is now fixed).
If we delete /hook, we have to decompose it from component to contours in /hookcomb. Same for /horn in /horncomb.

**Comment by arrowtype** [comment]
I'm basically following the lead of IBM Plex on accents, which is why most accents have a positive-width version (e.g. [acute](https://www.fileformat.info/info/unicode/char/00b4/index.htm)) plus a combining version (e.g. [acutecomb](http://www.fileformat.info/info/unicode/char/0301/index.htm)).

However, it strangely seems that there isn't a specific unicode for a positive-width hook above – only one for [hookcomb](https://www.fileformat.info/info/unicode/char/0309/index.htm).

So, I will simply remove the current /hook glyph (unicode 2440), as that points to something else; the [OCR Hook](https://www.fileformat.info/info/unicode/char/2440/index.htm). I can't even figure out what that glyph is specifically used for in OCR, just that it is part of [a required set for OCR-A](https://en.wikipedia.org/wiki/Optical_Character_Recognition_(Unicode_block)). It must be a type of punctuation/syntax of sorts for computers that are reading OCR documents.

**Comment by arrowtype** [comment]
Okay, I've removed the /hook and /horn from the UFOs and things seem to be working well (commits a7ef23d189763b4f6e3a247fa9596c191166dfa6 and fdc59006e4dabd6b12bf9c54352680c67edb5b58). Sorry to file an issue for them to be given uniform widths – I hadn't quite thought through the fact that there were overlapping/conflicting issues.
