### ISSUE TITLE
Kerning: make sure all alternates (.italic, .mono, .sans) are grouped with base glyphs

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#210]
Right now, kerning is changing line lengths. 

Unhelpful as it may be for perfect kerning, it is a priority to keep everything duplexed in Recursive – even if it means imperfect kerning. 

Therefore, we need to make sure glyph substitution doesn't impact spacing. To do this, we need to make sure to check that alternates are grouped with bases.

This should start as a manual check, but ultimately needs to have a QA script.

**Comment by LisaHuang2017** [comment]
Now that all /l diacritics combinations are created and added (from issue #274 ) into the kerning groups of Sans masters, this issue is complete and can be closed.
