### ISSUE TITLE
Make versions of /at glyph to allow case & alternate features

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#212]
- [x] `at` – Default; “compressed” version that descends past the baseline to work well with mixed-case code.

- [x] `at.case` – Shaped like the default, but only goes from baseline to cap height, to be set with all-caps text. 

- [x] `at.alt` – More like the simplified form in fonts menlo; basically what is currently in the masters as “at.cap.” Should descend past baseline. (Status: close to being done, was previously called "at.cap." However, the light versions should be the same height as the bold versions, and the linear versions should be low-contrast in Sans)

- [x] `at.alt_case` – Like /at.alt, but only goes from baseline to cap height, to be set with all-caps text.

@LisaHuang2017 if you have time to draw these, I can write the code to make this work! Thanks for bringing my attention to the fact that the default style here might not be everyone's favorite.

**Comment by LisaHuang2017** [comment]
In some masters, there are /at.cap and /at.short that are not part of the missing /at signs listed up there. We don't know yet if they are still needed or can be removed...
<img width="703" alt="Capture d’écran 2019-11-04 à 19 07 40" src="https://user-images.githubusercontent.com/32390132/68145637-89662380-ff36-11e9-9205-843a27afb5e1.png">

**Comment by arrowtype** [comment]
Thanks for the great work here, Lisa!

I'll close this for now, and reopen it if needed, once I write this OpenType feature.
