### ISSUE TITLE
match spacing of /fi to left of f and right of i (probably, will be 750 wide, rather than 800)

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#215]
First off, I'm pretty stoked about the /fi ligature. :) It was a pleasant surprise to find that it works witht the exact behavior I wanted after a very simple opentype feature rule, and didn't even require any sort of GSUB code in the designspace. It also just looks pretty darn cool!

![Kapture 2019-11-04 at 19 12 28](https://user-images.githubusercontent.com/45946693/68168626-6720d580-ff37-11e9-8911-4a45027e5d7b.gif)

## Spacing issue

However, it does currently cause a bit of a spacing issue: the right and left sides end up looking a little too loose, in comparison to the rest of the font, and also to the left of /f and the right of /i.

So, we should tweak this glyph so that it is less of a drastic change from either of those two parents, and I think it will be quite a bit better.

My guess is, the /fi glyph should be the width of /f plus /i – or `750`, rather than `800`. In Recursive Sans, /fi is a ligature slightly more for style than for spacing. (Potentially, the stem of the /f should move rightwards slightly, if the gap between the /f and /i is too great.)

## Tweak the /f hook

One extra tweak that would be useful: the hook of the /f in /fi should be slightly shorter in the bolder weights, so that it doesn't come quite so close to crashing into the dot of the /i. I think it would probably be ideal if this gap were about the same gap between the left of a normal /f and /n (around twice as big as it currently is).

Current instances where it is too close:

![image](https://user-images.githubusercontent.com/45946693/68168751-d696c500-ff37-11e9-971a-adc793b55804.png)

![image](https://user-images.githubusercontent.com/45946693/68168759-db5b7900-ff37-11e9-8448-552170ba0931.png)

**Comment by arrowtype** [comment]
One further detail: the /f in the /fi.italic should not have a descender, as the ligature only happens in Sans, and I don't activate the long-tailed /f in Sans (it stays "roman" along with a few other glyphs that are more cursive in the Mono).

So, this result is _almost_ the right shape, and the only thing that should be different is that the italic /i should have its little out-stroke:

![image](https://user-images.githubusercontent.com/45946693/68180396-8e8c9800-ff61-11e9-8d42-2269bf7ba05b.png)

Meanwhile, for /fl, I have found that it is very useful when the /l is italic, because it has the top in-stroke, but it stays more readable when we avoid making the ligature in the upright Sans (basically, the /fl working exactly as I want it to right now).

![image](https://user-images.githubusercontent.com/45946693/68180410-9cdab400-ff61-11e9-9fb8-86f6d5551b18.png)

**Comment by LisaHuang2017** [comment]
<img width="1524" alt="Capture d’écran 2020-01-15 à 12 41 54" src="https://user-images.githubusercontent.com/32390132/72431302-c94a5200-3794-11ea-87c4-42b27326344a.png">
<img width="1512" alt="Capture d’écran 2020-01-15 à 12 43 19" src="https://user-images.githubusercontent.com/32390132/72431303-c9e2e880-3794-11ea-8af0-f69ced396b2e.png">

note: maybe the /f.italic in Linear C can be much narrower to avoid overlaps?
