### ISSUE TITLE
left and right braces are not vertically aligned

### ISSUE THREAD

**Issue by saljam** [arrowtype/recursive#219]
with mono=0, casl=0, slrt=0, and wght somewhere in the middle (say 660), the left and right braces are not aligned vertically:
<img width="304" alt="‏لقطة الشاشة ٢٠١٩-١١-٠٦ في ١١ ٠٦ ٢٨" src="https://user-images.githubusercontent.com/751023/68293347-a9f0c380-0085-11ea-9b2e-5b499593be17.png">

the problem goes away with wght=300 or wght=1000:
<img width="112" alt="‏لقطة الشاشة ٢٠١٩-١١-٠٦ في ١١ ٠٧ ١٤" src="https://user-images.githubusercontent.com/751023/68293392-c0971a80-0085-11ea-9d66-ab8dcb5d86d9.png">
<img width="121" alt="‏لقطة الشاشة ٢٠١٩-١١-٠٦ في ١١ ٠٧ ٢٦" src="https://user-images.githubusercontent.com/751023/68293397-c2f97480-0085-11ea-8996-d369d18cd1c8.png">

this was on firefox 70.0 on macos mojave using the sliders on https://www.recursive.design/.

**Comment by FraserEmbrey** [comment]
This occurs for me as well. The braces align correctly when I increase the casual and monospace axes and also increasing the slant, either together or independently.

The issue occurs on the website on safari and Firefox (both on macOS). Visible in FontBook and occurs in Sketch with the 1.022 beta font

**Comment by arrowtype** [comment]
Thanks so much, @saljam and @FraserEmbrey! We'll fix this. :)

**Comment by LisaHuang2017** [comment]
Issue solved, thanks @saljam and @FraserEmbrey ! :D

**Comment by arrowtype** [comment]
I'm reopening this until I can make sure the fixes in sources are built into usable font files and will close when I am able to push those into the repo (soon!). 

Thanks for fixing the sources, Lisa!

**Comment by LisaHuang2017** [comment]
Mono masters:
<img width="1208" alt="Capture d’écran 2020-01-10 à 17 38 32" src="https://user-images.githubusercontent.com/32390132/72169833-21b5d400-33d0-11ea-84e3-c2aa15c8e2ad.png">
<img width="1214" alt="Capture d’écran 2020-01-10 à 17 38 55" src="https://user-images.githubusercontent.com/32390132/72169834-21b5d400-33d0-11ea-9627-64d30a76c13d.png">

Sans masters:
<img width="1172" alt="Capture d’écran 2020-01-10 à 17 45 02" src="https://user-images.githubusercontent.com/32390132/72170327-013a4980-33d1-11ea-8f76-1e4c65cedbb9.png">
<img width="1173" alt="Capture d’écran 2020-01-10 à 17 45 25" src="https://user-images.githubusercontent.com/32390132/72170329-01d2e000-33d1-11ea-9678-588b3af7aa8d.png">
