### ISSUE TITLE
Static font names fail to work well in most applications in Windows

### ISSUE THREAD

**Issue by nyteshade** [arrowtype/recursive#223]
Under Windows 10 Pro, most applications cannot locate or find the fonts specified. If they do, the full name isn't found or selected properly. I had to double click the font, find the official name, with version in it, and type it in. For example:

Recursive Mono Static Beta 1.020 Casual Medium

**Comment by arrowtype** [comment]
Hi Nyteshade, thanks a lot for filing an issue on it and for adding some details!

I think this issue has also been filed at https://github.com/arrowtype/recursive/issues/225, and there is a bit of detail on how we'll fix this in that discussion. So, closing this to track the issue there.
