### ISSUE TITLE
Unicodes remaining to meet full Google Fonts glyph set (Core + Plus + Pro + Expert, modified)

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#224]
To be "finished" with this typeface in an official sense, we must create the full glyph set agreed to. This is an extensive Google Fonts Latin glyph set (Core + Plus + Pro + Expert, modified), [documented in detail here](https://github.com/arrowtype/recursive/tree/master/docs/00--character_set_for_google_fonts) ([permalink](https://github.com/arrowtype/recursive/tree/master/docs/00--character_set_for_google_fonts)).

A simple view of glyphs in the latest font build is [available here](https://arrowtype.github.io/recursive/00--character_set_for_google_fonts/web-test/index.html).

Missing glyphs have been checked for with [this glyph coverage script](https://github.com/arrowtype/recursive/blob/master/docs/00--character_set_for_google_fonts/glyphset-coverage-test.py), comparing the most recent font build against [this compiled list of GF Glyph Sets minus glyphs we are specifically not building](https://github.com/arrowtype/recursive/blob/78ccdbd4e4d64c5ac1ebd08bc4c452dabcd76439/docs/00--character_set_for_google_fonts/google-plus-for-recursive-robofont_charset--oct_2019.txt).

<details><summary><b>Unicodes missing, as of Nov 7</b> (Click to expand)</summary>

## Gyph set:
![image](https://user-images.githubusercontent.com/45946693/68436047-de01dc80-018a-11ea-8dbc-6f5d6efb5b2a.png)

### Glyphs to draw / design

- [x] `0x2052` ⁒ commercial minus sign
- [x] `0x2012` ‒ figure dash
- [x] `0x2015` ― horizontal bar
- [x] `0x2205` ∅ empty set
- [x] `0x02BC` ʼ modifier letter apostrophe
- [x] `0x030F` ̏ combining double grave accent
- [x] `0x0311` ̑ combining inverted breve
- [x] `0x0324` ̤ combining diaeresis below
- [x] `0x0335` ̵ combining short stroke overlay
- [x] `0x00A0`   no-break space
- [x] `0x00AD` ­ soft hyphen

### Can be built from existing components / with Glyph Construction

Note: some of these may require anchors to be given to other combining glyphs.

- [x] `0x0200` Ȁ latin capital letter a with double grave
- [x] `0x0201` ȁ latin small letter a with double grave
- [x] `0x0202` Ȃ latin capital letter a with inverted breve
- [x] `0x0203` ȃ latin small letter a with inverted breve
- [x] `0x0204` Ȅ latin capital letter e with double grave
- [x] `0x0205` ȅ latin small letter e with double grave
- [x] `0x0206` Ȇ latin capital letter e with inverted breve
- [x] `0x0207` ȇ latin small letter e with inverted breve
- [x] `0x0208` Ȉ latin capital letter i with double grave
- [x] `0x0209` ȉ latin small letter i with double grave
- [x] `0x020A` Ȋ latin capital letter i with inverted breve
- [x] `0x020B` ȋ latin small letter i with inverted breve
- [x] `0x020C` Ȍ latin capital letter o with double grave
- [x] `0x020D` ȍ latin small letter o with double grave
- [x] `0x020E` Ȏ latin capital letter o with inverted breve
- [x] `0x020F` ȏ latin small letter o with inverted breve
- [x] `0x0210` Ȑ latin capital letter r with double grave
- [x] `0x0211` ȑ latin small letter r with double grave
- [x] `0x0212` Ȓ latin capital letter r with inverted breve
- [x] `0x0213` ȓ latin small letter r with inverted breve
- [x] `0x0214` Ȕ latin capital letter u with double grave
- [x] `0x0215` ȕ latin small letter u with double grave
- [x] `0x0216` Ȗ latin capital letter u with inverted breve
- [x] `0x0217` ȗ latin small letter u with inverted breve
- [x] `0x022A` Ȫ latin capital letter o with diaeresis and macron
- [x] `0x022B` ȫ latin small letter o with diaeresis and macron
- [x] `0x022C` Ȭ latin capital letter o with tilde and macron
- [x] `0x022D` ȭ latin small letter o with tilde and macron
- [x] `0x0230` Ȱ latin capital letter o with dot above and macron
- [x] `0x0231` ȱ latin small letter o with dot above and macron
- [x] `0x1EF6` Ỷ latin capital letter y with hook above
- [x] `0x1EF7` ỷ latin small letter y with hook above
- [x] `0x1E08` Ḉ latin capital letter c with cedilla and acute
- [x] `0x1E09` ḉ latin small letter c with cedilla and acute
- [x] `0x1E0C` Ḍ latin capital letter d with dot below
- [x] `0x1E0D` ḍ latin small letter d with dot below
- [x] `0x1E0E` Ḏ latin capital letter d with line below
- [x] `0x1E0F` ḏ latin small letter d with line below
- [x] `0x1E14` Ḕ latin capital letter e with macron and grave
- [x] `0x1E15` ḕ latin small letter e with macron and grave
- [x] `0x1E16` Ḗ latin capital letter e with macron and acute
- [x] `0x1E17` ḗ latin small letter e with macron and acute
- [x] `0x1E1C` Ḝ latin capital letter e with cedilla and breve
- [x] `0x1E1D` ḝ latin small letter e with cedilla and breve
- [x] `0x1E20` Ḡ latin capital letter g with macron
- [x] `0x1E21` ḡ latin small letter g with macron
- [x] `0x1E24` Ḥ latin capital letter h with dot below
- [x] `0x1E25` ḥ latin small letter h with dot below
- [x] `0x1E2A` Ḫ latin capital letter h with breve below
- [x] `0x1E2B` ḫ latin small letter h with breve below
- [x] `0x1E2E` Ḯ latin capital letter i with diaeresis and acute
- [x] `0x1E2F` ḯ latin small letter i with diaeresis and acute
- [x] `0x1E36` Ḷ latin capital letter l with dot below
- [x] `0x1E37` ḷ latin small letter l with dot below
- [x] `0x1E3A` Ḻ latin capital letter l with line below
- [x] `0x1E3B` ḻ latin small letter l with line below
- [x]`0x1E42` Ṃ latin capital letter m with dot below
- [x] `0x1E43` ṃ latin small letter m with dot below
- [x] `0x1E44` Ṅ latin capital letter n with dot above
- [x] `0x1E45` ṅ latin small letter n with dot above
- [x] `0x1E46` Ṇ latin capital letter n with dot below
- [x] `0x1E47` ṇ latin small letter n with dot below
- [x] `0x1E48` Ṉ latin capital letter n with line below
- [x]`0x1E49` ṉ latin small letter n with line below
- [x] `0x1E4C` Ṍ latin capital letter o with tilde and acute
- [x] `0x1E4D` ṍ latin small letter o with tilde and acute
- [x] `0x1E4E` Ṏ latin capital letter o with tilde and diaeresis
- [x] `0x1E4F` ṏ latin small letter o with tilde and diaeresis
- [x] `0x1E50` Ṑ latin capital letter o with macron and grave
- [x] `0x1E51` ṑ latin small letter o with macron and grave
- [x] `0x1E52` Ṓ latin capital letter o with macron and acute
- [x]`0x1E53` ṓ latin small letter o with macron and acute
- [x] `0x1E5A` Ṛ latin capital letter r with dot below
- [x] `0x1E5B` ṛ latin small letter r with dot below
- [x] `0x1E5E` Ṟ latin capital letter r with line below
- [x] `0x1E5F` ṟ latin small letter r with line below
- [x] `0x1E60` Ṡ latin capital letter s with dot above
- [x] `0x1E61` ṡ latin small letter s with dot above
- [x] `0x1E62` Ṣ latin capital letter s with dot below
- [x] `0x1E63` ṣ latin small letter s with dot below
- [x] `0x1E64` Ṥ latin capital letter s with acute and dot above
- [x] `0x1E65` ṥ latin small letter s with acute and dot above
- [x] `0x1E66` Ṧ latin capital letter s with caron and dot above
- [x] `0x1E67` ṧ latin small letter s with caron and dot above
- [x] `0x1E68` Ṩ latin capital letter s with dot below and dot above
- [x] `0x1E69` ṩ latin small letter s with dot below and dot above
- [x] `0x1E6C` Ṭ latin capital letter t with dot below
- [x] `0x1E6D` ṭ latin small letter t with dot below
- [x] `0x1E6E` Ṯ latin capital letter t with line below
- [x] `0x1E6F` ṯ latin small letter t with line below
- [x] `0x1E78` Ṹ latin capital letter u with tilde and acute
- [x] `0x1E79` ṹ latin small letter u with tilde and acute
- [x] `0x1E7A` Ṻ latin capital letter u with macron and diaeresis
- [x] `0x1E7B` ṻ latin small letter u with macron and diaeresis
- [x] `0x1E8E` Ẏ latin capital letter y with dot above
- [x] `0x1E8F` ẏ latin small letter y with dot above
- [x] `0x1E92` Ẓ latin capital letter z with dot below
- [x] `0x1E93` ẓ latin small letter z with dot below
- [x] `0x1E97` ẗ latin small letter t with diaeresis

### Glyphs we have drawn, but which may have missing unicodes or other build issues

- [x] `0x2010` ‐ hyphen
- [x] `0x20B9` ₹ indian rupee sign
- [x] `0x20BA` ₺ turkish lira sign
- [x] `0x2219` ∙ bullet operator

## Glyphs listed in GF Glyph Sets which we need to check manually (no unicode values to automatically check agains):

- [x] f_f
- [x] circumflexcomb_acutecomb
- [x] circumflexcomb_gravecomb
- [x] circumflexcomb_hookabovecomb
- [x] circumflexcomb_tildecomb
- [x] brevecomb_acutecomb
- [x] brevecomb_gravecomb
- [x] brevecomb_hookabovecomb
- [x] brevecomb_tildecomb
- [x] idotaccent
- [x] caroncomb.alt
- [x] periodcentered.loclCAT

## Glyphs to investigate (probably should be removed; may currently have incorrect unicode values)

- [x] `0x01B3` Ƴ latin capital letter y with hook
- [x] `0x01B4` ƴ latin small letter y with hook

## Glyphs to remove

✅ `0x2440` ⑀ ocr hook

---

## Unicodes created beyond GF Latin glyph sets

✅ `0x0132` Ĳ latin capital ligature ij
✅ `0x0133` ĳ latin small ligature ij
✅ `0x0149` ŉ latin small letter n preceded by apostrophe
✅ `0x019D` Ɲ latin capital letter n with left hook
✅ `0x0315` ̕ combining comma above right
✅ `0x0E3F` ฿ thai currency symbol baht
✅ `0x203E` ‾ overline
✅ `0x20A8` ₨ rupee sign
✅ `0x20AA` ₪ new sheqel sign
✅ `0x20B4` ₴ hryvnia sign
✅ `0x20B8` ₸ tenge sign
✅ `0x20BF` ₿ bitcoin sign
✅ `0x2194` ↔ left right arrow
✅ `0x2195` ↕ up down arrow
✅ `0x2196` ↖ north west arrow
✅ `0x2197` ↗ north east arrow
✅ `0x2198` ↘ south east arrow
✅ `0x2199` ↙ south west arrow
✅ `0x2261` ≡ identical to
✅ `0x2661` ♡ white heart suit
✅ `0x2665` ♥ black heart suit
✅ `0xE132`  (no unicode name)
✅ `0xE133`  (no unicode name)
✅ `0xF8FF`  (no unicode name)
✅ `0xFB00` ﬀ latin small ligature ff
✅ `0xFB03` ﬃ latin small ligature ffi
✅ `0xFB04` ﬄ latin small ligature ffl

</details>

<details><summary><b>Unicodes missing, as of Nov 11</b> (Click to expand)</summary>

Unicodes missing:
- [ ] `0x000D`   carriage return
- [x] `0x00A0`   no-break space
- [x] `0x00AD` ­ soft hyphen
- [ ] `0x0200` Ȁ latin capital letter a with double grave
- [ ] `0x0201` ȁ latin small letter a with double grave
- [ ] `0x0202` Ȃ latin capital letter a with inverted breve
- [ ] `0x0203` ȃ latin small letter a with inverted breve
- [ ] `0x0204` Ȅ latin capital letter e with double grave
- [ ] `0x0205` ȅ latin small letter e with double grave
- [ ] `0x0206` Ȇ latin capital letter e with inverted breve
- [ ] `0x0207` ȇ latin small letter e with inverted breve
- [ ] `0x0208` Ȉ latin capital letter i with double grave
- [ ] `0x0209` ȉ latin small letter i with double grave
- [ ] `0x020A` Ȋ latin capital letter i with inverted breve
- [ ] `0x020B` ȋ latin small letter i with inverted breve
- [ ] `0x020C` Ȍ latin capital letter o with double grave
- [ ] `0x020D` ȍ latin small letter o with double grave
- [ ] `0x020E` Ȏ latin capital letter o with inverted breve
- [ ] `0x020F` ȏ latin small letter o with inverted breve
- [ ] `0x0210` Ȑ latin capital letter r with double grave
- [ ] `0x0211` ȑ latin small letter r with double grave
- [ ] `0x0212` Ȓ latin capital letter r with inverted breve
- [ ] `0x0213` ȓ latin small letter r with inverted breve
- [ ] `0x0214` Ȕ latin capital letter u with double grave
- [ ] `0x0215` ȕ latin small letter u with double grave
- [ ] `0x0216` Ȗ latin capital letter u with inverted breve
- [ ] `0x0217` ȗ latin small letter u with inverted breve
- [ ] `0x022A` Ȫ latin capital letter o with diaeresis and macron
- [ ] `0x022B` ȫ latin small letter o with diaeresis and macron
- [ ] `0x022C` Ȭ latin capital letter o with tilde and macron
- [ ] `0x022D` ȭ latin small letter o with tilde and macron
- [ ] `0x0230` Ȱ latin capital letter o with dot above and macron
- [ ] `0x0231` ȱ latin small letter o with dot above and macron
- [x] `0x02BC` ʼ modifier letter apostrophe
- [x] `0x030F` ̏ combining double grave accent
- [x] `0x0311` ̑ combining inverted breve
- [x] `0x0324` ̤ combining diaeresis below
- [x] `0x0335` ̵ combining short stroke overlay
- [x] `0x2010` ‐ hyphen
- [x] `0x2052` ⁒ commercial minus sign
- [x] `0x2219` ∙ bullet operator
- [ ] `0x1E08` Ḉ latin capital letter c with cedilla and acute
- [ ] `0x1E09` ḉ latin small letter c with cedilla and acute
- [ ] `0x1E0C` Ḍ latin capital letter d with dot below
- [ ] `0x1E0D` ḍ latin small letter d with dot below
- [ ] `0x1E0E` Ḏ latin capital letter d with line below
- [ ] `0x1E0F` ḏ latin small letter d with line below
- [ ] `0x1E14` Ḕ latin capital letter e with macron and grave
- [ ] `0x1E15` ḕ latin small letter e with macron and grave
- [ ] `0x1E16` Ḗ latin capital letter e with macron and acute
- [ ] `0x1E17` ḗ latin small letter e with macron and acute
- [ ] `0x1E1C` Ḝ latin capital letter e with cedilla and breve
- [ ] `0x1E1D` ḝ latin small letter e with cedilla and breve
- [ ] `0x1E20` Ḡ latin capital letter g with macron
- [ ] `0x1E21` ḡ latin small letter g with macron
- [ ] `0x1E24` Ḥ latin capital letter h with dot below
- [ ] `0x1E25` ḥ latin small letter h with dot below
- [ ] `0x1E2A` Ḫ latin capital letter h with breve below
- [ ] `0x1E2B` ḫ latin small letter h with breve below
- [ ] `0x1E2E` Ḯ latin capital letter i with diaeresis and acute
- [ ] `0x1E2F` ḯ latin small letter i with diaeresis and acute
- [ ] `0x1E36` Ḷ latin capital letter l with dot below
- [ ] `0x1E37` ḷ latin small letter l with dot below
- [ ] `0x1E3A` Ḻ latin capital letter l with line below
- [ ] `0x1E3B` ḻ latin small letter l with line below
- [ ] `0x1E42` Ṃ latin capital letter m with dot below
- [ ] `0x1E43` ṃ latin small letter m with dot below
- [ ] `0x1E44` Ṅ latin capital letter n with dot above
- [ ] `0x1E45` ṅ latin small letter n with dot above
- [ ] `0x1E46` Ṇ latin capital letter n with dot below
- [ ] `0x1E47` ṇ latin small letter n with dot below
- [ ] `0x1E48` Ṉ latin capital letter n with line below
- [ ] `0x1E49` ṉ latin small letter n with line below
- [ ] `0x1E4C` Ṍ latin capital letter o with tilde and acute
- [ ] `0x1E4D` ṍ latin small letter o with tilde and acute
- [ ] `0x1E4E` Ṏ latin capital letter o with tilde and diaeresis
- [ ] `0x1E4F` ṏ latin small letter o with tilde and diaeresis
- [ ] `0x1E50` Ṑ latin capital letter o with macron and grave
- [ ] `0x1E51` ṑ latin small letter o with macron and grave
- [ ] `0x1E52` Ṓ latin capital letter o with macron and acute
- [ ] `0x1E53` ṓ latin small letter o with macron and acute
- [ ] `0x1E5A` Ṛ latin capital letter r with dot below
- [ ] `0x1E5B` ṛ latin small letter r with dot below
- [ ] `0x1E5E` Ṟ latin capital letter r with line below
- [ ] `0x1E5F` ṟ latin small letter r with line below
- [ ] `0x1E60` Ṡ latin capital letter s with dot above
- [ ] `0x1E61` ṡ latin small letter s with dot above
- [ ] `0x1E62` Ṣ latin capital letter s with dot below
- [ ] `0x1E63` ṣ latin small letter s with dot below
- [ ] `0x1E64` Ṥ latin capital letter s with acute and dot above
- [ ] `0x1E65` ṥ latin small letter s with acute and dot above
- [ ] `0x1E66` Ṧ latin capital letter s with caron and dot above
- [ ] `0x1E67` ṧ latin small letter s with caron and dot above
- [ ] `0x1E68` Ṩ latin capital letter s with dot below and dot above
- [ ] `0x1E69` ṩ latin small letter s with dot below and dot above
- [ ] `0x1E6C` Ṭ latin capital letter t with dot below
- [ ] `0x1E6D` ṭ latin small letter t with dot below
- [ ] `0x1E6E` Ṯ latin capital letter t with line below
- [ ] `0x1E6F` ṯ latin small letter t with line below
- [ ] `0x1E78` Ṹ latin capital letter u with tilde and acute
- [ ] `0x1E79` ṹ latin small letter u with tilde and acute
- [ ] `0x1E7A` Ṻ latin capital letter u with macron and diaeresis
- [ ] `0x1E7B` ṻ latin small letter u with macron and diaeresis
- [ ] `0x1E8E` Ẏ latin capital letter y with dot above
- [ ] `0x1E8F` ẏ latin small letter y with dot above
- [ ] `0x1E92` Ẓ latin capital letter z with dot below
- [ ] `0x1E93` ẓ latin small letter z with dot below
- [ ] `0x1E97` ẗ latin small letter t with diaeresis
- [x] `0x2010` ‐ hyphen
- [x] `0x2012` ‒ figure dash
- [x] `0x2015` ― horizontal bar
- [x] `0x2205` ∅ empty set

-----------------------------------------------
Unicodes created beyond GF Latin glyph sets:
✅ `0x0132` Ĳ latin capital ligature ij
✅ `0x0133` ĳ latin small ligature ij
✅ `0x0149` ŉ latin small letter n preceded by apostrophe
✅ `0x019D` Ɲ latin capital letter n with left hook
✅ `0x0315` ̕ combining comma above right
✅ `0x0E3F` ฿ thai currency symbol baht
✅ `0x203E` ‾ overline
✅ `0x20A8` ₨ rupee sign
✅ `0x20AA` ₪ new sheqel sign
✅ `0x20B4` ₴ hryvnia sign
✅ `0x20B8` ₸ tenge sign
✅ `0x20BF` ₿ bitcoin sign
✅ `0x2194` ↔ left right arrow
✅ `0x2195` ↕ up down arrow
✅ `0x2196` ↖ north west arrow
✅ `0x2197` ↗ north east arrow
✅ `0x2198` ↘ south east arrow
✅ `0x2199` ↙ south west arrow
✅ `0x2261` ≡ identical to
✅ `0x2440` ⑀ ocr hook
✅ `0x2661` ♡ white heart suit
✅ `0x2665` ♥ black heart suit
✅ `0xE132`  (no unicode name)
✅ `0xE133`  (no unicode name)
✅ `0xF8FF`  (no unicode name)
✅ `0xFB00` ﬀ latin small ligature ff
✅ `0xFB03` ﬃ latin small ligature ffi
✅ `0xFB04` ﬄ latin small ligature ffl

</details>

<details><summary><b>Unicodes missing (or not yet compatible for built font), as of Nov 12</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/45946693/68634054-29d1c000-04c2-11ea-94cc-0d0855bd8669.png)

- [x] `0x00A0`   no-break space
- [x] `0x00AD` ­ soft hyphen
- [x] `0x02BC` ʼ modifier letter apostrophe
- [x] `0x0324` ̤ combining diaeresis below
- [x] `0x0335` ̵ combining short stroke overlay
- [x] `0x2052` ⁒ commercial minus sign (missing from weight A slanted masters)
- [x] `0x2219` ∙ bullet operator (missing from weight A slanted masters)
- [x] `0x2010` ‐ hyphen (I think this can just use the `002d` hyphen as a component)
- [x] `0x2012` ‒ figure dash (missing from weight A slanted masters)
- [x] `0x2015` ― horizontal bar (missing from weight A slanted masters)
- [x] `0x2205` ∅ empty set (missing from weight A slanted masters)

</details>

## Unicodes missing (or not yet compatible for built font), as of Nov 12 (3 pm)

Almost there! I probably just have to figure out if these are getting cut unintentionally in my build process:

- [ ] `0x00A0`   no-break space
- [ ] `0x00AD` ­ soft hyphen
- [ ] `0x02BC` ʼ modifier letter apostrophe

![image](https://user-images.githubusercontent.com/45946693/68705967-01e36a80-055d-11ea-99ae-9fee8ed09d48.png)

**Comment by LisaHuang2017** [comment]
For /indianrupee and /turkishlira, once the right unicode was added, their names in RF changed (respectively named /rupeeindian and /liraTurkish).
For hyphen (uni2010) and bullet operator (uni2219) appear to not have their name in RF, and kept their unicode names.

**Comment by arrowtype** [comment]
Hey @LisaHuang2017, thanks for making some good progress on this!

I've rebuilt the font and updated the above comment with the latest status.

Of note, `∅ empty set` is really close, but missing from two of the sources.

**Comment by arrowtype** [comment]
Reminder to self: once this issue is closed, do https://github.com/arrowtype/recursive/issues/230

**Comment by arrowtype** [comment]
As of Nov 29 (6f5cbb26b7), the variable font is building with no missing unicodes, as checked by my python script.

```
Unicodes missing:

-----------------------------------------------
Unicodes created beyond GF Latin glyph sets:
✅ `0x0132` Ĳ latin capital ligature ij
✅ `0x0133` ĳ latin small ligature ij
✅ `0x0149` ŉ latin small letter n preceded by apostrophe
✅ `0x019D` Ɲ latin capital letter n with left hook
✅ `0x0272` ɲ latin small letter n with left hook
✅ `0x0315` ̕ combining comma above right
✅ `0x0E3F` ฿ thai currency symbol baht
✅ `0x203E` ‾ overline
✅ `0x20A8` ₨ rupee sign
✅ `0x20AA` ₪ new sheqel sign
✅ `0x20B4` ₴ hryvnia sign
✅ `0x20B8` ₸ tenge sign
✅ `0x20BF` ₿ bitcoin sign
✅ `0x2194` ↔ left right arrow
✅ `0x2195` ↕ up down arrow
✅ `0x2196` ↖ north west arrow
✅ `0x2197` ↗ north east arrow
✅ `0x2198` ↘ south east arrow
✅ `0x2199` ↙ south west arrow
✅ `0x2261` ≡ identical to
✅ `0x2661` ♡ white heart suit
✅ `0x2665` ♥ black heart suit
✅ `0xE0A0`  (no unicode name)
✅ `0xE132`  (no unicode name)
✅ `0xE133`  (no unicode name)
✅ `0xF8FF`  (no unicode name)
✅ `0xFB00` ﬀ latin small ligature ff
✅ `0xFB03` ﬃ latin small ligature ffi
✅ `0xFB04` ﬄ latin small ligature ffl

```
