### ISSUE TITLE
Static .otf Font Files - 'Not a valid font file.' on Windows [Beta 1.022]

### ISSUE THREAD

**Issue by bluesatin** [arrowtype/recursive#225]
I'm trying to install the static font files [Beta 1.022] onto my Windows machine and they're failing to be viewed or installed. It's failing with the only error being that the .otf file 'is not a valid font file'.

The singular .ttf version of the font does install, so I don't think it's some of the issues people mention with permissions etc. that's localised to my machine.

With a quick search people have mentioned issues with names being too long, something about 29 characters being a limit in certain naming slots. Perhaps that's causing the issue?

**Comment by arrowtype** [comment]
Hey @bluesatin, thanks so much for filing an issue and suggesting a fix!

Mastering for static files (OTF & TTF) is in progress, and name length is one thing that we are specifically being careful of. That probably is what is causing the problem on your end.

I'll update this when we have made a new release!

**Comment by bluesatin** [comment]
Just for ease of reference, this was the post I saw mentioning issues with Windows and the character limit with certain naming fields:
https://forum.glyphsapp.com/t/overly-strict-font-name-max-length-recommendation-in-naming-tutorial/10164

Which also references this thread:
https://github.com/googlefonts/fontbakery/issues/2179

Best of luck trying to fill those naming fields with something that doesn't look like it's actually Klingon, Welsh or the true name of an ancient-one.

**Comment by arrowtype** [comment]
:) They'll look a little funny, but the abbreviated postscript names are documented here:

https://github.com/arrowtype/recursive/blob/master/mastering/data/instance_names.csv

**Comment by arrowtype** [comment]
Issue #223 gave some detail that seems related:

> Under Windows 10 Pro, most applications cannot locate or find the fonts specified. If they do, the full name isn't found or selected properly. I had to double click the font, find the official name, with version in it, and type it in. For example:
> 
> Recursive Mono Static Beta 1.020 Casual Medium

**Comment by arrowtype** [comment]
Hi @bluesatin, can you please try the OTFs in v1.037, and let me know if the issue still exists?

https://github.com/arrowtype/recursive/tree/1375e40a15a24292d9545abd5f0626b3c7634e3b/fonts_1.037

**Comment by bluesatin** [comment]
The static OTFs from v1.037 now appear to be recognised as a proper font, install properly (which was my issue) and are recognised and appear to work with 4 different applications from a quick test.

I can't speak for whether every application does pick them up appropriately in regards to the other issue, but they were picked up correctly by Photoshop, Word, Notepad++ and NexusFont for me now that Windows recognises them and will let me install them.

**Comment by benkiel** [comment]
@arrowtype I think this can be closed?

**Comment by arrowtype** [comment]
Thanks, @ben – looks like it!
