### ISSUE TITLE
Weight and width corrections on Casual masters

### ISSUE THREAD

**Issue by LisaHuang2017** [arrowtype/recursive#242]
For some letters in Sans (and Mono) Casual C masters, they seem either slightly too dark, too light or too wide compared to the general color.

From this PDF we can see the most obvious ones: https://github.com/arrowtype/recursive/blob/master/src/proofs/working-proofs/102019-kerning/Recursive-kerning-20191115_corrections.pdf

Casual C
- [ ] /U and /S too light
- [ ] /O, /R and /B too dark

Casual A
- [ ] /X too wide

**Comment by arrowtype** [comment]
Hey Lisa, thanks for making these observations! I agree, for the most part.

> /U and /S too light

- /U could definitely get a bit thicker
- /S could get thicker at bottom stroke, and the top stroke could come a bit further down. I do want to keep the contrast for the thin spine 
- I think the /X is also a bit light, but if we make it slightly less wide through the masters, it might be corrected. And actually, it's 650 units in the Sans, so ... I think we should just revert it back to being something copied from the Mono masters!

> /O, /R and /B too dark

True! I'd say that each could gain a bit of contrast. 
- The /O could have sharper counter corners
- The /R could get a thinner middle bar, and maybe lose a bit of weight in the bowl
- The /B could get a thinner bottom bar, and maybe lose a bit of weight in the bowls

**Comment by LisaHuang2017** [comment]
Done for Casual C, will make a check round on all the other masters once the other more urgent issues will be done :)

**Comment by LisaHuang2017** [comment]
To avoid doubled informations, the latest updates on the weight and width can also be seen on the proof pdf of this issue : https://github.com/arrowtype/recursive/issues/91
