### ISSUE TITLE
flipped contours in /numbersign_numbersign.code

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#244]
![image](https://user-images.githubusercontent.com/45946693/68970775-11a9bb80-07b6-11ea-8528-b1eb6a926508.png)

**Comment by LisaHuang2017** [comment]
Mono masters:
<img width="669" alt="Capture d’écran 2020-01-10 à 15 55 32" src="https://user-images.githubusercontent.com/32390132/72162181-bf55d700-33c1-11ea-85df-782a7cd6ae6f.png">

Sans masters:
<img width="692" alt="Capture d’écran 2020-01-10 à 15 57 30" src="https://user-images.githubusercontent.com/32390132/72162260-eca28500-33c1-11ea-9ec3-69d46bbe3e4f.png">

**Comment by LisaHuang2017** [comment]
This issue is solved and can be closed.
