### ISSUE TITLE
resolve `//` ligature – make good for both JS comments and for URLS (https://www...)

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#253]
Looks good for comments, but awkward for URLs, which are probably even more common:

![image](https://user-images.githubusercontent.com/45946693/69164913-c695ee00-0abe-11ea-9f42-b6f27f2e3292.png)

Two possibilities to solve this:

1. create `colon_slash_slash.code` glyph which has better spacing for URLs
2. make `slash_slash.code` less tightly-spaced

**Comment by LisaHuang2017** [comment]
Casual masters
<img width="839" alt="Capture d’écran 2020-01-10 à 15 46 38" src="https://user-images.githubusercontent.com/32390132/72161471-7a7d7080-33c0-11ea-8fd8-e0c7689ee43a.png">

Linear masters
<img width="829" alt="Capture d’écran 2020-01-10 à 15 46 43" src="https://user-images.githubusercontent.com/32390132/72161489-810be800-33c0-11ea-8eb5-bf148526604c.png">

**Comment by LisaHuang2017** [comment]
Fixed in this commit: https://github.com/arrowtype/recursive/commit/3bbca5cb2e9c35994ac41b4b7cd482cef51b1971
