### ISSUE TITLE
Unable to set as a font in VSCode on Windows 10

### ISSUE THREAD

**Issue by iansan5653** [arrowtype/recursive#255]
I am unable to set this as a font in VSCode - I'm not sure what font name to use. I installed the latest static versions (as VSCode doesn't have support for variable fonts yet).

I've tried all of the following:
* `RecursiveMonoB_020-LnrRg`
* `RecursiveMonoB_120-LnrRg`
* `RecursiveMonoB_1020-LnrRg`
* `Recursive Mono`
* `Recursive Mono Static Beta 1.02`
* `Recursive Mono Static Beta 1.020`
* `Recursive Mono Static Beta 1.02 Linear Regular`
* `Recursive`

None of those work though. The font shows up in my text editors as `Recursive Mono Static Beta 1.02` and Windows shows all the variations:
![image](https://user-images.githubusercontent.com/2294248/69197664-1648d980-0b00-11ea-9535-782461e89327.png)

**Comment by arrowtype** [comment]
Ohh shoot, thank you for trying so many ways to get that working! I'm sorry it hasn't worked, so far.

I did some experiments, and I think I've found a naming scheme that will work in Windows.

![image](https://user-images.githubusercontent.com/45946693/69209129-1b1f8480-0b24-11ea-8b39-613b4af00cbb.png)

However, to make this properly work, I'll need to update my static build scripts. I'll try to do this as soon as possible (probably in the next day or two).

**Comment by arrowtype** [comment]
Hey, can you please also try this again with the latest release?

https://github.com/arrowtype/recursive/releases/tag/1.026

For me, it works in Windows 10 VS Code to specify the font like this:

`Recursive Mono Lnr b026st`
`Recursive Mono Csl b026st`

**Comment by iansan5653** [comment]
Thanks, I was able to get it to work using those.

To enable ligatures, I needed to set `editor.fontLigatures` to `"'dlig'"` (note the two sets of quotes since VSCode takes a comma separated list of  strings rather than an array of strings).

Also VSCode wouldn't allow me to use the bold mono linear as a terminal font - regular and medium and light work, but bold raises an error saying it's not monospace. Not sure if that's an issue with the font or with VSCode.

**Comment by arrowtype** [comment]
Thanks for confirming! I'll close this for now.

The inability to set a bold font in the terminal seems like a VS Code issue to me. As far as I know, the metrics are exactly the same across all of the Recursive mono fonts. Certainly, Light–Medium all include glyphs that are multiple-units wide (code ligatures like ===, etc). Beyond that, I don't see why any font can't be used on the terminal...
