### ISSUE TITLE
All font variations are casual on Windows

### ISSUE THREAD

**Issue by iansan5653** [arrowtype/recursive#256]
I just installed the font on Windows and every variation of the font, whether labeled as Linear or Casual, appears as Casual:

![image](https://user-images.githubusercontent.com/2294248/69197664-1648d980-0b00-11ea-9535-782461e89327.png)

**Comment by arrowtype** [comment]
Ouch, that’s not great! Just to track this, what version of Windows are you using?

**Comment by iansan5653** [comment]
I'm using Windows 10 Pro 1909.

**Comment by arrowtype** [comment]
Great, thank you for that detail! Hopefully, when we add a proper STAT table to the VF, it will fix this issue.

**Comment by arrowtype** [comment]
Hi @iansan5653 , can you please try with the latest release?

https://github.com/arrowtype/recursive/releases/tag/1.026

**Comment by iansan5653** [comment]
Looks good, thanks!
