### ISSUE TITLE
The 'estimated' symbol (℮) is missing

### ISSUE THREAD

**Issue by iansan5653** [arrowtype/recursive#258]
U+212e is listed on the website as a character but is not present in the font:
![image](https://user-images.githubusercontent.com/2294248/69198570-1f877580-0b03-11ea-8c49-8067c332fcff.png)

**Comment by arrowtype** [comment]
Thanks, Ian! That glyph is technically supposed to have a prescribed shape rather than fit into a font’s style. However, it is confusing to include on the site, for that reason (it does look broken, even though it’s not). I’ll remove that square. :)
