### ISSUE TITLE
/ellipses should be wider in Sans styles

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#260]
Currently, the `…` is just copied from mono to sans. However, this makes it unnaturally narrow. It should be less wide than three /period glyphs, but not as narrow as it currently is.

![F702BE97-E1CC-413F-B748-4F94359B015E](https://user-images.githubusercontent.com/45946693/69282304-fc6acd80-0bb7-11ea-94a8-69af7355fb1c.jpeg)

**Comment by LisaHuang2017** [comment]
Ellipses weights and widths are now balanced with each (Sans) masters:
<img width="806" alt="Capture d’écran 2020-01-10 à 17 54 30" src="https://user-images.githubusercontent.com/32390132/72171051-5cb90700-33d2-11ea-9ade-36287bc83dd8.png">
