### ISSUE TITLE
Are ligatures supported in recursive-static_fonts-b020.zip?

### ISSUE THREAD

**Issue by jonesnc** [arrowtype/recursive#268]
I have installed the `recursive-MONO_CASL_wght_slnt_ital--2019_11_05-00_13.ttf` file in recursive-static_fonts-b020.zip found on the Releases page, and in VS Code I'm using this as my `Editor: Font Family`:

`RecursiveMonoB_020-LnrMd`

Ligatures are not rendering (`->` in Python, `=>` in JavaScript). I have `"editor.fontLigatures": true,` in my `settings.json`.

Should I expect ligatures to be working in this release? Am I configuring VS Code incorrectly to use ligatures?

**Comment by arrowtype** [comment]
Hey @jonesnc, thanks for giving it a try, and thanks for filling an issue to ask! I am working on some improved statics with many more opentype features (along with documentation of it), and will try to put out a new release by the end of today. So, keep an eye out!

That said, I believe you can get code ligatures with beta 020, but they are behind a slightly different OpenType feature flag than simpler code ligatures fonts (discretionary ligatures, so they’re not active by default). Here’s how to activate features in three common editors:

**VS Code**

In VS Code, you can activate OpenType features by searching for `fontLigatures`, then editing this in settings.json like this:

```
    "editor.fontLigatures": "'ss01', 'ss05', 'dlig'"
```

(In beta025, the above would give you a simplied `6` & `9`, a single-story `a`, and activate code ligatures.)

**Atom**

Go to `Atom` -> `Stylesheet` and add in the following:

```
atom-text-editor {
  font-family: 'RecursiveMonoB_023-CslRg';
  font-feature-settings: "ss01", "ss05", "dlig";
}
```

# Sublime Text

Go to `Sublime Text` -> `Preferences` -> `Settings` and add:

```json
"font_options": ["ss01", "ss05", "dlig"]
```

**Comment by arrowtype** [comment]
Note: I’m away from my computer so it’s hard to verify, but I think that beta 020 has `dlig` but not stylistic sets. So, you only need to include that feature in settings.

**Comment by jonesnc** [comment]
Hi @arrowtype! Thanks for promptly responding. I was also away from the computer, so I haven't been able to try your suggestion until now.

I just wanted to report that your suggestions for VS Code worked!

Thank you!

**Comment by arrowtype** [comment]
That's great news! Thanks for reporting and for updating. Keep your eye out for more ligatures in updated versions, soon!
