### ISSUE TITLE
Mono + Casual combo causes Weight change

### ISSUE THREAD

**Issue by robertjanes** [arrowtype/recursive#269]
Hi,

I'm using Recursive for programming (looks great!), and have setup my editor so that my attribute names are casual and italic. However I noticed that the weight of the casual was heavier, and after looking on the microsite it appears to be a problem with the `MONO` and `CASL`.

![image](https://user-images.githubusercontent.com/18029187/69708452-f0bd6080-10fb-11ea-9cc0-a75e845c0c4a.png)

![image](https://user-images.githubusercontent.com/18029187/69708088-46ddd400-10fb-11ea-8b8b-ff7b8bc757d4.png)
![image](https://user-images.githubusercontent.com/18029187/69708110-51986900-10fb-11ea-83ff-52a0e554cc2c.png)

**Comment by arrowtype** [comment]
First of all, thanks for trying Recursive. Awesome mixing of styles!

This seems to be an issue with text rendering on macOS. What version of OS are you on?

https://github.com/fonttools/fonttools/issues/1756#issuecomment-548807603

Potentially, I could do something in my build to back around the issue. I’ll think about what that might require...

**Comment by giovanicascaes** [comment]
Hi!

I'm getting something similar on macOS. The italics seems not to be respected on code editors. Words that should be italics are rendered regular. Is it OS related too?

**Comment by arrowtype** [comment]
@giovanicascaes That is a separate issue (https://github.com/arrowtype/recursive/issues/153). It is OS correlated (it does work in VS Code on Windows 10, but not currently in VS Code on macOS. It does work on PhpStorm, interestingly, on macOS).

**Comment by giovanicascaes** [comment]
Oh, ok. Thank you very much.

**Comment by arrowtype** [comment]
This appears to have been fixed in recent versions of macOS! 🎉
