### ISSUE TITLE
Code ligature `&&` might be improved with design adjustments

### ISSUE THREAD

**Issue by enriqueMartinezInter** [arrowtype/recursive#276]
When using && and ligatures the second characters looks broken.
Keep up the great work!

**Comment by arrowtype** [comment]
This might be working as intended – I think code ligatures are most useful if they stand out a bit from regular glyphs. Can you post a screenshot of what you think is the issue?

**Comment by enriqueMartinezInter** [comment]
Sure, first image has no ligatures on , second one does

![ampnolig](https://user-images.githubusercontent.com/12499680/71147515-a6a53780-21ee-11ea-9d08-60510eb4f156.JPG)

![amplig](https://user-images.githubusercontent.com/12499680/71147588-d2c0b880-21ee-11ea-8e78-b92d1c9d92b3.JPG)

**Comment by arrowtype** [comment]
Cool, thanks!

Yup, I think part of the value of code ligatures is they represent meaningful syntax items as “single units,” and visibly different from normal text – it’s like a form of syntax highlighting. So, this && is drawn as if someone were quickly writing it as a single symbol, a bit quickly by hand.

Possibly, though, it could be improved a bit if the bottom part were connected... I’ll sketch on that when I have some time. :)

**Comment by enriqueMartinezInter** [comment]
Perhaps make it an optional feature?
