### ISSUE TITLE
Code ligature for != looks broken in VS Code themes with italics support

### ISSUE THREAD

**Issue by krish-r** [arrowtype/recursive#277]
First of all, Awesome font. Thanks!

Code ligature for != looks broken in VS Code themes with italics support. 
Same ligature looks fine without italics. 
(Also, !== also looks fine with/without italics.)

Font version: 1.029
VS Code version: 1.41.1
VS Code Theme: Cobalt2/Night Owl

#### Steps to Reproduce:
* Install Recursive Mono Csl/Lnr b029st Regular & Italics variant
* Install/Set a VS Code Theme which supports Italics (For ex. Night Owl Italics)
* Type "!=" (without quotes) in file formats with italics support (For ex. comments in .java or .py files.)

![image](https://user-images.githubusercontent.com/54745129/71310172-1279e100-2437-11ea-8445-15d9884ed584.png)

**Comment by arrowtype** [comment]
Hey @krish-r, thanks so much for flagging this issue!

I’m guessing you’re using Windows 10, correct? As far as I’m aware, the italic style-linking isn’t working just yet on macOS – but we’re working on that.

Looks like a couple of contours have reversed directions between the weights of the slanted styles. This will be a quick fix, and I'll try to post an update in the next couple of days. :)

![Kapture 2019-12-21 at 12 11 29](https://user-images.githubusercontent.com/45946693/71311156-0e27d680-23eb-11ea-9ae2-517da172ad5a.gif)

**Comment by krish-r** [comment]
yes, Windows 10. Thanks for the quick response. :)

**Comment by arrowtype** [comment]
Hey @krish-r, could you please give this another try with the latest release (beta 1.030)?

**Comment by krish-r** [comment]
Thanks @arrowtype, it looks good now. 

![image](https://user-images.githubusercontent.com/54745129/71318023-fe72c580-24b0-11ea-848a-0575562cdc82.png)

**Comment by arrowtype** [comment]
Awesome; thanks for confirming!
