### ISSUE TITLE
Code ligatures not currently working in Static fonts, with new build scripts

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#287]
As of https://github.com/arrowtype/recursive/releases/tag/1.030, code ligatures were working in static & variable fonts, via the `dlig` feature:

![image](https://user-images.githubusercontent.com/45946693/71934886-67c22c00-3173-11ea-8187-c61ff55fc4ce.png)
[image source](https://github.com/arrowtype/recursive/blob/e3e189782d252bbb80a2ef565f3e4cbd11411c8a/docs/001-opentype_features/recursive-b027-ot_features.png)

With the new build scripts, code ligatures aren't currently working in Illustrator Sketch, Figma, or Pages (macOS Catalina 10.15.2). I'm not yet sure why this might be – these features show up in feature lists, but can't be activated. Features besides ligatures are working as expected.

![image](https://user-images.githubusercontent.com/45946693/71934857-56791f80-3173-11ea-93c7-75fd8a75727b.png)

However, the variable font _does_ seem to have `dlig` working, when tested.

**Comment by benkiel** [comment]
FWIW, the fea code is the same here, assuming it hasn't changed in the repository between 1.3 and now. My gut feeling here is that there is some funny business in the feature code itself that `fontmake` papered over (much like it papered over the stylistic set names using non-escaped non-ascii glyphs).

**Comment by arrowtype** [comment]
Luckily, this is once again working as of b733ba362d08ff47efe9c742bd0e1ad5e169d927. Possibly, it was another issue from AFDKO?

**Comment by benkiel** [comment]
Very likely.
