### ISSUE TITLE
Similar font names between static and var fonts lead to confusing font menu UX – add suffix to static names

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#288]
Currently, if I have the variable font and static fonts all installed at once, when I try to select the variable font in a menu, the menu changes in unpredictable ways, probably due to shared names.

In Pages, it's possible to have two font menu items appear as "selected."

![image](https://user-images.githubusercontent.com/45946693/71936140-9b528580-3176-11ea-90a2-ec9adfb44201.png)

In Sketch, it's even more confusing: when I try to select a static font family, it will snap back to the variable font. I think this was happening in the reverse direction when I installed the fonts in the opposite order (i.e. selecting the variable font snapped to a selection of a static menu item).

![Kapture 2020-01-07 at 17 54 34](https://user-images.githubusercontent.com/45946693/71936218-cfc64180-3176-11ea-8143-412537e67cf9.gif)

My guess is, we should add a suffix into static font names to ensure that they are unambiguously different than the variable font name (which should be the base font). However, there may be another way to handle this that I don't know of.

Dave Crossland has made it clear that Google Fonts should make the variable versions the "canonical" versions of fonts, and mark static fonts differently. That is, instead of appending "VF" to variable font names, we should append "Static" or "St" to static font names.

**Comment by benkiel** [comment]
Yes, 100% possible to do. It's going to make the shortened names even weirder, but that's all one can do.

A side issue to this is the need to change the naming in the source UFOs for the variable fonts, I'm finding that some font menus will show them. I'll open an issue for that.

**Comment by benkiel** [comment]
Looking at this again, I think that the fix may actually be in changing the Postscript names that are in the variable font, will investigate

**Comment by arrowtype** [comment]
Posting this here from our conversation offline, but Dave makes the point that static/variable font installations might be a bit like otf/ttf installations – something the user should manage:

https://github.com/googlefonts/fontbakery/issues/2412

...then again, I've never as a user experienced any noticeable difference when using finished OTF vs TTF fonts, whereas there are quite a few differences in using static vs variable fonts – both have pros and cons, especially as software is still refining support for variable TTFs (e.g. Adobe rendering of Recursive variable has some major issues).

But, I think that probably the solution of having a variable font with the family name `Recursive`, then statics with split names like `Recursive Sans Casual` and `Recursive Mono Linear`, etc, is probably good. We should also update the postscript names to be sure that they can be separately activated. 

Potentially, static file names could be specified as static? E.g. `RecursiveMonoLinear-BoldItalic.static.otf`. The specific stylename will already cue advanced users that it's a single static instance, but maybe the extra bit specificity could help make things more obvious...

**Comment by arrowtype** [comment]
THOUGH, one potential problem is that early on, the Google Fonts frontend will only support weight-axis fonts (plus maybe italics?). So, it is likely that instead of a single Recursive listing, there will be one of two outcomes:

1. A single listing for `Recursive Sans Linear`, which will eventually evolve into the full `Recursive`
2. Four listings: `Recursive Sans Linear`, `Recursive Sans Casual`, `Recursive Mono Linear`, `Recursive Mono Casual`, which will eventually be replaced by a single listing of the full `Recursive`

In either case, the font will be available as a split VF through an official channel. My question is whether the "Download" from Google Fonts will be for the full VF, or for split VFs. If there _are_ split VFs available for download along with static fonts, then I think we are back to needing suffixes in static names. I suspect that many users will just install all the fonts they download from Google Fonts, rather than trying to carefully manage static vs variable installations.

**Comment by arrowtype** [comment]
**As to what Google Fonts will serve initially,** 

It sounds like scenario 1 is closest, because Eng doesn't want to have separate sub-families listings to collapse later. However, the Recursive specimen page will point to [a configuration page on the minisite](https://github.com/arrowtype/recursive-minisite/issues/33), so people have access to all axes if they want it. 

**As to font naming and suffixes**

Adding suffixes to family names is the only way to predictably avoid causing chaos for users. The variable version is the official version, and statics are just offshoots for legacy software. So, adding `static` to the name is the only realistic way to avoid big issues. I do think that it’s best to include after the main family divisions, to avoid suggesting that “static” is a description of a subfamily, like `mono`/`sans` and `casual`/`linear`. 

So, these should be the primary fonts we build:
- Recursive
- Recursive Mono Casual Static
- Recursive Mono Linear Static
- Recursive Sans Casual Static
- Recursive Sans Linear Static

With the alternative – placing "Static" immediately after "Recursive," I worry it will sound like “Recursive Static” is somehow a separate sub-family of Recursive, rather than a different type of file.

And actually, I don’t really mind it when the style name is appended you that:

“Recursive Mono Casual Static ExtraBold” is a static instance of the ExtraBold style, within the collection/subfamily of “Recursive Mono Casual.” So, I think that “static” is most natural to place between them, all things considered.


If I provide a way to download custom, split VFs or static instances in the future, that should append a suffix to these custom fonts.
