### ISSUE TITLE
Change style names in source UFOs

### ISSUE THREAD

**Issue by benkiel** [arrowtype/recursive#289]
The development names are getting stuck into the name table of the font, so the font menu gets populated by those names occasionally.

**Comment by arrowtype** [comment]
How would you recommend changing style names? Currently, naming is like this:

```
family: ​ Recursive 
 style:  Mono Casual B Slanted
family:  Recursive 
 style:  Sans Linear A
# (etc)
```

Should the family name stay as `Recursive`, and have style names become like the following?

```
family: ​ Recursive 
 style:  Mono Casual ExtraBold Italic
family:  Recursive 
 style:  Sans Linear Light
# (etc)
```

OR, should the system only have weight + italic names in the `styleName`, for a system like this?

```
family: ​ Recursive Mono Casual
 style:  ExtraBold Italic
family:  Recursive Sans Linear
 style:  Light
# (etc)
```

The main place I am currently seeing the issue as you describe it is in the full variable font. So, I will try the first approach today (keeping the family name as `Recursive`), and I can update later if needed.

![image](https://user-images.githubusercontent.com/45946693/72294981-a731c200-3624-11ea-9476-acd9dfa8879d.png)

**Comment by arrowtype** [comment]
I've tested both updates in this PR: https://github.com/arrowtype/recursive/pull/294

But both approached have a similar problem: the style name of the base master populates the font style menu excessively, whether it is `Sans Linear A`, `Sans Linear Light`, or just `Light`.

**Comment by benkiel** [comment]
I'm digging into this, but my current operating assumption is that the ufo that is the default needs the name that the instance has, and that there should not be that instance in the list.

**Comment by benkiel** [comment]
Looking at this further, I think it actually is a change in the designspace file.
