### ISSUE TITLE
Can't set as fonts in VSCode after updating to 1.030 from 1.027

### ISSUE THREAD

**Issue by iansan5653** [arrowtype/recursive#295]
In 1.027, I was using this string to set the fonts in VSCode on Windows 10: `Recursive Mono Lnr b027st Regular`. Now, attempting to do the same for 030 (using `Recursive Mono Lnr b030st Regular` results in the editor failing to find the font. If I leave off the `Regular`, same thing happens.

**Comment by iansan5653** [comment]
Never mind, just needed to reload the window.

**Comment by arrowtype** [comment]
Phew, glad the reload worked! Thanks for the update. 

We are actively working on production-ready versions, so this will be simpler, soon. :)
