### ISSUE TITLE
Recursive Mono issue with phpstorm

### ISSUE THREAD

**Issue by hossein-nas** [arrowtype/recursive#298]
It is not possible to change Recursive Mono Linear Style in Phpstorm.
By default it's uses Bold Italic style of font and can't change font style.

**Comment by arrowtype** [comment]
Hi Hossein, thanks for trying Recursive and for taking the time to file an issue!

I assume you are using the latest release (v1.030), correct? What OS are you on?

If so, please try some of the newer betas (v1.031), available here:

https://github.com/arrowtype/recursive/tree/e5dbba46b46fc3c9dfa902db863beb2a632446ed/fonts_1.031/Static_TTF

(You may want to uninstall the existing fonts before trying this. Also, please make sure to restart the app between changing fonts, to give it a chance to reload your system's fonts).

Sidenote: this is my first time trying Phpstorm. I love that the whole UI can get a custom font! Wish VSCode allowed that. :)

**Comment by hossein-nas** [comment]
@arrowtype awesome :). it works just fine 
thanks.
