### ISSUE TITLE
Is the middle blue zone for /f.italic? If so, this needs updating for newer design

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#299]
@benkiel is the blue zone in the middle of the x-height for the low crossbar of the f.italic? Today, I have adjusted the design of the f.italic for better spacing, and have lowered the crossbar somewhat. In this case, should I move the middle blue zone to match the top of the f.italic bar, or is is there for some other purpose?

![image](https://user-images.githubusercontent.com/45946693/72571709-53c2ac80-388e-11ea-9026-bb1d8f3de0f4.png)

**Comment by benkiel** [comment]
This is for the bottom of the numerators, it is an `otherBlue` (i.e., moving things up, not down). Not for the middle bar of the f.italic (it would need to have some sort of round that is at the same height).

**Comment by arrowtype** [comment]
Oh, that is very helpful to know. Thank you!
