### ISSUE TITLE
Is the /sterling a common-enough form, or would it be better with a flat bottom?

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#30]
I'm considering two different styls of `£` in the "strict" masters:
- one with a totally-flat bottom stroke
- one with a more-humanist bottom stroke

Is one better than the other?

![image](https://user-images.githubusercontent.com/7355414/59968826-6c443180-950e-11e9-8f94-69c7e6b65934.png)

---

![image](https://user-images.githubusercontent.com/7355414/59968976-29d02400-9511-11e9-8d6a-4c7a5a828341.png)

**Comment by arrowtype** [comment]
I ended up opting for a "humanist" connection in the casual styles, and a flat bottom in the Linear styles. This helps accentuate the expression on either end.

![Kapture 2019-09-17 at 10 16 52](https://user-images.githubusercontent.com/45946693/65049781-563ee500-d934-11e9-9c0c-da3c0263e478.gif)
