### ISSUE TITLE
Mastering: is there a simple way to prep *just* the variable font sources (and not prep statics)?

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#300]
I am trying to test a variable font build, so I've followed the readme instructions:

> `python build.py --files` is the first step. This will generate all the files needed for building the variable and static fonts.

`python build.py --files -v 1.034`

The preps UFOs for the variable font as I had hoped, but it _also_ preps all instance UFOs, which is overkill for my current objective. I see that `buildFiles()` function does have a `static` argument that can be set to false. Can this be cued from the command line, or would I have to modify the Python scripts to make this possible?

**Comment by benkiel** [comment]
That can be added easily to the script, yes

**Comment by arrowtype** [comment]
Okay, yeah that was super easy. :)

Added with ada5a0d104e9f15f2c831799213ef18763e0dfde
