### ISSUE TITLE
Emphasize waviness of Tilde character for improved legibility

### ISSUE THREAD

**Issue by krish-r** [arrowtype/recursive#301]
Hi, 

Just a query, is this how the tilde character supposed to look at font size 15 (VS Code)?

![image](https://user-images.githubusercontent.com/54745129/72639766-5f949880-398c-11ea-8963-07a5cf73a92e.png)

|     |     |
| --- | --- |
| OS | Windows 10 |
| VS Code version | 1.41.1 |
| Font version | 1.030 |
| Font Size | 15 |
| Font Style | Recursive Mono Csl b030st |

**Comment by arrowtype** [comment]
Hmm, mostly yes, but would you prefer a different rendering? I suspect it may be a bit flatter than might be useful...

**Comment by krish-r** [comment]
Well, I was able to recognise this in my code.
But, do you think making the character very slightly curvy (or taller) whilst still preserving recursive's characteristic could improve the readability.
Just my opinion, I'm no designer and I believe you know what looks best.

**Comment by arrowtype** [comment]
Thanks for raising the idea! It is a frequent character in code, and you're right that at small sizes it's not currently super distinct. I will probably change this at some point in the nearish future.

**Comment by joshtriplett** [comment]
@arrowtype Thank you!
