### ISSUE TITLE
font ligatures are not working on jetbrains IDEs

### ISSUE THREAD

**Issue by srisar** [arrowtype/recursive#304]
As you can see from the screenshot, I have enabled font ligature feature on, but it is not working for recursive font. Am I missing something or is it a bug?

![2020-01-22_190203](https://user-images.githubusercontent.com/16640541/72898239-b6fa8600-3d49-11ea-97cb-e1312f41fa73.png)

**Comment by arrowtype** [comment]
@srisar the code ligatures in Recursive are implemented with the "discretionary ligatures" OpenType feature, so the fonts can be used in more contexts than other code-ligature-specific fonts.

Does PhpStorm support arbitrary OpenType features? If so, you'll want to activate the `dlig` feature. If not, this is something you'd either have to request from JetBrains, or make a forked version of Recursive that uses the `calt` or `liga` features for Code Ligatures (similar to Fira Code, Hasklig, etc).
