### ISSUE TITLE
Duplicate style names in Sketch & Keynote menus – not necessarily an issue in Recursive

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#316]
**Problem description**

https://github.com/arrowtype/recursive/pull/315 seems to improve style naming on macOS, overall, but there are still some significant issues. However, it is unclear how much of this can actually be solved within Recursive, and how much is dependent on macOS & software.

In TextEdit, style names work (mostly) as I want them to, without duplicates:
![image](https://user-images.githubusercontent.com/45946693/74463843-74b3f880-4e60-11ea-8aad-fc122d718069.png)

However, this style list is notably missing "Italic" styles, and it suffers from being interpreted as an Italic-by-default font (due to the macOS issue https://github.com/arrowtype/recursive/issues/153).

In Keynote, the style menu is full of repeats:
![image](https://user-images.githubusercontent.com/45946693/74463703-38809800-4e60-11ea-885e-17a221f1ab57.png)

The style menu is similarly confusing in Sketch:

![image](https://user-images.githubusercontent.com/45946693/74463741-47ffe100-4e60-11ea-9410-1cb8f3236d55.png)

If the family name is changed to `RecVF` in light of https://github.com/arrowtype/recursive/issues/153, TextEdit no longer defaults to Italics, but now, the `i` italic button is no longer possible to use:

![image](https://user-images.githubusercontent.com/45946693/74464540-af6a6080-4e61-11ea-9cc2-f12aed681e8b.png)

In Sketch & Keynote, the style menus are still repetative:

![image](https://user-images.githubusercontent.com/45946693/74464641-e476b300-4e61-11ea-91cc-f9ee5c2a6876.png)

Notably, most of the styles labeled as `Sans Linear Light` are actually italic versions of styles that are correctly identified. Maaaybe this is an issue with the `STAT` table? However, all style names and postscript names are clearly defined in the `fvar` table, so it seems likely that it is a CoreText issue.

**Expected behavior**

I expect font style menus to have exactly 64 instances, with zero repeated names.

**To Reproduce**
1. Install one or the other of the fonts in the [current v1.038](https://github.com/arrowtype/recursive/tree/c3d7b14266dc3cd6c6b9bd16822ac87d02ece13c/fonts_1.038/Variable_TTF)
2. Try them in various macOS apps

**Environment (please complete the following information):**
- OS: macOS 10.15.3 (Catalina)

**Comment by arrowtype** [comment]
Some good news:

Font naming is working well in Windows 10, as far as I can tell.

![image](https://user-images.githubusercontent.com/45946693/74470354-610e8f00-4e6c-11ea-90cc-4b36d4ce7690.png)

![image](https://user-images.githubusercontent.com/45946693/74470327-548a3680-4e6c-11ea-8061-1c1ebea409a7.png)

Windows font menus seem to tend toward having constrained horizontal width, which makes it challenging to read full font names. However, there doesn't appear to be the same issue of repeating "Sans Linear Light."

**Comment by benkiel** [comment]
@arrowtype started to look into this. One thing, the PS name of the instances didn't change to RecVF, but that's still not doing the trick.

**Comment by onyekaa** [comment]
I'm getting this issue as well, but in Font Book on Mac. I'm not sure if it's related but I was trying to use test the font in a browser (I occasionally set custom fonts for sites using Stylus) and for some reason it was setting the Italic version.

![image](https://user-images.githubusercontent.com/3392638/79123696-9fec9280-7d92-11ea-86d9-db68aa384784.png)

**Comment by arrowtype** [comment]
Thanks for adding that detail, @onyekaa! Sketch uses the built-in font handling of macOS, so it makes sense that Font Book would have the same issues as Sketch & Keynote. It will take more investigation to solve this, but for now, the main workaround I'm using is to use static fonts for most desktop design, but the variable font on the web (or if I'm specifically trying to design with a variable font). I wish it were better, but the fact that it works better on Windows suggests that it will get better over time on macOS!

**Comment by arrowtype** [comment]
This will be fixed in macOS 11.

**Comment by arrowtype** [comment]
Actually, hmmmmm, I think I may have found a solution (even for macOS Catalina).

Removing nameID `17` makes the style menu work as expected. 

![image](https://user-images.githubusercontent.com/45946693/118177371-9a7fd280-b400-11eb-9e4f-0fb95790802b.png)

**Comment by arrowtype** [comment]
But, I'm unsure whether this is worth changing. Things are indeed working fine on macOS Big Sur, and name 17 is probably useful on pre-variable systems. So, I will probably leave it as is.

![image](https://user-images.githubusercontent.com/45946693/118208763-578c2200-b435-11eb-9d40-71f97f5c6b0b.jpeg)

**Comment by onyekaa** [comment]
For what it's worth, can confirm it works fine on Big Sur now.

**Comment by arrowtype** [comment]
Thank you! That's good to get the confirmation.

Yeah, I'm this case, it would cause more problems than it would solve to fix it for Catalina.
