### ISSUE TITLE
Some standard ligatures not available in Static Italic fonts, as desired (fi, fl, ffi, ffl)

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#320]
**Problem description**

These are availabe in the variable font, but not yet in the static italics.

**Expected behavior**
fi, fl, ffi, ffl should automatically be ligatures in the Italic static fonts. They are not.

**To Reproduce**

**Environment (please complete the following information):**
- OS: macOS 10.15.3
- Fonts: [v1.042](https://github.com/arrowtype/recursive/tree/7ff677f7b54f0a188e08abc18b5b2ece27556000/fonts/Recursive-Beta_1.042)

**Additional context**

Will document more as I dig into this.

**Comment by benkiel** [comment]
Two things happening:

1. The OT code for the statics needs to be re-written for the italic fonts, right now it's trying to do a sub of `f i.italic by fi;`, it needs to do just `f i by fi;`

2. The `fi` and `fl` glyphs aren't making it into the static fonts.

**Comment by arrowtype** [comment]
Ahh that makes sense. Thanks for clarifying! 

One way I would think to fix this: create a "static" specific stylistic set file, and reference that in `features-staic.fea`. Then, include that alternate features file here:

https://github.com/arrowtype/recursive/blob/f995862b46a8bed1d426375e8975cf388a0ae736/mastering/build_static.py#L269-L274

But, were you thinking of a cleaner/DRYer way of doing this?

**Comment by benkiel** [comment]
Yes, I think. Trying to sort through the best way. Would it be a correct assumption that only the italic fonts (Sans, Casual, Sans Mono, Casual Mono) get ligatures? Just checking my assumption here.

**Comment by benkiel** [comment]
@arrowtype Can you double check my assumption above?
