### ISSUE TITLE
Minor docs typos

### ISSUE THREAD

**Issue by francisbooth** [arrowtype/recursive#331]
The following image has the wrong example for `ss11`:
https://github.com/arrowtype/recursive/blob/master/docs/001-opentype_features/recursive-b027-ot_features.png
...i.e. the `1` isn't simplified in the second column.

Also there are two of the following typo _se**e**tings_ => _set**t**ings_ in the README:
https://github.com/arrowtype/recursive/blob/master/README.md

Loving the project. 😄🤘

**Comment by arrowtype** [comment]
Hey, thanks so much for letting me know! I'll go through and clean this up. :)

Glad you're enjoying the project. ♥️

**Comment by arrowtype** [comment]
OpenType features image corrected in 3e57d12f
