### ISSUE TITLE
Rec Mono for Code fonts should freeze in rvrn subsitutions

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#335]
**Problem description**

Currently, the released fonts in `Recursive_Code` fail to show the correct glyphs in some software, such as iTerm. It seems that they continue to use the `rvrn` feature to swap in some `MONO` glyphs, rather than just having those "baked in." That means that software that doesn't support the `rvrn` OpenType feature can display several characters in an unintended way.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/45946693/78460563-cf631700-768f-11ea-86c1-17d143e24f11.png">

**Expected behavior**

Shown is a screenshot of FontGoggles with `rvrn` off, then on. These fonts for code shouldn't require `rvrn` at all – they should act more like the static fonts, which have this feature baked in.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/45946693/78460608-3385db00-7690-11ea-8bb4-54339a3558b8.png">

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/45946693/78460611-397bbc00-7690-11ea-944b-e79d611ff6d2.png">

**Environment (please complete the following information):**
- OS: macOS Mojave, 10.14.5
- Fonts: https://github.com/arrowtype/recursive/releases/tag/1.047

**Additional context**
This is not a problem in other static fonts. :)

**Comment by a-mg** [comment]
I think I'm seeing this same behavior in MacVim -- I was trying to track down why it seemed like some stylistic sets were on by default only in that editor, but I think this issue would explain it. (This is with latest 1.047 code fonts):

<img width="1920" alt="Screen Shot 2020-04-30 at 15 45 41" src="https://user-images.githubusercontent.com/393834/80754511-26c49d80-8afd-11ea-9003-45ec4e25ffd5.png">

**Comment by arrowtype** [comment]
Hey Mattson, it's so cool to see that you're giving Recursive a try! Thanks for adding your experience here.

Indeed, in VIM, all of those glyphs are in their "default" forms, while they should be in their mono-specific substitutions. It's less noticeable, but the issue is also affecting the `g` (it has a flat top rather than an upwards "ear" as it should in the mono styles).

I'll be doing a round of fixes this weekend, specifically to make things work better on Windows, and this will be one of the two main issues I focus on. I'll update once I can solve it!

**Comment by a-mg** [comment]
Hey, no worries, I thought it might have an issue in the editor's text rendering but saw this issue and assumed it was connected. Yes, I guess my normal font size is too small to notice the `g`. :-) I'm enjoying Recursive a lot, and will look forward to the update!

**Comment by arrowtype** [comment]
Haha, yeah, the `g` is less noticeable and less of a problem. The `i` & `r` look pretty bad like this, though.

It's nice to know someone personally who is enjoying it. Extra motivation! Will work on this ASAP.

**Comment by arrowtype** [comment]
Okay, I think I’ve now solved this issue with [the fonts here](https://github.com/arrowtype/recursive/tree/e30961efe11fd4710b61d4352d1f346be361484f/fonts/rec_mono-for-code). Here’s a zip to make this simpler to download for now:

[rec_mono-for-code.zip](https://github.com/arrowtype/recursive/files/4583476/rec_mono-for-code.zip)

These seem to be correctly working in MacVim:

![image](https://user-images.githubusercontent.com/45946693/81113191-d16a0100-8eed-11ea-9d8e-4090891cfcb0.png)

And the stylistic sets still work in apps that support them, such as VS Code and Font Goggles (unfortunately, MacVim doesn’t seem to support OpenType features, before or after this change).

@a-mg if you get a chance, could you please test these new fonts, and let me know if they solve your issue? If so, we can close this issue.

**Comment by a-mg** [comment]
Hey Stephen, good timing, you updated this right before I opened GitHub.

Yes, I can confirm that these new fonts are working as expected. All four packages look right (though I'm typically using Linear now). I'm seeing the same result as you did in your test. Thanks for addressing!

I have an open issue on the MacVim project requesting implementation of OpenType features. :-) It's a bit of an old-school editor, so it doesn't always support things that VS Code takes for granted but it may get there.

**Comment by arrowtype** [comment]
Awesome, thanks for helping confirm that, @a-mg!

Working on making a new release, now.
