### ISSUE TITLE
Code fonts (Rec Mono series) have name/behavior conflicts on Windows

### ISSUE THREAD

**Issue by jdknezek** [arrowtype/recursive#336]
**Problem description**
There are several possibly-related issues with the Rec Mono (Code) series on Windows:

* Fonts have strange names like "Rec Mono Linear Mono Linear", "Rec Mono Duotone Mono Linear" / "Rec Mono Duotone Mono Casual"
* Possibly due to these strange names and overlaps, italics often don't work correctly
  * Rec Mono Casual sometimes has no italic styles
  * Rec Mono Linear & SemiCasual sometimes has no non-italic styles
  * Rec Mono Duotone sometimes doesn't correctly switch between linear/casual based on italic (e.g. VS Code)

**Expected behavior**
I would expect to specify "Rec Mono Linear" or "Rec Mono Casual" for regular styles, with italics & weights being properly applied. I would expect "Rec Mono Duotone" to use casual styles when displayed in an italic style.

**Screenshots**
Rec Mono Linear properties (duplicate names, no regular style):
![image](https://user-images.githubusercontent.com/1338/78466107-11598080-76c3-11ea-970d-4c83f782d6ac.png)

Rec Mono Casual properties (duplicate names, no italic style):
![image](https://user-images.githubusercontent.com/1338/78466112-1d454280-76c3-11ea-9744-506c0594a358.png)

Rec Mono SemiCasual properties (no regular style):
![image](https://user-images.githubusercontent.com/1338/78466115-29310480-76c3-11ea-9977-f5b33444a701.png)

Rec Mono Duotone properties:
![image](https://user-images.githubusercontent.com/1338/78466117-2fbf7c00-76c3-11ea-9ae1-4ca995dc3ea7.png)

VS Code not recognizing e.g. "Rec Mono Duotone":
![image](https://user-images.githubusercontent.com/1338/78466125-3f3ec500-76c3-11ea-90be-f176a049d2b8.png)

VS Code recognizing "Rec Mono Duotone Mono Linear" but not applying casual italic styles:
![image](https://user-images.githubusercontent.com/1338/78466134-4960c380-76c3-11ea-854a-a45124a3c92c.png)

**To Reproduce**
1. Install Recursive Mono Code Beta 1.047 fonts
2. Configure VS Code's font family to "Rec Mono Duotone" to no effect
3. Configure VS Code's font family to "Rec Mono Duotone Mono Linear" for regular styles to work, but italic to not be casual

**Environment (please complete the following information):**
- OS: Windows 10 build 18362
- Editor: VS Code 1.43.2
- Fonts: Beta 1.047

**Additional context**
I believe this behavior has been broken since the Rec Mono (Code) styles were released independently.

**Comment by arrowtype** [comment]
Hey @jdknezek, thank you so much for this detailed issue report! Ouch; these are some rough issues, but probably solvable without too much trouble.

Do you happen to know whether this did work as expected with [release 1.043](https://github.com/arrowtype/recursive/releases/tag/1.043)?

**Comment by jdknezek** [comment]
Here are the Rec Mono Duotone properties for 1.043 Beta:
![image](https://user-images.githubusercontent.com/1338/79697691-a921a780-8249-11ea-853e-59e2e86a8983.png)

In VS Code it requires the wonky name and strangely enough doesn't apply italic styles at all:
![image](https://user-images.githubusercontent.com/1338/79697710-c6ef0c80-8249-11ea-9bf8-3d30719941a3.png)
![image](https://user-images.githubusercontent.com/1338/79697713-c9516680-8249-11ea-988f-b63853f357a9.png)

**Comment by arrowtype** [comment]
Okay, thanks so much for this additional detail! I will try to resolve these issues ASAP.

**Comment by jdknezek** [comment]
Thanks for all your work on this font! I'm happy to provide any additional detail or testing.

**Comment by arrowtype** [comment]
I think I might have found the issue. 🤞

I replicated the problem on Windows 10 using a vmware virtual machine.

Then, I dropped the `STAT` tables in fonts and tried again. It seems to work for me!

@jdknezek if you want to, could you please try downloading & testing the fonts here?https://github.com/arrowtype/recursive/tree/c122f675fdf59fb3f52a624776d7997ece65e451/fonts/Recursive-Beta_1.047/Recursive_Code/Duotone-windows_fix

Here’s what I see with these:

![image](https://user-images.githubusercontent.com/45946693/81101517-47656c80-8edc-11ea-820e-bcc0b64e1e30.png)

![image](https://user-images.githubusercontent.com/45946693/81101520-48969980-8edc-11ea-9f01-1861c2b3237f.png)

Technical details: The `STAT` table is a new table meant to help apps understand the relationship in font families. This is important in the variable font, but these code families are just reg-ital-bold-boldital ("RIBBI") families, and the current instantiation script doesn't alter the `STAT` table, so it was accidentally labeling these styles as if they were still instances in the full variable family. Without the `STAT` table, it should work purely with names 1 & 2 on the `name` table, as RIBBI fonts traditionally have.

**Comment by jdknezek** [comment]
Brilliant! It looks great to me!

![image](https://user-images.githubusercontent.com/1338/81103354-885a8280-8ed6-11ea-80bc-e2cea4f33b14.png)

![image](https://user-images.githubusercontent.com/1338/81103358-8bee0980-8ed6-11ea-9fa5-071c8226b379.png)

**Comment by arrowtype** [comment]
Amazing; thanks so much for your help in isolating this issue and testing the fix!

Other code fonts have been built and are currently available here:

https://github.com/arrowtype/recursive/tree/983fe478c806e4b100a33d08b56458c6c070be08/fonts/rec_mono-for-code

They’ll be added to a proper release soon. :)
