### ISSUE TITLE
Update STAT table for new axis names

### ISSUE THREAD

**Issue by benkiel** [arrowtype/recursive#337]
The variable font build has been updated for the new axis names, but the data for the static fonts has not.

**Comment by arrowtype** [comment]
Thanks for raising this issue, Ben!

Just to be clear ... I changed the `ital` axis to have the name "Cursive" and the tag `CRSV`, but didn't change `.italic` alt glyph suffixes, and so didn't have to update opentype features (including `rvrn` designspace rules). 

Also, "Italic" instances should still keep their "Italic" naming – an instance with `slnt -15, CRSV 1` is still "Recursive _____  _____ Italic", never "Recursive _____  _____ Oblique" or "Recursive _____  _____ Cursive".

Would there be other data that requires a change, though?

**Comment by benkiel** [comment]
Actually...statics are fine after checking. Stat table needs updating.
