### ISSUE TITLE
`ss12` is the feature controling `Simplified one`, should be `ss11`

### ISSUE THREAD

**Issue by black-black-cat** [arrowtype/recursive#340]
Hello, thanks for your amazing fonts.

My question is shown in the title. I am using mono linear static v1.047.

<img width="623" alt="image_4" src="https://user-images.githubusercontent.com/15521864/79684059-2dcbf000-8261-11ea-816b-8afeec13a4db.png">

**Comment by arrowtype** [comment]
Thanks for finding and reporting this mixup, @black-black-cat! Thanks also for the kind words. :)

Actually, I think I'll instead fix the fonts to align with the documentation. Should have a patch released soon!

**Comment by arrowtype** [comment]
Hey @black-black-cat, this has been fixed as of release 1.051.

(There is a semi-related issue where the slashed zero isn't currently available in static Sans fonts. I have posted this at https://github.com/arrowtype/recursive/issues/347).

Let me know if you find any other issues! Thanks again.
