### ISSUE TITLE
Difficulty in configuring font-family for vscode

### ISSUE THREAD

**Issue by FatTonyy** [arrowtype/recursive#342]
I've done everything, installed all the fonts for editors and even restarted my laptop but I can seem to get the font to work, I have had success with JetBrains mono and fira code but can't seem to get Rec Mono Duotone to work :(, I'm I doing something wrong? also, this fonts seems fairly new so little info on it and the readme doesn't help much

**Comment by arrowtype** [comment]
Hey @FatTonyy, thanks for your interest, and sorry for the rough experience! I’m still dialing in these code fonts a bit, and have a couple of steps to add to their build scripts. :)

Just to help me out, can you please let me know what OS and version you are using?

**Comment by arrowtype** [comment]
Also, can you please share the specific text you've added to the `Editor: Font Family` setting in VS Code? Here's how mine looks (currently on macOS Catalina):

![image](https://user-images.githubusercontent.com/45946693/80419022-5332ac80-88a6-11ea-8aa3-92c0731b87c7.png)

```
"editor.fontFamily": "'Rec Mono Duotone', Menlo, monospace"
```

**Comment by FatTonyy** [comment]
I’m on windows, I just used your setup but still nothing.

**Comment by arrowtype** [comment]
Shoot, sorry about that! I will get this resolved as soon as possible.

**Comment by arrowtype** [comment]
I'm closing this and folding it into https://github.com/arrowtype/recursive/issues/336, as the two are closely related. Thanks again for filing this! I hope to have this solved in a week or so.

**Comment by arrowtype** [comment]
PS @FatTonyy I think I’ve closed this issue! Please check out [the latest release (1.050)](https://github.com/arrowtype/recursive/releases/tag/1.050) and let me know if things are working. If not, we can reopen this issue and investigate more deeply.

**Comment by FatTonyy** [comment]
Yeah seems it's working now excerpt the ligatures

**Comment by arrowtype** [comment]
Nice!

Ligatures work slightly differently than in other fonts, so you’ll need to go into VS Code's `settings.json`:

https://github.com/arrowtype/recursive#activating-opentype-features-in-code-editors

Let me know if that works, and if not, we might need to open a new issue. Thanks!

**Comment by FatTonyy** [comment]
works like a charm thanks

**Comment by arrowtype** [comment]
Haha, okay, actually, this was such a common issue for people I finally changed it. As of release 1.051, The "Rec Mono for Code" fonts now use `calt` for code ligatures, similar to other code-ligature fonts. So, you’ll need to change this next time you update (no rush to update now, though, as nothing else changed in this release).
