### ISSUE TITLE
LaTeX: error: Invalid font: -1 (1)

### ISSUE THREAD

**Issue by grea09** [arrowtype/recursive#344]
**Problem description**
When using the OTF file with modern distributions of LaTeX, an error happens reading that particular font.

**Expected behavior**
I would have expected to be able to take avantage of that font in my LaTeX document especially knowing the flexibility of both Recursive and LaTeX.

**Screenshots**

```
error: Invalid font: -1 (1)
Error producing PDF.
```

**To Reproduce**
1. Install Recursive as a system font
2. Compile the following document in XeTeX/Tectonic
```
\documentclass[twoside,openright,draft]{scrreprt}
\usepackage{fontspec}
\setsansfont{Recursive}  
\begin{document}
\section{Lorem Ipsum} dolor
\end{document}
```

**Environment (please complete the following information):**
- OS: Ubuntu/Linux Alpine
- Browser: Chrome/Irrelevant
- Fonts: 1.049 full OTF

**Additional context**
Not sure whether the incompatibility is on Recursive's side or on LaTeX/Tectonic side. Sorry if the issue is not here.

**Comment by grea09** [comment]
My bad, using the `.ttc` file and the version 1.047, the font works great ! Thanks for the good work !

**Comment by arrowtype** [comment]
Hmm, yeah TTC/OTC files are helpfully convenient, but I have found that sometimes one or the other work better. Thanks for trying both, and thanks for the kind words!
