### ISSUE TITLE
Ligatures for <>, <->, <=>

### ISSUE THREAD

**Issue by Niels-NTG** [arrowtype/recursive#346]
**Is your feature request related to a problem? Please describe.**
Recursive currently doesn't have support for ligatures for the character combinations of <>, <-> and <=>. 

**Describe the solution you'd like**
`<>`, also known as the diamond operator is common in Java and C# (eg. `LinkedHashMap<String, String> newRow = new LinkedHashMap<>();` and apparently also in Perl and VBA.` Would be nice if Recursive could render this as an actual diamond shape.

While as far as I know `<->` is not an operator in any programming language, a ligature for it would be a logical addition if Recursive would have a ligature for `<=>`, also known as the [Spaceship Operator](https://en.wikipedia.org/wiki/Three-way_comparison#"Spaceship_operator").

Here's how Fira Code (at the bottom) renders the aforementioned character combinations as compared to the latest release of Recursive with code ligatures (at the top):
<img width="1091" alt="Schermafbeelding 2020-05-11 om 11 04 32" src="https://user-images.githubusercontent.com/6061595/81544438-d6a8cf00-9377-11ea-9c25-0e757a8ee9cc.png">

**Comment by arrowtype** [comment]
Hey @Niels-NTG, thanks for the good suggestions! I’ll add these when I get the chance.

**Comment by J3Rik0** [comment]
Was looking to post this suggestion as PHP also has the spaceship operator, I can add the bitwise shifting operators in java, that Fira Code shows nicely, and the Haskell negation, which is /= unlike != in other languages, this would expand the audience of the font a bit:
![image](https://user-images.githubusercontent.com/1242984/83495708-beccf280-a4c0-11ea-94e1-34abcfeb3d55.png)

The font looks great btw, I just started using it and enjoying it so far. A world of thanks for this great font.

**Comment by duien** [comment]
I'd definitely like to have that `<=>` ligature for Ruby as well. A few other language-specific ligatures that would be great to see are `=~` and `!~` regex-match operators, and `<<-` and `<<~` heredoc symbols. I'd also love to see `|>` Elixir's pipeline operator. 

Really love Recursive! I didn't know you could do this much with a variable font, and I've been having a ton of fun playing around with it, both getting my terminal and editor set up, and in some design work as well. Thanks for making it!

**Comment by Niels-NTG** [comment]
These ligatures have been added in the latest release. They look lovely!

**Comment by arrowtype** [comment]
Thanks, @Niels-NTG! I was glad I could add in some more useful glyphs. :)
