### ISSUE TITLE
Remove overlap in common code ligatures

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#353]
Some code ligatures render with visible overlap. I see this most often in `==`. This can be easily resolved by decomposing & removing overlap in these glyphs.

![image](https://user-images.githubusercontent.com/45946693/88130536-d4999280-cba8-11ea-80ef-8e0a44a69ef5.png)

**Comment by magneticflux-** [comment]
Was this fixed in the web version, or just the "code" versions? On the web, I enabled the `dlig` font-feature for my `<code>` blocks and am seeing the same overlap:
![image](https://github.com/user-attachments/assets/38e56fce-f314-4c3b-9ab5-a7dd0646ff89)
