### ISSUE TITLE
misalignment of dots on i and j for black mono

### ISSUE THREAD

**Issue by d--b** [arrowtype/recursive#355]
**Problem description**
The dots on i and j are not placed on the same line for Black 900.

**Screenshots**
![image](https://user-images.githubusercontent.com/2219416/88337821-a39b9800-cd37-11ea-88ab-f089927f8a70.png)

**Comment by arrowtype** [comment]
Ouch, good catch! Thanks so much for the report; will fix this soon.

**Comment by arrowtype** [comment]
This is fixed in the sources, and will be fixed in a release with #359
