### ISSUE TITLE
Inconsistent baseline for Recursive Sans Linear Static (Firefox on Linux)

### ISSUE THREAD

**Issue by joshtriplett** [arrowtype/recursive#357]
**Problem description**
Inconsistent baseline, most noticeable in bold font. (Screenshot and description provided below.)

**Screenshots**
![image](https://user-images.githubusercontent.com/162737/88354031-75f12780-cd14-11ea-988f-9cdcf34f51a3.png)

Look closely at the word "Development" at the end of the headline, and notice how the baseline bounces up and down. Likewise in several other words in this screenshot. The bottom of letters like like 'e', 'o', and 's' extend below the baseline, unlike characters like 'i' and 'v'. The result feels painful to read. I don't see this with other fonts.

The effect seems more pronounced with bold versions of the font, and much more pronounced in this rendering rather than as rendered on https://www.recursive.design/ . This may be a rendering issue, but I don't see it with other fonts.

**To Reproduce**
1. Set Firefox's sans font to Recursive Sans Linear Static, 16pt. I also temporarily set the default proportional font to sans serif rather than serif, so that I'd see the new font more.
2. Go to <https://lwn.net> (or another site that uses default browser fonts).
3. Look at large bold headlines.

**Environment (please complete the following information):**
- OS: Debian GNU/Linux, latest as of today
- Browser: Firefox 78.0.2
- Fonts: Static OTF fonts from commit e13789e13389a5ed9be25191f3f461b6b9618fe2. I copied `fonts/Recursive-Beta_1.053/Recursive_Desktop/separate_OTF_TTF_statics/Static_OTF/*` into `~/.local/share/fonts/` and ran `fc-cache`.

**Comment by arrowtype** [comment]
Thanks for filing an issue! Thanks also for including enough detail to describe it well.

So, I think this is likely an issue with how your OS is handling font hinting in the OTFs. On the website, I'm using the variable TTF, which has no hinting at all. There are also static TTFs, which have hinting which I believe is somewhat different from the static OTFs. Can you maybe give those other versions a try, and let me know how they are looking for you?

**Comment by joshtriplett** [comment]
I tried the static TTFs, and the result looks much better:

![image](https://user-images.githubusercontent.com/162737/88361357-a0031380-cd2d-11ea-9bf0-db1c474b7fdc.png)

Does that look more like you'd expect the rendering to look?

**Comment by arrowtype** [comment]
> Does that look more like you'd expect the rendering to look?

Yes! And actually, the releases include woff2 files which are actually TTFs. I’d recommend using these on the web, as they have much better file compression.

@benkiel will take a look at Linux & OTF hinting, just to see whether this is a problem in the font, or something that is unavoidable in GNU/Linux right now.

Thanks for the detailed issue report!

**Comment by davelab6** [comment]
Try asking on the freetype-users list

**Comment by arrowtype** [comment]
> The effect seems more pronounced with bold versions of the font, and much more pronounced in this rendering rather than as rendered on https://www.recursive.design/

> I tried the static TTFs, and the result looks much better

Because this seems to be working well with the variable font (on the Recursive minisite) and with TTFs (and therefore the provided web WOFF2 files), I don’t really think there is a blocking issue here. 

However, to help others to avoid this potential pitfall of the OTF fonts on Linux, I have improved usage recommendations for Desktop fonts in the [latest release, v1.074](https://github.com/arrowtype/recursive/releases/tag/v1.074), and at https://github.com/arrowtype/recursive/commit/e1eff05e862f325098c8703d129ec3835b8b55d0.
