### ISSUE TITLE
Bold font weight is taken as default font in JetBrains IDE (IntelliJ IDEA)

### ISSUE THREAD

**Issue by RamananSharma** [arrowtype/recursive#362]
**Problem description**
Bold font weight is taken as default when we select Editor font in IDE settings dialog

**Expected behavior**
Regular weight should be taken as default font as the IDE doesn't allow us to choose the weight

**Screenshots**
![image](https://user-images.githubusercontent.com/1993024/88505949-73355180-cff6-11ea-8c7f-02b662470229.png)

**To Reproduce**
1. Go to 'File-> Settings'
2. Click on 'Editor -> Font'
3. Change the font to  'Rec Mono SemiCasual'
4. See the preview generated below

**Environment (please complete the following information):**
- OS: [Ubuntu 20.04]
- IDE: [JetBrains IntelliJIDEA 2020.1.2]
- Font: [commit e13789e13389a5ed9be25191f3f461b6b9618fe2]

**Comment by arrowtype** [comment]
Thanks for the detailed report, @RamananSharma!

This may have been fixed along with https://github.com/arrowtype/recursive/issues/373.

If you get a moment, can you please check whether that issue has been closed, and if not, test the updated fonts at https://github.com/arrowtype/recursive/tree/7beedaff5200a5c8000711bc92dfbeb418af94c3/fonts/rec_mono-for-code?

I ended up fixing some metadata in the fonts to better categorize them as italic, bold, & bold italic styles, as needed.

**Comment by arrowtype** [comment]
Actually, to avoid repeating issues, I will close this one and fold it into #373.

Thanks!
