### ISSUE TITLE
superior / inferior zero not working in Sans (MONO<0.5) styles

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#364]
**Problem description**

- superior / inferior zeros are not working in Sans (MONO<0.5) styles
- they _are_ working when MONO is greater than 0.5

**Screenshots**

![Kapture 2020-07-30 at 11 52 07](https://user-images.githubusercontent.com/45946693/88944767-21d9cc00-d25b-11ea-88d8-9f92d9ebbee1.gif)

**Environment (please complete the following information):**
- OS: macOS 10.15.5
- Fonts: 1.052, 1.053

**Additional context**

This is related to other issues around the `0` and OpenType features:
- https://github.com/arrowtype/recursive/issues/347
- https://github.com/arrowtype/recursive/issues/363

**Comment by benkiel** [comment]
Root cause here, below `0.5` on the `MONO` axis, `zero` is `zero.sans`. The OT feature had nothing to sub.
