### ISSUE TITLE
Improve spacing & kerning of quotes in Sans styles

### ISSUE THREAD

**Issue by raphaelbastide** [arrowtype/recursive#366]
The apostrophe seams to have spacing issues (lacks of space after it). Tested with the setting `"MONO" 0,"CASL" 0,"wght" 400,"slnt" 0,"CRSV" 0.5` on Firefox 80 and Chromium 79 on GNU Linux.

![Screenshot_2020-08-01_01-16-01](https://user-images.githubusercontent.com/193122/89087519-daeff180-d394-11ea-85fd-03f79cf72b30.png)

**Comment by arrowtype** [comment]
Thanks for the report, @raphaelbastide!

This is sort of a blend of issues. I’ll record them here so I can fix later.

## Quotes are kerned against `a` too tightly

This is the main issue. In the Sans styles, the quotes are just kerned against `a` too tightly. (In the Mono styles, there is no kerning.)

![image](https://user-images.githubusercontent.com/45946693/89574156-b020f580-d7f9-11ea-937f-9b696147d77b.png)

![image](https://user-images.githubusercontent.com/45946693/89574174-b6af6d00-d7f9-11ea-871f-c880e44fc719.png)

![image](https://user-images.githubusercontent.com/45946693/89574129-a7302400-d7f9-11ea-812f-fe0131344c54.png)

## quotes are too far to the right of their glyph space in the Linear ExtraBold source

![image](https://user-images.githubusercontent.com/45946693/89574539-51a84700-d7fa-11ea-8b42-110b47af994b.png)


## Sans Heavy Casual vs Linear `l` shaping is different

The tail of the `l` is longer in Casual than Linear. The basic structure should be somewhere in-between these two:

![image](https://user-images.githubusercontent.com/45946693/89573698-02154b80-d7f9-11ea-9838-e2a696257890.png)

![image](https://user-images.githubusercontent.com/45946693/89573752-19543900-d7f9-11ea-8a5c-737ad154494a.png)

**Comment by raphaelbastide** [comment]
Thanks for clarifying the issue @arrowtype! Also, thank you for your great work.
