### ISSUE TITLE
Add /ringbelow, add anchors to base glyphs & accents. Then, add `mark` feature. (Request: IAST and ISO 15919 Glyphs)

### ISSUE THREAD

**Issue by vizzmay** [arrowtype/recursive#367]
Many of the glyphs used in [IAST (International Alphabet of Sanskrit Transliteration)](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) and [ISO 15919 (Transliteration of Devanagari and related Indic scripts into Latin characters)](https://en.wikipedia.org/wiki/ISO_15919) are already covered under Latin Extended blocks. Some of them are not.

I am particularly interested in these glyphs:

- Ṝ = U+1E5C LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
- ṝ = U+1E5D LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
- Ḹ = U+1E38 LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
- ḹ = U+1E39 LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
- ̥ = U+0325 COMBINING RING BELOW (Used in R̥ r̥ L̥ l̥ R̥̅ r̥̅ L̥̅ l̥̅, which are ISO 15919 characters for vocalic Rs and Ls)
- Ṁ = U+1E40 LATIN CAPITAL LETTER M WITH DOT ABOVE
- ṁ = U+1E41 LATIN SMALL LETTER M WITH DOT ABOVE

**Comment by arrowtype** [comment]
We will probably fix this with combining accents. It won’t add the unicodes directly into the font, but these characters should be typable and render well with Recursive.

One question on Uppercase glyphs here, though:

The combining accents in Recursive are designed for lowercase glyphs, whereas glyphs like Ṝ or J́ would ideally get a case-specific combining accent.

Are such caps with accents required to be pre-composed in order to use case-specific accents, or is there some way in the `mark` feature to intelligently swap to .case variants of accents for uppercase glyphs?

This is related to https://github.com/arrowtype/recursive/issues/368

**Comment by arrowtype** [comment]
As an update on this for @benkiel:

- I have added the `ringbelowcomb` to all sources, with anchor `_top`
- I have added the `top` & `bottom` anchors to all base latin alphabet characters that were missing them, including .italic, .mono, and .sans alternates

These were added to the `updating-terminology` branch: https://github.com/arrowtype/recursive/commits/updating-terminology

I still need to manually fix anchor x-positioning in several glyphs (these plus their italic alts):
    - [ ] F (bottom)
    - [ ] b, d, f (top, at ascenders)
    - [ ] j, q (bottom)

However, I think that now that they are included in the fonts, you should hopefully be able to add the `mark` feature to the build when you have an opening to. I will correct those anchor placements ASAP.

**Comment by benkiel** [comment]
The mark feature can swap intelligently.

**Comment by arrowtype** [comment]
Awesome!

**Comment by arrowtype** [comment]
This isn’t quite closed just yet, but is under active work.

**Comment by arrowtype** [comment]
- [ ] To fix the `Ṝ ṝ Ḹ ḹ` issue, I will add top anchors to R dot below etc 
  - [ ] When I do, I’ll add the R dot below and L dot below to the `base_uc` class in  `src/features/features/ccmp.fea`
  - [ ] We will also need to update `mastering/utils.py`

**Comment by arrowtype** [comment]
This is currently working well in the variable font, though not quite in static fonts, in this [beta 1.076 test build](https://github.com/arrowtype/recursive/tree/7e0023408a94f3fb26e15a51d712d8103a7bf08a/fonts/fonts_1.076_BETA). (The static fonts still have the issue with lost anchors in alt glyphs, https://github.com/arrowtype/recursive/issues/448).

![image](https://user-images.githubusercontent.com/45946693/111036755-d7265200-83ee-11eb-957b-980da4b635fb.png)

**Comment by arrowtype** [comment]
Okay, it’s now working well in the variable and static fonts! Will be released as v1.077.

![image](https://user-images.githubusercontent.com/45946693/111057907-d1655680-8458-11eb-8e53-299711546f1f.png)

**Comment by benkiel** [comment]
This is done. Closing.
