### ISSUE TITLE
Italic variant (and possibly bold) are not being detected by Windows applications

### ISSUE THREAD

**Issue by javlaks** [arrowtype/recursive#373]
**Problem description**
The italic variant is not being detected by windows applications. When I or the editor make italic, the regular font is being transformed to Italic instead of take Italic font variant

**Expected behavior**
Windows applications need to use the Italic variant instead of create italic from regular font

**Screenshots**
Here you can see from word document (right), and how should be showed (left)
![image](https://user-images.githubusercontent.com/513351/89459132-cc576080-d72d-11ea-8bab-c1f36961803c.png)

Same case using Dank Mono, this is displaying correctly using the italic font variant
![image](https://user-images.githubusercontent.com/513351/89459202-e3964e00-d72d-11ea-9e9c-c13c09578133.png)

Not only in word, this happend in most of windows applications, here two examples from Notepad++

Rec Mono Duotone
![image](https://user-images.githubusercontent.com/513351/89459279-00cb1c80-d72e-11ea-9aab-b09d964b3765.png)

Dank Mono
![image](https://user-images.githubusercontent.com/513351/89459302-07f22a80-d72e-11ea-85c7-aef2849f5711.png)

**To Reproduce**
Just make italic text on any windows application text editor or programming editor

**Environment**
OS: Windows 10 v1909
Font: 1.055
Notepad++: 7.8.4
Microsoft Word: 365 Version (16.0)

**Additional information**
This issue is not present in Visual Studio Code 1.47.3
![image](https://user-images.githubusercontent.com/513351/89459808-dc237480-d72e-11ea-8b23-d6044841b89e.png)

**Comment by iansan5653** [comment]
I'm seeing this in Intellij.

**Comment by arrowtype** [comment]
Hmm, that is odd. Thanks for the report, @javlaks!

The fix isn’t immediately clear to me, though I’ll try to keep an eye out for a solution.

In the near term, I recommend using the normal Recursive Mono fonts in apps that are for design and general word processing. These seem to work well for me in Windows. Here’s Wordpad:

![image](https://user-images.githubusercontent.com/45946693/89554613-16e3e600-d7dd-11ea-86fa-383b739ba634.png)

**Comment by iansan5653** [comment]
@arrowtype While the first two screenshots were from Word, we're also seeing this when using code fonts in the Notepad++ and IntelliJ code editors.

**Comment by arrowtype** [comment]
@javlaks okay, I may have solved this. Would you be willing to confirm with one of the families at https://github.com/arrowtype/recursive/tree/7beedaff5200a5c8000711bc92dfbeb418af94c3/fonts/rec_mono-for-code?

![image](https://user-images.githubusercontent.com/45946693/89563044-d8542880-d7e8-11ea-877d-32ea49c56f06.png)

I found that I needed to set a few values for Bold, Italic, & Bold Italic fonts:

1. In the OS/2 table, Panose `bLetterform` must be set to 11, for oblique fonts
2. In the OS/2 table, the `fsSelection` needed to be set to italic/bold/bolditalic
3. In the head table, the `macStyle`  needed to be set italic/bold/bolditalic (probably not relavent to Windows, but related to the overall issue)

I _think_ this might solve the issues in most Windows apps, and maybe even in IntelliJ. 🤞

@iansan5653 if you would be willing to try one of the updated families in IntelliJ, that would also be super helpful!

**Comment by javlaks** [comment]
Hey @arrowtype you're super fast!

It is working now :P

Wordpad
![image](https://user-images.githubusercontent.com/513351/89564499-b2c42080-d7e2-11ea-82aa-a1768b4b52a6.png)

Notepad++
![image](https://user-images.githubusercontent.com/513351/89565267-f10e0f80-d7e3-11ea-9ec7-dc66de57e030.png)

Netbeans
![image](https://user-images.githubusercontent.com/513351/89565283-f53a2d00-d7e3-11ea-81cf-0aaea0e9a4d9.png)

We only have pending a fix for the ligatures ( #369 )

Thank you for the hark work and the font ;)

**Comment by arrowtype** [comment]
Yeeeeah thanks for helping to check that so quickly, @javlaks! 💪

I’ll wait to see whether @iansan5653 can check out things in IntelliJ before closing this / possibly moving that to a new issue.

**Comment by iansan5653** [comment]
Sorry for the delay - I tried in IntelliJ and it's working! Thanks.

**Comment by arrowtype** [comment]
Awesome, thanks so much for taking a look, @iansan5653!
