### ISSUE TITLE
Code fonts in 1.054 are still version 1.053

### ISSUE THREAD

**Issue by iansan5653** [arrowtype/recursive#374]
**Problem description**
If you donwload the ZIP for version 1.054, the code fonts are all still version 1.053 (ie, `RecMono-LinearBold-1.053.ttf`).

**Expected behavior**
I would expect to see 1.054 fonts.

**Comment by iansan5653** [comment]
I do see the version is bumped in Windows Font Settings, so I think this is just for the file names.

**Comment by arrowtype** [comment]
🤦‍♂️ Haha, yup, I had updated the versions in file metadata, but missed some of the filenames.

Thanks for pointing out that discrepancy, @iansan5653! It should be fixed now, still in the same release but with updated files.

(I also noticed that the woff2 files still had the previous version numbers, so I remade those from the newer TTFs.)
