### ISSUE TITLE
Font Name in GVim is weird

### ISSUE THREAD

**Issue by ghsgz** [arrowtype/recursive#409]
**Problem description**
I use it in GVim, but if I set the font as the full name **Recursive Mono Linear Static**, it does not work. I set it use the full font name in VSCode before, it worked.

**Expected behavior**
In GVim, users can set this font by use its full name: **Recursive Mono Linear Static**

**Screenshots**
the GVim font select window:
![1](https://user-images.githubusercontent.com/34056529/93769038-e4872e80-fc4c-11ea-9fdc-7bcf327a693b.png)
But the worked font name and displayed name is different:
![2](https://user-images.githubusercontent.com/34056529/93769182-08e30b00-fc4d-11ea-804e-57c95d447df0.png)

**To Reproduce**
......

**Environment (please complete the following information):**
- OS: Win10 Home 2004
- Fonts: v 1.065 at commit db192fc

**Additional context**
- Through Vim command: `:set guifont=*`, we can select the font through a font slelect window. In this window, this font name is **Recursive Mono Linear Static**.
- Select Recursive Mono Linear Static by hand, then through Vim command: `:set guifont?`, the vim output area shows: 
 `guifont=Recursive_Mn_Lnr_St:h12`
- This difference of font name confused me at first.
- I just installed this font: **"~\Downloads\ArrowType-Recursive-1.065\Recursive_Desktop\separate_statics\TTF\RecursiveMonoLnrSt.ttf"**, 4 font weight: Regular Italic Bold and Bold Italic
- I have no idea whether this issue lies in GVim or The font itself.

**Comment by arrowtype** [comment]
Shoot, it is hard to know where this issue lies.

Have you tried the "Rec Mono for Code" fonts, by any chance? They are simplified a bit, and tend to work better in some code environments. If they do work better but you don’t want ligatures, you can configure your own Rec Mono family at

**Comment by arrowtype** [comment]
(Sorry, this sent early)

...you can configure your own Rec Mono family at https://github.com/arrowtype/recursive-code-config

**Comment by arrowtype** [comment]
@ghsgz This might actually be working in an expected way, though I can see how it would be _unexpected_ for users. Maybe I can add something to the readme about it.

**Questions for you**
1. Were you able to get the font to display in Gvim?
2. Is your main comment that the difference here is unexpected as a user?

What might be going on is this:
- Fonts actually have multiple name entries, used for different purposes. Basically, they have user-friendly names, and other names for specific software.
- Due to historical software issues, some of those names need to be below a certain character count, or have special qualities
- Name 16, the family name used in font menus that support it, is `Recursive Mono Linear Static`
- Meanwhile, Name 4, used in some older font menus, is `Recursive Mn Lnr St` because it has to be less than a certain number of characters (different numbers, depending on who you ask, but it’s sometimes said this is 31, 29, 27, 24, or even 20).

So, it seems that the GUI for setting fonts uses the nice name, while the code way takes Name 4 and replaces spaces with underscores.

Please let me know if you can’t get the font to work! If it is basically working, can you think of what advice you might give another user, to let them know what to expect? I can take this and try to think of how to add it to the readme. Or, at minimum, it will be here in case other GVim users search for it!

<details>
<summary><b>Name table in Recursive Mono Linear Static</b> (Click to expand)</summary>

<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.13">

  <name>
    <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Copyright 2019 The Recursive Project Authors (github.com/arrowtype/recursive)
    </namerecord>
    <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Recursive Mn Lnr St
    </namerecord>
    <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      1.065;ARRW;RecursiveMonoLnrSt-Regular
    </namerecord>
    <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Recursive Mn Lnr St
    </namerecord>
    <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Version 1.065;hotconv 1.0.115;makeotfexe 2.5.65600; ttfautohint (v1.8.3)
    </namerecord>
    <namerecord nameID="6" platformID="1" platEncID="0" langID="0x0" unicode="True">
      RecursiveMonoLnrSt-Regular
    </namerecord>
    <namerecord nameID="13" platformID="1" platEncID="0" langID="0x0" unicode="True">
      This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
    </namerecord>
    <namerecord nameID="256" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Single-story ‘a’
    </namerecord>
    <namerecord nameID="257" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Single-story ‘g’
    </namerecord>
    <namerecord nameID="258" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified Mono ‘f’
    </namerecord>
    <namerecord nameID="259" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified Mono ‘i’
    </namerecord>
    <namerecord nameID="260" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified Mono ‘l’
    </namerecord>
    <namerecord nameID="261" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified Mono ‘r’
    </namerecord>
    <namerecord nameID="262" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified italic diagonals
    </namerecord>
    <namerecord nameID="263" platformID="1" platEncID="0" langID="0x0" unicode="True">
      No-serif  18L 19 &amp; ‘Z’
    </namerecord>
    <namerecord nameID="264" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified Six &amp; Nine
    </namerecord>
    <namerecord nameID="265" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Dotted Zero
    </namerecord>
    <namerecord nameID="266" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified One
    </namerecord>
    <namerecord nameID="267" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Simplified Mono ‘at’
    </namerecord>
    <namerecord nameID="268" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Slashed Zero
    </namerecord>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2019 The Recursive Project Authors (github.com/arrowtype/recursive).
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Recursive Mn Lnr St
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      1.065;ARRW;RecursiveMonoLnrSt-Regular
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Recursive Mn Lnr St
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 1.065;hotconv 1.0.115;makeotfexe 2.5.65600; ttfautohint (v1.8.3)
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      RecursiveMonoLnrSt-Regular
    </namerecord>
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Recursive Mono Linear Static
    </namerecord>
    <namerecord nameID="256" platformID="3" platEncID="1" langID="0x409">
      Single-story ‘a’
    </namerecord>
    <namerecord nameID="257" platformID="3" platEncID="1" langID="0x409">
      Single-story ‘g’
    </namerecord>
    <namerecord nameID="258" platformID="3" platEncID="1" langID="0x409">
      Simplified Mono ‘f’
    </namerecord>
    <namerecord nameID="259" platformID="3" platEncID="1" langID="0x409">
      Simplified Mono ‘i’
    </namerecord>
    <namerecord nameID="260" platformID="3" platEncID="1" langID="0x409">
      Simplified Mono ‘l’
    </namerecord>
    <namerecord nameID="261" platformID="3" platEncID="1" langID="0x409">
      Simplified Mono ‘r’
    </namerecord>
    <namerecord nameID="262" platformID="3" platEncID="1" langID="0x409">
      Simplified italic diagonals
    </namerecord>
    <namerecord nameID="263" platformID="3" platEncID="1" langID="0x409">
      No-serif ‘L’ &amp; ‘Z’
    </namerecord>
    <namerecord nameID="264" platformID="3" platEncID="1" langID="0x409">
      Simplified Six &amp; Nine
    </namerecord>
    <namerecord nameID="265" platformID="3" platEncID="1" langID="0x409">
      Dotted Zero
    </namerecord>
    <namerecord nameID="266" platformID="3" platEncID="1" langID="0x409">
      Simplified One
    </namerecord>
    <namerecord nameID="267" platformID="3" platEncID="1" langID="0x409">
      Simplified Mono ‘at’
    </namerecord>
    <namerecord nameID="268" platformID="3" platEncID="1" langID="0x409">
      Slashed Zero
    </namerecord>
  </name>

</ttFont>
 
</details>

Thanks for taking the time to file this!

**Comment by ghsgz** [comment]
Thanks for your detailed reply!

For your questions:
1. Were you able to get the font to display in Gvim?
Yes, works fine!
2. Is your main comment that the difference here is unexpected as a user?
I think so. I tried three times, finally make Recrusive Mono Static works in GVim, just because the font name in the GVim font slection dialog.
The workaround configuration for GVim is `set guifont=Recursive_Mn_Lnr_St`

Thanks for your answer! Maybe this issue will provide an reference for those who has the same problem.

And sorry for my poor english, I think this is just a small problem, but I could not descript it concisely, that is my question, but you replied me carefully, thank you so much!

**Comment by arrowtype** [comment]
Hey, thanks for following up! Sorry I took a pause from responding to issues here for awhile.

Thanks for sharing the solution for you!

Okay, yes, this makes sense now. It is unfortunate that the naming is a bit odd like that. I will consider whether there is something I could add to the documentation or download `README`s to hopefully point that out to people.

(Also, your English is fine! Thanks for taking the time to write this issue, and kudos to you for being multi-lingual! I know basically nothing outside of English, so I always admire folks who who are able to understand more than one language.)

**Comment by arrowtype** [comment]
One followup to clarify for anyone else reading along: I was about to put this in the readme, but I realized that it doesn’t really need to be there, as there is nothing to really advise people of. 

The font works as expected in Gvim, it’s just that the abbreviated name is shown in the configuration file once the font is selected in the font selection panel. Nice! 🎉

**Comment by alerque** [comment]
True. This is also expected behaviour when using GVim (and a number of other VIM based UIs) and documented in tutorials on how to customise the UI. Knowing what font names to enter and what format to enter them is not really a font's responsibility to document, it is the editor's.
