### ISSUE TITLE
U+220F N-ARY PRODUCT is too short

### ISSUE THREAD

**Issue by dscorbett** [arrowtype/recursive#410]
**Problem description**
The glyph for U+220F N-ARY PRODUCT should descend below the baseline because it is an _n_-ary operator. Compare the glyph for U+2211 N-ARY SUMMATION, which is correct. The current glyph for U+220F would be appropriate for U+03A0 GREEK CAPITAL LETTER PI.

**Screenshot**
![∏∑](https://user-images.githubusercontent.com/1124347/94347432-16f4ab00-0002-11eb-87fe-c24fd1747d4e.png)

**Environment**
- OS: macOS 10.14.6
- Font: 1.065

**Comment by arrowtype** [comment]
I wasn’t aware of that – thanks so much for letting me know!

**Comment by arrowtype** [comment]
Fixd this in sources with dbdb242a4178e79f64578296cec8d02122a26c93, will build into release soon!

![image](https://user-images.githubusercontent.com/45946693/101290301-475d8000-37cf-11eb-9a36-da940f604869.png)
