### ISSUE TITLE
Incomplete stylistics sets

### ISSUE THREAD

**Issue by dscorbett** [arrowtype/recursive#411]
**Problem description**
Some stylistic sets are incomplete.

'ss03' simplifies ⟨f⟩ and related characters, except for U+FB01 LATIN SMALL LIGATURE FI and U+FB02 LATIN SMALL LIGATURE FL.
![fﬁﬂ](https://user-images.githubusercontent.com/1124347/94872610-105b9e80-041b-11eb-8d4c-2e37cace692f.png)

'ss04' simplifies ⟨i⟩ and related characters, except for U+0131 LATIN SMALL LETTER DOTLESS I.
![iı](https://user-images.githubusercontent.com/1124347/94872796-8c55e680-041b-11eb-880e-90cbdf2d895b.png)

'ss05' simplifies ⟨l⟩ and related characters, except for U+FB02 LATIN SMALL LIGATURE FL.
![x](https://user-images.githubusercontent.com/1124347/94872941-f3739b00-041b-11eb-963e-e59823b6c4eb.png)

'ss08' simplifies ⟨L⟩, ⟨Z⟩, and related characters, except for U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT, U+01C4 LATIN CAPITAL LETTER DZ WITH CARON, and U+01F1 LATIN CAPITAL LETTER DZ.
![LZĿǄǱ](https://user-images.githubusercontent.com/1124347/94873205-93312900-041c-11eb-822e-302d6a6671cc.png)

'ss11' simplifies ⟨1⟩ but skips U+00B9 SUPERSCRIPT ONE, U+00BC VULGAR FRACTION ONE QUARTER, U+00BD VULGAR FRACTION ONE HALF, U+2081 SUBSCRIPT ONE, U+2153 VULGAR FRACTION ONE THIRD, and U+215B VULGAR FRACTION ONE EIGHTH.

![1¹¼½₁⅓⅛](https://user-images.githubusercontent.com/1124347/94873350-ec00c180-041c-11eb-9f73-d8a585f1859d.png)

**Environment (please complete the following information):**
- OS: macOS 10.14.6
- Font: 1.065

**Comment by arrowtype** [comment]
Thanks for taking the time to file the issue, and especially to include good screenshots!

> 'ss04' simplifies ⟨i⟩ and related characters, except for U+0131 LATIN SMALL LETTER DOTLESS I.

- [ ] Good catch! I will fix this.

> 'ss08' simplifies ⟨L⟩, ⟨Z⟩, and related characters, except for U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT, U+01C4 LATIN CAPITAL LETTER DZ WITH CARON, and U+01F1 LATIN CAPITAL LETTER DZ

 - [ ] Another good catch – I will also fix these.

> 'ss03' simplifies ⟨f⟩ and related characters, except for [U+FB01 ligature `fi` and U+FB02 ligature `fI`]
> 'ss05' simplifies ⟨l⟩ and related characters, except for [U+FB02 ligature `fI`]

The `fi` and `fl` ligatures shouldn’t be used where code is being displayed, and these ligatures are really only in the font for optional ligatures in the proportional / Sans styles, so I unless there is a good reason to include these, I will not be changing this behavior.

> 'ss11' simplifies ⟨1⟩ but skips [fractions]

Yes, fractions always have fixed-width numbers, and the spacing within them would look bad with a simplified 1. Additionally, there will never be an `l` in these fractions, so there is no chance for ambiguity, which is what the normal ss11 `1` is intended to fix. So, I will not be changing this.

--

Thanks again for finding these, @dscorbett! I’m curious – how did you discover these issues? I am always looking for better ways to proof fonts for quality, and you found a few things I clearly missed. :) I’d be interested if you have any tips. Cheers!

**Comment by dscorbett** [comment]
I scrolled through the font in FontForge, enabling each stylistic set in turn and keeping an eye out for missing substitutions. It works for small fonts but is not terribly efficient, and it’s easy to miss things. A better way would be, whenever you create a new glyph, to note what other glyphs it is related to, and whenever you make a change to or a stylistic set for a glyph, to check that glyph’s notes for what other glyphs might need changing.

**Comment by arrowtype** [comment]
Oh cool, I didn’t realize FontForge had that functionality! Sounds useful.

Nice idea – I might have to give it a try.

**Comment by arrowtype** [comment]
I’ve fixed these two issues in the source UFOs, and I am currently building fonts with the updates. Here’s the variable font, now working better with ss04 and ss08:

![image](https://user-images.githubusercontent.com/45946693/105435850-1d033d00-5c2c-11eb-9ba6-72177c120176.png)

Before:
![image](https://user-images.githubusercontent.com/45946693/105435859-2391b480-5c2c-11eb-81f8-ede30dc4869c.png)

**Comment by arrowtype** [comment]
Closed with https://github.com/arrowtype/recursive/releases/tag/v1.072
