### ISSUE TITLE
Does it support SemiLight?

### ISSUE THREAD

**Issue by vuongggggg** [arrowtype/recursive#413]
As the question in title, I'm not sure if Recursive support SemiLight? 
The Light is slightly thin and the Regular is a little bold for me.

Thanks for the nice font!

**Comment by arrowtype** [comment]
Hey @vuongggggg, thanks for your interest!

There is no premade or preset "SemiLight" instances for Recursive, _BUT_ the project includes a variable font, so there are various ways you can get & use a SemiLight style, and probably a solution that will work for your needs.

What context are you trying to use Recursive in? E.g. on the web, in a code editor, in MS Word, for packaging design, etc?

**Comment by vuongggggg** [comment]
Hi @arrowtype, thanks for replying.

I use Recursive for coding, VSCode.

**Comment by arrowtype** [comment]
> I use Recursive for coding, VSCode.

Nice! You’re in luck: the Recursive Code Config repo has YAML config + script + instructions you can follow to make a custom 4-style family to have exactly the weight you want for your "Regular" text. E.g. if you want normal text to be in a weight between the current Light & Regular, adjust [Line 42 in config.yaml](https://github.com/arrowtype/recursive-code-config/blob/7d5463ab65b84f4fb886c4eb1b1a85ef364706d9/config.yaml#L42) to be `wght: 350`, then build the fonts. You can repeat this process to dial in exactly the weight you want!

If you want to preview the weight before building & checking, you could try one of a few things:
- Install the variable font from the latest release, & make a mockup in Sketch (if you have it), if you have it (simulate your color scheme to get a good idea of how things will look – text looks really different between light/dark themes)
- Install the [Chrome plugin Type-X](https://chrome.google.com/webstore/detail/type-x/bfnfnnicdjkkialkldogjjmmfeiopbin), then activate it in a [Code Sandbox](https://codesandbox.io/) and tweak the weight in Type-X to find the exact style you like (be sure to set the MONO slider to `1` if you like coding with monospace fonts, as most people do. I think Code Sandbox will even pick up your local theming from VS Code settings, so this would probably be a really good simulation of it!

**Comment by arrowtype** [comment]
I’ll close this comment for now, but feel free to add extra questions if you have them!
