### ISSUE TITLE
Bug on macOS pre-11 makes "A" show up with rendering problems in static fonts from Google Fonts. Test splitting "A" bar to fix this.

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#414]
## Problem 

![image](https://user-images.githubusercontent.com/45946693/97085908-6a9ce900-15ee-11eb-9433-c923714ff8d0.png)

As seen on https://www.a11yproject.com/

![image](https://user-images.githubusercontent.com/45946693/97085915-725c8d80-15ee-11eb-93b5-067a5a8dbec1.png)

Also occurs in the Ø:

![image](https://user-images.githubusercontent.com/45946693/97086454-560e2000-15f1-11eb-8103-44f93e25dae0.png)

## Fix

![image](https://user-images.githubusercontent.com/45946693/97085939-8b653e80-15ee-11eb-849c-e78dcfc7ae86.png)

https://twitter.com/ArrowType/status/1312023807939444736?s=20

## Check

Check that "remove overlap" still works to create OTF fonts from the split-bar. Also check that the VF overlap can be removed in Adobe Illustrator. If yes and yes, make a new release & PR to Google Fonts!

**Comment by arrowtype** [comment]
Oh, actually, it seems like maybe Google Fonts has solved the issue already? 

https://codepen.io/thundernixon/pen/yLJgRKQ

**Comment by alerque** [comment]
There are (at least) two other major places this is being tracked:

* Google Fonts deployment issue: https://github.com/google/fonts/issues/2602
* Fontmake build time workaround: https://github.com/fonttools/fonttools/pull/2068
