### ISSUE TITLE
Which static fonts should be in the Google Fonts downloadable zip?

### ISSUE THREAD

**Issue by m4rc1e** [arrowtype/recursive#416]
Google Fonts currently creates static fonts by instantiating all possible axis combinations from a VF. For Recursive, this means we'll have around  [85 static fonts](https://docs.google.com/spreadsheets/d/1bm3CMWgSYZGR9Ac8LNJvhO2NwT3y5VT7eeagQ1yIwLI/edit#gid=2080829662).

I see you've included a [static fonts directory](https://github.com/arrowtype/recursive/tree/main/fonts/ArrowType-Recursive-1.066/Recursive_Desktop/separate_statics/TTF), would you prefer us to use these style combinations instead for the downloadable static fonts? We may still end up deriving the static fonts from the VF but we can limit the amount of generated static fonts based on what's in this dir.

Another option is to highlight the rows in the spreadsheet.

**Comment by arrowtype** [comment]
> I see you've included a static fonts directory, would you prefer us to use these style combinations instead for the downloadable static fonts?

I don't know whether it is the best solution for every project, but for Recursive, **yes**. The static fonts here were generated from a build process made by @benkiel, who has been mastering static fonts for type foundries for years. I trust them a lot more than something auto-generated from the VF. They also happen to have autohinting, which may be useful in some scenarios.

**Comment by m4rc1e** [comment]
Ok, but would you be opposed to us instantiating static fonts from the VF which use the same coordinates and names as the static fonts? sorry if that wasn't clear.

**Comment by arrowtype** [comment]
Oh, yes, sorry to miss that question.

Yes, that would be the next best thing. 😄

Note: one current issue of the statics instantiated from the VF is this: https://github.com/a11yproject/a11yproject.com/issues/1137 (the `A` crossbar macOS problem). Ideally, there might be a way to avoid that without requiring manual edits to the glyph paths (e.g. in most cases, it should be fine to just remove overlaps on generated statics).

**Comment by arrowtype** [comment]
Also, I can highlight rows in the spreadsheet soon if that is helpful, but the instance locations can also be seen in the main designspace of the project:

https://github.com/arrowtype/recursive/blob/main/src/ufo/recursive-MONO_CASL_wght_slnt_ital--full_gsub.designspace

**Comment by arrowtype** [comment]
Closing this, but feel free to let me know if you have any further questions, @m4rc1e!
