### ISSUE TITLE
Change the "@" sign to be more legible and aesthetic.

### ISSUE THREAD

**Issue by maxvons** [arrowtype/recursive#419]
First of all, I want to say that this font is as close to perfect as it gets. But I would like to propose a change that could make it even better.

Problem:
As it is right now, the "at sign" or "@" is not very legible or aesthetic. It just looks like a "blob" in my opinion.

<img width="262" alt="Screenshot 2020-11-12 at 19 12 51" src="https://user-images.githubusercontent.com/43211032/98979123-3fd1f080-251b-11eb-943b-80d85f2bd6a9.png">

![Screenshot 2020-11-12 at 19 08 41](https://user-images.githubusercontent.com/43211032/98979143-4496a480-251b-11eb-9a8e-1bb364437918.png)

Solution:
I would propose to change the "@" to something that more closely resembles the sans variant. So that it looks more like this:
 
<img width="307" alt="Screenshot 2020-11-12 at 19 12 57" src="https://user-images.githubusercontent.com/43211032/98979079-3052a780-251b-11eb-9abc-0b5a4a8b8e9d.png">

Maybe this could be done only for the variants of the font that are included in the "Code" folder. F.ex. Rec Mono Linear, Rec Mono Semicasual, Rec Mono Casual, and Rec Mono Duotone.

**Comment by arrowtype** [comment]
Hey @maxvons, thanks for the kind words!

Keeping the @ sign narrow enough to fit into monospace constraints requires one tradeoff or another, and I know this style was a slightly cheeky thing to make the default. :) But, the philosophy in Recursive is to make things as animatable where possible, and I like that that could even work for this character.

However, with [stylistic set 12](https://github.com/arrowtype/recursive#opentype-features), you can swap the style of the at symbol:

![image](https://user-images.githubusercontent.com/45946693/98987674-7fd1ad00-24f4-11eb-8c91-1c49120497bd.png)

I may consider making this the default in future Rec Code fonts. If you want it immediately, though, you can configure this at 
 https://github.com/arrowtype/recursive-code-config

**Comment by maxvons** [comment]
I just found out about that build option after I posted the issue. Thank you so much! This makes the font perfect for me 😍

**Comment by arrowtype** [comment]
Awesome, that’s great to hear! Let me know if anything else comes up; I’m slowly but surely trying to iron out all the issues. 🙂
