### ISSUE TITLE
Release zips include fonts twice

### ISSUE THREAD

**Issue by faraixyz** [arrowtype/recursive#433]
**Problem description**
In the release zips, the fonts are included twice in separate folders since 1.070

**Expected behavior**
Have the fonts in just one folder

**To Reproduce**
1. Download the latest release zip https://github.com/arrowtype/recursive/releases/download/v1.070/ArrowType-Recursive-1.070.zip
2. Extract the zip

**Environment (please complete the following information):**
- OS: N/A
- Browser: N/A
- Fonts: [v1.070]

**Additional context**
I think [/src/build-scripts/make-release/00-prep-release.sh](https://github.com/arrowtype/recursive/blob/a1fab1a85ba775d0f6ba4e21ac2eac5ec5797dff/src/build-scripts/make-release/00-prep-release.sh) is responsible for generating the release folders, so I might be able to fix it sometime.

**Comment by arrowtype** [comment]
Haha, that is an embarrassing oversight. Thank you for taking the time to report it!

I have updated release 1.070 with a corrected zip and tested it on my end. If you want, would you be willing to download it again and confirm?

**Comment by arrowtype** [comment]
## Additional context

_This may be TMI, but part of it is to document my current thinking process for future reference._

I was using the CLI tool `zip` to make zips, but my usage was causing that unintended stacking. I am still not 100% certain of why.

I have updated my zip function to the following, and it now seems to work better:

```bash
function zipit {
  currentDir=$(pwd)
  cd $(dirname $1)
  target=$(basename $1)
  zip -r $target.zip $target -x '*/.DS_Store'
  echo "zip made of " $1
  cd $currentDir
}

# usage: zipit <filepath>
```

I have that in my `.bash_profile`, then run it manually after adding Code fonts into the font directory. 

I could move this into the `00-prep-release.sh`, but a current problem is that I have separated my Recursive Code generation into a separate repo, https://github.com/arrowtype/recursive-code-config/.  So, currently there are a couple of semi-manual steps in the release process.

Thank you for the offer to improve `00-prep-release.sh`! However, I think the main blocker is that I am slightly uncertain of the best way to design the release workflow. I could, in that release script, `cd` to the code config directory on my computer, but then the script would be overly tied to my computer. I previously had duplicate scripts for `src/build-scripts/make-release/dlig2calt.py` and `src/build-scripts/make-release/instantiate-code-fonts.py` in the Recursive repo, but these just slightly different from the code config versions, and this split became more painful to maintain than doing occasional semi-manual releases.

I may have to look into Git submodules or Python packages as a solution to this problem (I’m open to suggestions/advice on this front!) ... but also, this project is edging closer to being “complete,” so I likely don’t have many future releases to make, and automating it might take more time than it would save.

**Comment by faraixyz** [comment]
I checked the download and it doesn't duplicate it anymore. Since you side you're nearly done, I guess it makes sense not to overhaul the release pipeline too much, so I'll try look to see if `00-prep-release.sh` can be fixed some time.

**Comment by arrowtype** [comment]
Thanks for confirming!

> I'll try look to see if 00-prep-release.sh can be fixed some time

Thanks, but before you do that, what aspects of it do you think require fixing?
