### ISSUE TITLE
Feature Request: Offer a simplified curly braces variant

### ISSUE THREAD

**Issue by muhammadsammy** [arrowtype/recursive#446]
Thank you for this beautiful font!

**Is your feature request related to a problem? Please describe.**
It would be nice if the shape of curly braces can be changed to a more simplified version

**Describe the solution you'd like**
This could be enabled by a font feature e.g `ss13` and maybe the same curly braces in the `casual` variant could be used as a simple curly

**Comment by arrowtype** [comment]
Thanks for filing an issue!

Is there an example of what kind of shaping you are hoping for? 

To be honest, a fair amount about this font (especially in the Casual styles) embraces personality over total simplicity, so I'm fairly uncertain about adding alternate glyph for this...

**Comment by muhammadsammy** [comment]
> Thanks for filing an issue!
> 
> Is there an example of what kind of shaping you are hoping for?
> 
I meant something like this from Cascadia Code or Jetbrains Mono
![image](https://user-images.githubusercontent.com/35064832/110143595-0da51100-7de0-11eb-87a4-bc7d748bc1d9.png)
![image](https://user-images.githubusercontent.com/35064832/110143762-4349fa00-7de0-11eb-865d-bd82f6959e01.png)

> To be honest, a fair amount about this font (especially in the Casual styles) embraces personality over total simplicity, so I'm fairly uncertain about adding alternate glyph for this...
>
That's totally understandable. If adding this alternative glyph does not align with the design, feel free to close this ticket!

**Comment by arrowtype** [comment]
To be honest, I like the current curly braces as they are, and this would feel like too small a change to be very meaningful. If someone comes along and *really* wants different braces, it’s an OFL font, so they could fork the project, or hire me separately to add some different braces as a [character variant feature](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#cv01-cv99). But, for now, I’ll close this.

![image](https://user-images.githubusercontent.com/45946693/114229566-0379b380-9946-11eb-9022-5fde43c6dcb5.png)

**Comment by arrowtype** [comment]
(If people still come across this issue and also would want this to be considered as a future change, feel free to put a 👍 reaction on the first comment)

**Comment by effinsky** [comment]
for me, definitely one of the more nasty-looking features of this font -- one I otherwise enjoy!

**Comment by kajukenbo** [comment]
As an awk user, I will say that I appreciate the clear and distinct curly braces.
Being able to tell characters that are "less frequently used by many others" apart at a glance is why I use Recursive Mono Linear Static.
Same goes for the tilde.  In fact it could stand out a bit more.
Not being able to distinguish between glyphs instantly is a fail, IMO.

Please keep up the good work.

[{(ioa@l1IL0O6b5S$%^~-B8&*.,;:`"'\
