### ISSUE TITLE
Add 'mark' feature to fully cover all alternates (e.g. ".italic" glyphs) in static fonts

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#448]
PR https://github.com/arrowtype/recursive/pull/441 was a big upgrade to the localization and mark-related features of Recursive, but despite closing several open issues, it also revealed that a thoroughly arbitrary `mark` feature would be nice to support in the static fonts (as it did add this in the variable font).

_Below: the top row shows marks combining well in the Recursive variable (v1.075), but not in `.italic` alternates of one of the Static fonts (also v1.075)._

![image](https://user-images.githubusercontent.com/45946693/110967945-f2c52600-8324-11eb-9e83-916074668307.png)

My understanding is that solving this would require writing a bit of static-specific feature code, similar to how the project applies the `fi` ligature in Italic styles only, variable and static. Hopefully, @benkiel might have bandwidth available to help solve this. 🤞

**Comment by arrowtype** [comment]
According to @benkiel, this is a result of an issue in ufoProcessor, https://github.com/LettError/ufoProcessor/issues/26 – when alt glyphs are swapped (i.e. `n.italic` becomes just `n` for Italic UFOs that are prepped for static output), the anchors are lost. This is why the `mark` feature stops working in the statics (which uses ufoProcessor), but does work in the variable fonts (which has a FontMake-based build).

**Comment by benkiel** [comment]
Once the above update is made to ufoProcessor, this issue can be closed.

**Comment by arrowtype** [comment]
This was closed by [release 1.077](https://github.com/arrowtype/recursive/releases/tag/v1.077) and is working well now.

![image](https://user-images.githubusercontent.com/45946693/114229325-ac73de80-9945-11eb-8feb-75fbc9d4249b.png)
