### ISSUE TITLE
Add support layers where needed

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#45]
Support layers can provide additional control for intermediate masters, between sources. The main problem this solves is contrast at intermediate weights. Strokes are meant to appear uniform in thickness from Light to Medium weights but require a lot of modulation at bolder weights to preserve counters. This means that, if simply interpolated between Light and ExtraBold masters, several more-complex glyph shapes suffer from too much stroke contrast at regular and medium weights.

I've tested this in the /w at `wght=500` for Casual and Linear masters. It builds and works well! This image shows the font with this support layer for the /w only:

![image](https://user-images.githubusercontent.com/7355414/60387460-98613480-9a71-11e9-9222-8d8ec88ff572.png)

![image](https://user-images.githubusercontent.com/7355414/60387469-af078b80-9a71-11e9-8e71-24cb7b5e9b76.png)

![image](https://user-images.githubusercontent.com/7355414/60387494-1ae9f400-9a72-11e9-86c6-f610791b8829.png)

![image](https://user-images.githubusercontent.com/7355414/60387501-2f2df100-9a72-11e9-8f9f-0a8dc058b6e8.png)

However, there are other glyphs which will also benefit from support layers. This issue will be a list of them.

- [ ] /w in Casual Slanted and Linear Slanted masters
- [ ] /w.italic
- [ ] /m
- [ ] /s
- [ ] /e
- [ ] /a
- [ ] /z
- [ ] /W
- [ ] /M
- [ ] /eight

### How will they work with accents? Will I need to build source glyphs for all diacritics, e.g. /aacute, /zcaron, etc, in order to bring these fixes into those glyphs? If so, is it worth the filesize, maintenance burden, and overall complexity?

**Comment by arrowtype** [comment]
Update: After some earlier tests and subsequent work to expand the font and go through mastering, I've determined that this would add significant complexity for insignificant benefit. I'm closing this.
