### ISSUE TITLE
Example @font-face rules from example code not working

### ISSUE THREAD

**Issue by brgrz** [arrowtype/recursive#452]
**Problem description**

When downloading the entire package folder `Recursive_Web\woff2_variable_subsets` contains the `fonts.css` file which guides user to `@font-face` rules which one is supposed to use. At least that's how I understand it. I tried and use those rules but browsers fail to fetch the font - they do not seem to try and fetch at all since no error occurs the font just isn't fetched.

It appears browsers have issues with the `unicode-range` lines

**Expected behavior**

Are these rules/snippets supposed to work? If so, how come they don't work at the moment in any major browser?

Removing the unicode-range line solves the problem and font loads normally.

example rule with issue

```
/* unicode latin A extended */
@font-face {
  font-family: 'Recursive';
  font-style: oblique 0deg 15deg;
  font-weight: 300 1000;
  font-display: swap;
  src: url('/fonts/Recursive_VF_1.077--subset_range_latin_ext.woff2') format('woff2');
//  unicode-range: U+0100-017F; // commenting this out solves the issue e.g. browser loads the font
}

```

**To Reproduce**

Copy/paste snippets (@font-face rules) from `fonts.css` in `Recursive_web/woff2_variable_subsets`

**Environment (please complete the following information):**
- OS: Windows 10 latest
- Browser: Chrome 89
- Fonts: v.1.0.77

**Comment by arrowtype** [comment]
Thanks for taking time to post the issue, @brgrz!

Unicode Range should work on Chrome 89, and is supported on about 97.81% of browsers ([Source: CanIUse](https://caniuse.com/font-unicode-range)). But, if you need to support IE8, you may want to look into fallback strategies.

Still, I tested it on Windows with Chrome, and had a similar problem.

I think the issue may have been the file paths I had in the CSS. I added an example `index.html` to the `woff2_variable_subsets` folder, and this helped me make paths that work better on my test in Windows. I also made specific subsets to includes ranges for Vietnamese, and for everything in Recursive beyond the specific subsets (https://github.com/arrowtype/recursive/commit/cada0c626b2df07c817cd3931f613500fc869ef9). So, if your webpage includes characters beyond basic Latin that are in the full Recursive font, they should now work.

If you have a moment, could you please test the [updated release v1.077](https://github.com/arrowtype/recursive/releases/tag/v1.077), and let me know whether it’s working for you with unicode-range?

**Comment by arrowtype** [comment]
Shoot, I see one issue in that code ... updating it again to fix.

**Comment by arrowtype** [comment]
Okay, _NOW_ please try it when you can. 😅

**Comment by brgrz** [comment]
I did and the Latin ext does not work for me. Browser won't fetch the file (no request being made). The basic English one is working though.

**Comment by brgrz** [comment]
What I'm trying to achieve here is get the latin extended set because of special European characters. But I don't want to use the entire 650 KB set.

**Comment by arrowtype** [comment]
Darn, I should have tested my update in the Network tab of Dev Tools. 🤦‍♂️ For now, the quick fix is to remove the final block for "remaining subsets" from the fonts.css, and the other subsets will load as needed. 

![image](https://user-images.githubusercontent.com/45946693/111799240-37127200-88a1-11eb-8dc7-0ce556d27ef6.png)

![image](https://user-images.githubusercontent.com/45946693/111799212-2feb6400-88a1-11eb-8e60-2052bf934c42.png)

This afternoon, I’ll try to revise my build script to properly subset that "remaining unicodes" font, and make sure that its `unicode-range` CSS value only includes relevant unicodes that aren’t in the other subsets. My guess is, unicodes snuck in there from the other subsets, so the browser is just downloading that whole font outright. I’ll update this issue when I’ve refined and tested that.

Just to make sure we’re on the same page for how this works, though, these subsets load like this:

- The `english_basic` subset will load on almost any webpage, as it contains characters `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z 0 1 2 3 4 5 6 7 8 9 _ - ( ) [ ] { } # % \' " ‘ ’ “ ” * . , : ; ! ? / \ | @ & • + = < > ← ↑ → ↓ $ ^ ~ ©`
- The `latin_1_punc` subset will load if a page includes something in here: `ª º ¹ ² ³ ¼ ½ ¾ « » ¡ ¿ ¦ § ¶ · ± ¬ ↔ ¢ £ ¤ ¥ ´ ¯ ¨ ¸ ® ° ↕ ↖ ↗ ↘ ↙ µ`
- `latin_ext` will load if a page includes something in here:  `Ā Ă Ą Ć Ĉ Ċ Č Ď Ē Ĕ Ė Ę Ě Ĝ Ğ Ġ Ģ Ĥ Ĩ Ī Ĭ Į İ Ĵ Ķ Ĺ Ļ Ľ Ń Ņ Ň Ō Ŏ Ő Ŕ Ŗ Ř Ś Ŝ Ş Š Ţ Ť Ũ Ū Ŭ Ů Ű Ų Ŵ Ŷ Ÿ Ź Ż Ž Đ Ħ Ĳ Ŀ Ł Ŋ Œ Ŧ ā ă ą ć ĉ ċ č ď ē ĕ ė ę ě ĝ ğ ġ ģ ĥ ĩ ī ĭ į ĵ ķ ĺ ļ ľ ń ņ ň ō ŏ ő ŕ ŗ ř ś ŝ ş š ţ ť ũ ū ŭ ů ű ų ŵ ŷ ź ż ž đ ħ ı ĳ ĸ ŀ ł ŉ ŋ œ ŧ`
- etc

> Is that the minimum we can get?

There are ways to optimize this further, but wouldn’t make as much sense in the general releases:
1. If you only need part of the stylistic range (e.g. Monospace `0`, Casual `1`, Weight `300-800`), variable fonts can be “instanced” or “partially instanced” with the [FontTools Instancer](https://fonttools.readthedocs.io/en/latest/varLib/instancer.html). You can do it locally on the command line or in a Python script. Alternatively, the [Google Fonts API allows you to do this by requesting a special URL](https://css-tricks.com/getting-the-most-out-of-variable-fonts-on-google-fonts/), and the “Get Recursive” section of the [Recursive Minisite](https://recursive.design/) has a UI to help construct these URLs.
2. You can tailor subsets and CSS `unicode-range` to your specific use case. E.g. if you are specifically writing in only English & Spanish, you could make a subset for this, using the FontTools Subsetter or by adapting [my Recursive subsetting script](https://github.com/arrowtype/recursive/blob/4d6fb032b722968cdc12b7d6b7da1994e10e4f70/src/build-scripts/make-release/make-variable-woff2s_and_subsets.sh) if you want.
3. You can combine instancing and subsetting. For instance, if you use Casual ExtraBlack on just your first name, you could make a font file that just includes characters `M a r k o` in the single style or style range you want for that. The website https://sia.codes/ does something like this for `Sia`.

**Comment by arrowtype** [comment]
One note on subsetting and `unicode-range`: a drawback is that kerning doesn’t work between different font files. So, for instance, it would be a bad idea to put uppercase & lowercase into separate files, because you’d lose all kerning between pairs like `To` and `Ye`, etc etc.

**Comment by arrowtype** [comment]
Okay, I think I fixed the issue. It was actually a pretty simple typo causing the problem. 😅

I also improved the example HTML.

https://github.com/arrowtype/recursive/releases/tag/v1.077

If you can, please check it agains and let me know if that works on your end, @brgrz. (I did test it the Network tab downloads this time around, though, and I _think_ it should be working.)

**Comment by arrowtype** [comment]
I’ll close this, as I think it’s been resolved, but @brgrz, if you are able to try it out and you’re still experiencing any issues, please feel free to let me know and reopen it!

**Comment by arrowtype** [comment]
(By the way, thanks for helping make Recursive better, @brgrz!)

**Comment by brgrz** [comment]
Hey @arrowtype I can now confirm that this is working as expected with 1.0.78 release.

For future reference what I did:
- downloaded the entire package,
- copied the contents of Recursive_Web\woff2_variable_subsets into my fonts/recursive folder,
- referenced fonts.css into my index.html (I did not change anything but someone might want to change their paths if it doesn't load right),
- changed the referenced font name from "Recursive" to "RecVar" (which is used in fonts.css).

Browser now correctly fetches just the two files it needs, the basic subset and the latin extended subset since that are the characters my site uses. Previously because nothing else worked I had to reference the entire subset coming at 700kb.

Now with the two mentioned files it comes at around 350kb. 50% savings...still, not small but I guess it'll have to do. 👍

**Comment by subnut** [comment]
### OFF-TOPIC:
Hey @arrowtype, what colorscheme are you using in this picture? I _really_ like it -
![](https://user-images.githubusercontent.com/45946693/111799240-37127200-88a1-11eb-8dc7-0ce556d27ef6.png)
Also, which editor is it? VS Code?

**Comment by arrowtype** [comment]
@subnut thanks! It's a theme I made for myself, starting from Night Owl, indeed in VS Code.

GitHub.com/arrowtype/recursive-theme

**Comment by subnut** [comment]
I love it!
Also, I am guessing the font you use is `Rec Mono Duotone`. Am I right? Or is it a custom version?

**Comment by arrowtype** [comment]
Correct!
