### ISSUE TITLE
GF onboarding

### ISSUE THREAD

**Issue by RosaWagner** [arrowtype/recursive#453]
Is this the right file : `Recursive_Desktop > Recursive_VF_1.077.ttf` ?

- [x] Is it somehow possible to rename the directory `ArrowType-Recursive-1.077` something like `last release`, or i don't know, but a name that won't change with the next update and where we can find the fonts to onboard. It's to link the directory with the packager.
- [x] you also need the github link in the OFL.txt instead of your contact info.
- [ ] make STAT fallbacks correct according to axis registry (for what is possible) or open issue to update axis registry

**Comment by RosaWagner** [comment]
you also need the github link in the OFL.txt instead of your contact info.

**Comment by RosaWagner** [comment]
## Fontbakery report

Fontbakery version: 0.7.34

<details>
<summary><b>[14] Recursive_VF_1.077.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/canonical_filename](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename)
<pre>--- Rationale ---

A font&#x27;s filename must be composed in the following manner:
&lt;familyname&gt;-&lt;stylename&gt;.ttf

- Nunito-Regular.ttf,
- Oswald-BoldItalic.ttf

Variable fonts must list the axis tags in alphabetical order in square brackets
and separated by commas:

- Roboto[wdth,wght].ttf
- Familyname-Italic[wght].ttf


</pre>

* 🔥 **FAIL** font filename "/Users/rosalie/Downloads/recursive-main/fonts/ArrowType-Recursive-1.077/Recursive_Desktop/Recursive_VF_1.077.ttf" is invalid. It must not contain underscore characters! [code: invalid-char]

</details>
<details>
<summary>🔥 <b>FAIL:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
<pre>--- Rationale ---

A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry
of the name table.

The source of truth for this check is the licensing text found on the NameID 13
entry (LICENSE DESCRIPTION).

The string snippets used for detecting licensing terms are:
- &quot;This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is available with a FAQ at: https://scripts.sil.org/OFL&quot;
- &quot;Licensed under the Apache License, Version 2.0&quot;
- &quot;Licensed under the Ubuntu Font Licence 1.0.&quot;


Currently accepted licenses are Apache or Open Font License.
For a small set of legacy families the Ubuntu Font License may be acceptable as
well.

When in doubt, please choose OFL for new font projects.


</pre>

* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache: 'https://www.apache.org/licenses/LICENSE-2.0' or Open Font License: 'https://scripts.sil.org/OFL'
For a small set of legacy families the Ubuntu Font License 'https://www.ubuntu.com/legal/terms-and-policies/font-licence' may be acceptable as well.
When in doubt, please choose OFL for new font projects. [code: no-license-found]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.
 [code: http]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check name table: TYPOGRAPHIC_SUBFAMILY_NAME entries.</summary>

* [com.google.fonts/check/name/typographicsubfamilyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/typographicsubfamilyname)

* 🔥 **FAIL** TYPOGRAPHIC_SUBFAMILY_NAME for Win "Sans Linear Light" is incorrect. It must be "Light". [code: bad-typo-win]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Following instances are not supported: 
	- Mono Linear Light
	- Mono Linear Light Italic
	- Mono Casual Light
	- Mono Casual Light Italic
	- Mono Linear
	- Mono Linear Italic
	- Mono Casual
	- Mono Casual Italic
	- Mono Linear Medium
	- Mono Linear Medium Italic
	- Mono Casual Medium
	- Mono Casual Medium Italic
	- Mono Linear SemiBold
	- Mono Linear SemiBold Italic
	- Mono Casual SemiBold
	- Mono Casual SemiBold Italic
	- Mono Linear Bold
	- Mono Linear Bold Italic
	- Mono Casual Bold
	- Mono Casual Bold Italic
	- Mono Linear ExtraBold
	- Mono Linear ExtraBold Italic
	- Mono Casual ExtraBold
	- Mono Casual ExtraBold Italic
	- Mono Linear Black
	- Mono Linear Black Italic
	- Mono Casual Black
	- Mono Casual Black Italic
	- Mono Linear ExtraBlack
	- Mono Linear ExtraBlack Italic
	- Mono Casual ExtraBlack
	- Mono Casual ExtraBlack Italic
	- Sans Linear Light
	- Sans Linear Light Italic
	- Sans Casual Light
	- Sans Casual Light Italic
	- Sans Linear
	- Sans Linear Italic
	- Sans Casual
	- Sans Casual Italic
	- Sans Linear Medium
	- Sans Linear Medium Italic
	- Sans Casual Medium
	- Sans Casual Medium Italic
	- Sans Linear SemiBold
	- Sans Linear SemiBold Italic
	- Sans Casual SemiBold
	- Sans Casual SemiBold Italic
	- Sans Linear Bold
	- Sans Linear Bold Italic
	- Sans Casual Bold
	- Sans Casual Bold Italic
	- Sans Linear ExtraBold
	- Sans Linear ExtraBold Italic
	- Sans Casual ExtraBold
	- Sans Casual ExtraBold Italic
	- Sans Linear Black
	- Sans Linear Black Italic
	- Sans Casual Black
	- Sans Casual Black Italic
	- Sans Linear ExtraBlack
	- Sans Linear ExtraBlack Italic
	- Sans Casual ExtraBlack
	- Sans Casual ExtraBlack Italic

Further info can be found in our spec https://github.com/googlefonts/gf-docs/tree/master/Spec#fvar-instances [code: bad-instance-names]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Ensure VFs do not contain slnt or ital axes. </summary>

* [com.google.fonts/check/varfont/unsupported_axes](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont/unsupported_axes)
<pre>--- Rationale ---

The &#x27;ital&#x27; and &#x27;slnt&#x27; axes are not supported yet in Google Chrome.

For the time being, we need to ensure that VFs do not contain either of these
axes. Once browser support is better, we can deprecate this check.

For more info regarding browser support, see:
https://arrowtype.github.io/vf-slnt-test/


</pre>

* 🔥 **FAIL** The "slnt" axis is not yet well supported on Google Chrome. [code: unsupported-slnt]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Validate STAT particle names and values match the fallback names in GFAxisRegistry. </summary>

* [com.google.fonts/check/STAT/gf-axisregistry](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/gf-axisregistry)
<pre>--- Rationale ---

Check that particle names and values on STAT table match the fallback names in
each axis entry at the Google Fonts Axis Registry, available at
https://github.com/google/fonts/tree/master/axisregistry


</pre>

* 🔥 **FAIL** On the font variation axis 'MONO', the name 'Sans' is not among the expected ones (Proportional, Monospace) according to the Google Fonts Axis Registry. [code: invalid-name]
* 🔥 **FAIL** On the font variation axis 'MONO', the name 'Mono' is not among the expected ones (Proportional, Monospace) according to the Google Fonts Axis Registry. [code: invalid-name]
* 🔥 **FAIL** On the font variation axis 'wght', the name 'ExtraBlack' is not among the expected ones (Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Black) according to the Google Fonts Axis Registry. [code: invalid-name]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
<pre>--- Rationale ---

A font&#x27;s winAscent and winDescent values should be greater than the head
table&#x27;s yMax, abs(yMin) values. If they are less than these values, clipping
can occur on Windows platforms
(https://github.com/RedHatBrand/Overpass/issues/33).

If the font includes tall/deep writing systems such as Arabic or Devanagari,
the winAscent and winDescent can be greater than the yMax and abs(yMin) to
accommodate vowel marks.

When the win Metrics are significantly greater than the upm, the linespacing
can appear too loose. To counteract this, enabling the OS/2 fsSelection bit 7
(Use_Typo_Metrics), will force Windows to use the OS/2 typo values instead.
This means the font developer can control the linespacing with the typo values,
whilst avoiding clipping by setting the win values to values greater than the
yMax and abs(yMin).


</pre>

* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 330, but got 271 instead. [code: descent]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Are there unwanted tables?</summary>

* [com.google.fonts/check/unwanted_tables](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/unwanted_tables)
<pre>--- Rationale ---

Some font editors store source data in their own SFNT tables, and these can
sometimes sneak into final release files, which should only have OpenType spec
tables.


</pre>

* 🔥 **FAIL** The following unwanted font tables were found:
Table: MVAR
Reason: Produces a bug in DirectWrite which causes https://bugzilla.mozilla.org/show_bug.cgi?id=1492477, https://github.com/google/fonts/issues/2085

They can be removed with the gftools fix-unwanted-tables script.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check correctness of STAT table strings </summary>

* [com.google.fonts/check/STAT_strings](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/STAT_strings)
<pre>--- Rationale ---

On the STAT table, the &quot;Italic&quot; keyword must not be used on AxisValues for
variation axes other than &#x27;ital&#x27;.


</pre>

* 🔥 **FAIL** The following AxisValue entries on the STAT table should not contain "Italic":
 ['nameID 414: Italic'] [code: bad-italic]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i.italic
	- i.italic + i.italic

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Combined length of family and style must not exceed 27 characters.</summary>

* [com.google.fonts/check/name/family_and_style_max_length](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/family_and_style_max_length)
<pre>--- Rationale ---

According to a GlyphsApp tutorial [1], in order to make sure all versions of
Windows recognize it as a valid font file, we must make sure that the
concatenated length of the familyname (NameID.FONT_FAMILY_NAME) and style
(NameID.FONT_SUBFAMILY_NAME) strings in the name table do not exceed 20
characters.

After discussing the problem in more detail at `FontBakery issue #2179 [2] we
decided that allowing up to 27 chars would still be on the safe side, though.

[1]
https://glyphsapp.com/tutorials/multiple-masters-part-3-setting-up-instances
[2] https://github.com/googlefonts/fontbakery/issues/2179


</pre>

* ⚠ **WARN** The combined length of family and style exceeds 27 chars in the following 'WINDOWS' entries:
 FONT_FAMILY_NAME = 'Recursive Sans Linear Light' / SUBFAMILY_NAME = 'Regular'

Please take a look at the conversation at https://github.com/googlefonts/fontbakery/issues/2179 in order to understand the reasoning behind these name table records max-length criteria. [code: too-long]

</details>
<details>
<summary>⚠ <b>WARN:</b> Glyph names are all valid?</summary>

* [com.google.fonts/check/valid_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames)
<pre>--- Rationale ---

Microsoft&#x27;s recommendations for OpenType Fonts states the following:

&#x27;NOTE: The PostScript glyph name must be no longer than 31 characters, include
only uppercase or lowercase English letters, European digits, the period or the
underscore, i.e. from the set [A-Za-z0-9_.] and should start with a letter,
except the special glyph name &quot;.notdef&quot; which starts with a period.&#x27;

https://docs.microsoft.com/en-us/typography/opentype/spec/recom#post-table


In practice, though, particularly in modern environments, glyph names can be as
long as 63 characters.
According to the &quot;Adobe Glyph List Specification&quot; available at:

https://github.com/adobe-type-tools/agl-specification


</pre>

* ⚠ **WARN** The following glyph names may be too long for some legacy systems which may expect a maximum 31-char length limit:
hyphen_space_brktleft_space_brktright.code and hyphen_space_brktleft_x_brktright.code [code: legacy-long-names]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---

Mark characters should be in the GDEF mark glyph class.


</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 U+0324 and U+0335 [code: mark-chars]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check GDEF mark glyph class doesn't have characters that are not marks)</summary>

* [com.google.fonts/check/gdef_non_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_non_mark_chars)
<pre>--- Rationale ---

Glyphs in the GDEF mark glyph class become non-spacing and may be repositioned
if they have mark anchors.
Only combining mark glyphs should be in that class. Any non-mark glyph must not
be in that class, in particular spacing glyphs.


</pre>

* ⚠ **WARN** The following non-mark characters should not be in the GDEF mark glyph class:
	 U+02CC [code: non-mark-chars]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 9 | 5 | 91 | 8 | 82 | 0 |
| 0% | 5% | 3% | 47% | 4% | 42% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by RosaWagner** [comment]
Otherwise, the change of v-metric doesn't impact linespacing on the web, so it is not a problem. [diff.zip](https://github.com/arrowtype/recursive/files/6150358/diff.zip)

**Comment by arrowtype** [comment]
Great, thanks for pointing out the needed steps for the update!

I'm not under a current contract, but I could look at a PR for these items, or I could do onboarding myself, if Google Fonts / @davelab6 can sponsor that.

> the change of v-metric doesn't impact linespacing on the web, so it is not a problem.

It may not be a problem for fonts served via CSS, but obviously, it's a problem for any Mac users who download the fonts with the prominent "Download Fonts" button on Google Fonts.

**Comment by arrowtype** [comment]
Also, I'm Perry unsure whether limiting the fvar table to just weight names makes sense in this particular project, even that is the typical approach to VFs. This has instances along the Mono, Casual, and Slant axes that shouldn't be excluded from the font.

**Comment by RosaWagner** [comment]
> It may not be a problem for fonts served via CSS, but obviously, it's a problem for any Mac users who download the fonts with the prominent "Download Fonts" button on Google Fonts.

We'll update the description to warn users. 

> I'm not under a current contract, but I could look at a PR for these items, or I could do onboarding myself, if Google Fonts can sponsor that.

Okay, I'll wait for his confirmation, or bring it up to next meeting.

> Also, I'm pretty unsure whether limiting the fvar table to just weight names makes sense in this particular project, even that is the typical approach to VFs. This has instances along the Mono, Casual, and Slant axes that shouldn't be excluded from the font.

They gonna be accessible through the stat table. Although since the font is already onboarded with these instances, maybe we can't get them out. I'll ask for that too.

**Comment by arrowtype** [comment]
Okay, thanks for your responsiveness and help, Rosalie! I really appreciate your time in this.

I’ve done the following quick tasks:

- Added the github link in the OFL.txt instead of my contact info.
- Added a specific, constant path for the latest release at https://github.com/arrowtype/recursive/tree/main/fonts/recursive_for_googlefonts

For the other requested tasks...

> They gonna be accessible through the stat table. Although since the font is already onboarded with these instances, maybe we can't get them out. I'll ask for that too.

I’ll try to ask about this on Friday. To point out what we both already know, no major software gives access to `STAT` info, so far. So, for most users, removing those `fvar` instances would effective be hiding 75%+ of the font. At least until all statics are included in the GF download (https://github.com/google/fonts/issues/3104), I would really hesitate to remove the fvar instances. I _could_ be misunderstanding this requirement, though... for instance, maybe there is the concern that keeping those `fvar` instances would clash with static fonts, depending how they are being generated. If there is some documentation around this issue, I’d be interested in reading further.

> We'll update the description to warn users.

If there are no regressions in Recursive from before, I would hope that we might be able to update the font to fix the existing (pretty serious) user issues, rather than relying on people to read a warning in the description. My worry is that probably every day, some number of people are downloading old versions of Recursive that will break badly in print projects. This makes both myself and Google Fonts look pretty bad.

**Comment by arrowtype** [comment]
This update was merged: https://github.com/google/fonts/pull/3279
