### ISSUE TITLE
Download zip README has links to master branch, lacks filenames

### ISSUE THREAD

**Issue by davelab6** [arrowtype/recursive#458]
>> `For design & usage recommendations, please see the project README at https://github.com/arrowtype/recursive/blob/master/README.`

Should be

> `For design & usage recommendations, please see the project README at https://github.com/arrowtype/recursive/blob/main/README.md`

(If you want to be fancy, you can run a URL checker on your files at build time; there's some build into fontbakery, see eg https://github.com/googlefonts/fontbakery/issues/2550 :)

**Comment by arrowtype** [comment]
Corrected at https://github.com/arrowtype/recursive/releases/tag/v1.078

**Comment by arrowtype** [comment]
Thanks, Dave! Glad you caught that.

The URL response check is a cool idea, and a very good idea for Google Fonts descriptions. I may have to test that if I run into similar issues some more!
