### ISSUE TITLE
List of all ligatures? 

### ISSUE THREAD

**Issue by smsegal** [arrowtype/recursive#459]
This is kind of a silly request, but I'd love a list of all of the coding ligatures present in the font.

 I use https://github.com/mickeynp/ligature.el to get ligatures in emacs but it needs an explicit list of the characters to be ligaturized due to the way emacs idiosyncratic font-rendering works (to be fair, everything about emacs is idiosyncratic). 

I tried searching through the repo but I'm pretty unfamiliar with how fonts are created behind the scenes and didn't see anything. Thanks!

**Comment by arrowtype** [comment]
Interesting question! I don’t think I had a list anywhere obvious...

<details>
<summary><b>📃 A list of code ligatures currently in Recursive</b> (Click to expand)</summary>

```
- [x]
- [ ]
####
<!--
'''
---
=<<
-->
>>=
+++
<*>
===
|||
=/=
://
<<<
-<<
"""
<<-
>>>
<$>
<|>
***
<=>
&&&
!==
///
###
<+>
<<=
<<~
>>-
=>
==
<>
++
<<
*/
*=
>-
&&
?.
|>
>>
<|
||
|=
##
<*
//
${
−=
??
=~
\b
!~
__
-<
<-
\r
?:
/*
<=
!=
**
!!
->
\t
/=
\v
\n
+=
>=
::
--
```

There is also ```, but that breaks the markdown code block to include.

I may eventually remove the `\r \v \n \t`, because I’m unsure whether these are actually useful to change into ligatures...

</details>


There is probably a better/simpler way to find this, but partly for reference for myself later, I copied my ligature names from the `.calt` feature file, then opened one of the font source UFOs in RoboFont and looped through to find the characters.

<details>
<summary><b>Python script</b> (Click to expand)</summary>

```py
"""
    RoboFont script to go through a source UFO, find glyphs with ".code" suffix, and print their base glyphs as normal characters
"""

f = CurrentFont()

# copied from .calt feature code 
codeLigs = "hyphen_space_bracketleft_x_bracketright hyphen_space_bracketleft_space_bracketright numbersign_numbersign_numbersign_numbersign less_exclam_hyphen_hyphen quotesingle_quotesingle_quotesingle hyphen_hyphen_hyphen equal_less_less hyphen_hyphen_greater greater_greater_equal plus_plus_plus less_asterisk_greater equal_equal_equal bar_bar_bar equal_slash_equal colon_slash_slash less_less_less hyphen_less_less quotedbl_quotedbl_quotedbl less_less_hyphen greater_greater_greater less_dollar_greater less_bar_greater asterisk_asterisk_asterisk less_equal_greater ampersand_ampersand_ampersand exclam_equal_equal slash_slash_slash numbersign_numbersign_numbersign less_plus_greater less_less_equal grave_grave_grave less_less_asciitilde greater_greater_hyphen equal_greater equal_equal less_greater plus_plus less_less asterisk_slash asterisk_equal greater_hyphen ampersand_ampersand question_period bar_greater greater_greater less_bar bar_bar bar_equal numbersign_numbersign less_asterisk slash_slash dollar_braceleft minus_equal question_question equal_asciitilde backslash_b exclam_asciitilde underscore_underscore hyphen_less less_hyphen backslash_r question_colon slash_asterisk less_equal exclam_equal asterisk_asterisk exclam_exclam hyphen_greater backslash_t slash_equal backslash_v backslash_n plus_equal greater_equal colon_colon hyphen_hyphen".split(" ")


for lig in codeLigs:
    chars = lig.split("_")
    
    if len(chars) > 1:
        # print()
        # print(lig)
    
        print("".join([chr(f[name].unicodes[0]) for name in chars]))
       
```

</details>

**Comment by arrowtype** [comment]
To find this on your own, I think Font Forge (which is open source) may allow you to view glyphs that are activated by a given font feature, though I’m not totally sure of that. It would also be possible to write a script with FontTools TTFont, but this would probably get a bit tricky and require some expertise plus experimentation.

**Comment by arrowtype** [comment]
Please let me know if this answers your question! And if so, feel free to close the issue.

Best of luck!

**Comment by smsegal** [comment]
Exactly what I was looking for, thanks! Font Forge is added to my list of interesting tech outside my wheelhouse to check out :)

**Comment by matj1** [comment]
> There is also ```, but that breaks the markdown code block to include.

If a code block is marked by ‹x› backticks, it can contain a sequence of ‹x›−1 backticks for every ‹x› from 3.

`````
````
```
````
`````
shows as
````
```
````
.
