### ISSUE TITLE
Should italic alternates use slant axis + stylistic sets, or have their own "italic" axis?

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#46]
Most lowercase glyphs in Recursive have `.italic` alternates, which swap in for roman forms in Italic named instances. 

However, a user also needs the ability to assert roman forms in slanted instances, and italic forms in upright instances. Partly, this is necessary to give users access to the full range of design possibilities in the family, and partly, this is necessary to allow for smooth animations – for instance, a link that slants when hovered should _not_ swap italic forms during the transition.

There are two technical ways to achieve this:

## 1. Tying the glyph substitution rules to the Slant axis, then giving stylistic sets that can assert italic or roman forms.

Pros: 
- One less axis, which may make it simpler for users to understand the font, and easier for users to get what they generally want in the slant axis, probably 90% of the time.

Cons: 
- Many design tools (including Adobe software) don't make it easy to find and control stylistic sets, so most users will completely miss this option. At minimum, it will require the user to explore two separate controls to access the italic aspect of the font's designspace.
- This may lead to more cases of broken animations, and users not realizing they can have upright italics and sloped romans. 
- From a production standpoint, it requires duplicating all default glyphs (including diacritics) to `.roman` glyphs, which adds a ton of extra glyphs to the sources, for no clear gain.

## 2. Adding an Italic axis which only controls roman/italic letterforms

Pros: 
- Allows full control of designspace on more UIs (if a user can control variation axes, they can control this, even stylistic sets aren't surfaced in a particular software context). 
- Makes it obvious that Slant and Italic axes can be used separately. 
- Named instances still allow users to easily select "Italic" style (slanted and italicized) if that's what they want. 
- Reduces the complexity of production.

Cons: 
- Potentially, the typeface will seem harder to understand for newcomers, because interfaces will surface more complexity up-front.
- The "Italic" axis would be different from other axes, in that by its nature, it won't really allow for smooth transitions between levels (short of a "Higher-Order Interpolation" approach, which is way out of scope for the current project).

![recursive axes 2019-06-29 at 16 22 07](https://user-images.githubusercontent.com/7355414/60389107-1a5d5780-9a8a-11e9-9cab-77714239c49c.gif)

## Is there a filesize difference? Needs testing.

- [ ] To test this, I need to add the `.roman` alternates to fonts in an example designspace, then generate that version.

**Comment by arrowtype** [comment]
I went with the `ital` axis. :)
