### ISSUE TITLE
Enabling ligatures have no effect in vscode

### ISSUE THREAD

**Issue by milandosljak** [arrowtype/recursive#461]
No feature have effect except **dlig**

I tested out lastest ten versions of Rec Mono, then go back even more and find out that this is the case from version **1.053**
Before that version, all ligatures worked as expected

For Rec Mono installed from desktop separate statics, ligatures work tho

I tested it out only in vscode, and I don't think it's OS related, but anyway
OS: Ubuntu 20.04.2 LTS

I don't know if this is the way it should be, that you get freezed ligatures in Recursive Code, but if you want to enable more features you need to use font from desktop separate statics?

If you need some more info, let me know

And thank you for this great font :)

**Comment by arrowtype** [comment]
Hey @milandosljak, thanks for the kind words, and thanks for filing the issue!

> if you want to enable more features, do you need to use fonts `desktop > separate statics`?

That is one option. There, you can activate `dlig` and any arbitrary font features, as is described here:

https://github.com/arrowtype/recursive#2-standard-recursive-mono-desktop-fonts

The other option, if you want to "freeze in" features, is to use the Rec Mono fonts. You can use the versions included with releases if you like those features, or you can configure your own build with this tool:

https://github.com/arrowtype/recursive-code-config

Let me know if that solves this for you. Cheers!

**Comment by milandosljak** [comment]
@arrowtype, thank you for clarifying and fast reply :)

I somehow missed that part of README, sorry for bothering you then

Unfortunately, **recursive-code-config** is not enough for me right now, because feature which I prefer (**ss04**) is not currently working, so I will stick with older versions or desktop separate statics

I do hope it will be fixed soon, so I can start using Rec Mono with preferred features in other programs too, which doesn't support ligatures tweaks

Thank you for your time, you can close this issue now

Cheers!
