### ISSUE TITLE
Recursive in use

### ISSUE THREAD

**Issue by raphaelbastide** [arrowtype/recursive#469]
Hi, I have made a book with my father, It’s in french, made with HTML / CSS, Inkscape for the illustrations, and zero proprietary software. It’s about pregnancy and osteopathy, and it is all set in Recursive <3.
Video https://peertube.social/videos/watch/8ebc7a70-6ddd-4887-9e5f-00e479932061
Thank you so very much for your work, I am happy with the result and Recursive was a very pleasant ingredient to work with.

**Comment by arrowtype** [comment]
Hi Raphaël, this is gorgeous work! Thank you so much for taking the time to share it. It makes my day to see how well you were able to use it for this project. It's very cool you were able to do it with all open software, too!

Would you be alright if I re-shared this video to my social media? If so, do you have a Twitter and/or Instagram handle I could credit?

**Comment by raphaelbastide** [comment]
Glad you like it! It is a bit early to share the video it, it is self-published and the official release will be in September. However, if you agree to share the website osteofolio.com in September, that would be perfect for us!

**Comment by arrowtype** [comment]
Okay, that sounds good – thanks again, and best of luck on the release!

**Comment by raphaelbastide** [comment]
We’ll release it tomorrow! You can have a look at https://osteofolio.com/

**Comment by arrowtype** [comment]
This looks so fantastic, @raphaelbastide! Congrats on the release.

Would you be willing to send some high-ish resolution photos of the book, so I could make a page on [Fonts In Use](https://fontsinuse.com/typefaces/112749/recursive)?

**Comment by raphaelbastide** [comment]
Thank you! [Here](https://osteofolio.com/grossesse/assets/osteofolio-presse.zip) you can find pictures of the book. You are free to zoom / crop if needed.

**Comment by raphaelbastide** [comment]
Could you send me an address, we would like to offer you a copy of the book, so you can have an excuse to practice your French or make a child. info at osteofolio ✿ com

**Comment by arrowtype** [comment]
Ha, thank you! I’ll send my address your way. I do love French! Undecided on whether to make a child, but there’s probably a 60/40 chance.

**Comment by ng-hai** [comment]
Would love to have a pinned issue in GitHub about **Recursive in use** to inspire product design and development 😄
