### ISSUE TITLE
Closing backtick in code editor not appearing correctly with Static font variant

### ISSUE THREAD

**Issue by avidworks** [arrowtype/recursive#470]
**Problem description**
When using the static fonts (i.e. Recursive Mono Linear Static), closing backticks in languages such as Javascript are appearing on top of the last letter as opposed to after it -- almost like it's treating it as a special character/letter. This happens from A-Z and whether it's lower or uppercase. When there is a number or punctuation at the end of the string, the backtick appears as normal. This does NOT happen with the Code variants (i.e. Rec Mono Linear) -- Those versions appear to be working fine.

I'm not sure if this is isolated to VSCode as it didn't seem to do it in Word, but I wanted to put in a bug report in case it's something that needs to be addressed.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/68607953/126827162-8f8e62c9-2081-4539-a76b-a0bb362bbfaf.jpg)

**Environment (please complete the following information):**
- OS: Windows 10
- Program: VSCode
- Fonts: Static Options (both Mono and Sans)

**Comment by arrowtype** [comment]
Thanks for taking the time to submit the issue, and sorry for that inconvenience!

I think this is solved with https://github.com/arrowtype/recursive/releases/tag/v1.078.

Can you please install that release, and let me know whether you are still experiencing the issue?

Also, can I ask when/where you downloaded the version you do have? Wondering if that release is still floating around somewhere...

Thanks!

**Comment by avidworks** [comment]
Yep, that release fixed it. I guess I should've checked here for the latest version -- The recursive.design website still links to v1.077 when you click "Get Recursive" in the upper right corner and then click "Download".

Thanks for the quick reply, love the font!

**Comment by arrowtype** [comment]
> The recursive.design website still links to v1.077 when you click "Get Recursive"

Ohhh crap, I am sorry about that – thank you for the heads up! That's embarrassing, and I will fix it now. Glad the new release solved the issue for you!
