### ISSUE TITLE
v1.079 Interpolation Issues - 0025 percent & 2030 perthousand

### ISSUE THREAD

**Issue by kenmcd** [arrowtype/recursive#478]
v1.079 Interpolation Issues - 0020 percent & 2030 perthousand
There appears to be an issue with element order in the Black master.

Here is both while varying the Weight axis.
![0025-percent-2030-perthousand](https://user-images.githubusercontent.com/844920/133155022-94e26aae-e89a-4d9c-82bb-f1a452d3331d.gif)

This is just 0025 percent (2030 perthousand is similar).
![0025-percent](https://user-images.githubusercontent.com/844920/133155561-3776bae4-fe58-48d1-87d1-6694d305cedd.gif)

**Comment by arrowtype** [comment]
Thanks for noticing and reporting! This is working exactly as intended, though – to make these glyphs as dark as possible in the Black and Ultra weights, I want those counters to close entirely. They close quickly between 800 and 900, where they are relatively unlikely to be used. The typeface could instead sub between open and closed versions, but the weight axis of Recursive is meant to be possible to animate without any hard jumps.

**Comment by kenmcd** [comment]
So this is by design. 
Closing now. :-)
