### ISSUE TITLE
character request: ∶

### ISSUE THREAD

**Issue by illfygli** [arrowtype/recursive#480]
Thank you for this very useful and beautiful font.
I'm using it as my system UI font, and I noticed on my lock screen clock that the ratio character, `∶`, is missing. 
Is that something that would make sense to add?

**Comment by illfygli** [comment]
The reason why it's used in the clock seems to be that ratio is more vertically centered than colon.
Compare these two:
12∶34 12:34
assuming it's the same in the font you're seeing here. :)
When I look in Gnome's character picker, I can also see that it's higher above the baseline, but looks otherwise identical.

**Comment by arrowtype** [comment]
Thanks!

> Compare these two: X∶:X

Actually, for me on macOS Catalina, the ratio glyph actually looks quite a bit smaller than the colon! Here’s what I see:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/45946693/137053863-adca87ed-0646-4201-a029-81989a2dc00b.png">

But yeah, I think it makes more sense to make this vertically centered with caps and figures. I’ll give it a try!

**Comment by arrowtype** [comment]
Hi @illfygli, if you’d like to try it out, I have the ratio added to the latest font build, here:

https://github.com/arrowtype/recursive/tree/c1a7672a267084871899fca6679b4a33aabbe429/fonts/ArrowType-Recursive-1.080

(I will probably make a proper GitHub Release soon, but I’m working on adding one more thing, first.)
