### ISSUE TITLE
Add basic Greek characters for mathematics

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#489]
I’ve been hired to add some Greek to Recursive, to improve it for mathematics! I’m pretty excited about this. This issue is to help plan and track the work.

Specifically, I need to add the following: `Α Β Γ Δ Λ Μ Ν Θ Π Φ α β γ μ λ ν θ π δ φ`. In full:

- [x] `Α` `0391` | Alpha
- [x] `Β` `0392` | Beta
- [x] `Γ` `0393` | Gamma
- [x] `Δ` `0394` | Delta
- [x] `Λ` `039B` | Lambda
- [x] `Μ` `039C` | Mu
- [x] `Ν` `039D` | Nu
- [x] `Θ` `0398` | Theta
- [x] `Π` `03A0` | Pi
- [x] `Φ` `03A6` | Phi
- [x] `α` `03B1` | alpha
- [x] `β` `03B2` | beta
- [x] `γ` `03B3` | gamma
- [x] `μ` `03BC` | mu (actually, this needed a bit of refinement)
- [x] `λ` `03BB` | lambda
- [x] `ν` `03BD` | nu
- [x] `θ` `03B8` | theta
- [x] `π` `03C0` | pi
- [x] `δ` `03B4` | delta
- [x] `φ` `03C6` | phi (Note: “in mathematical contexts, the loopy glyph is preferred, to contrast with 03D5 φ” – [source](https://www.unicode.org/charts/PDF/U0370.pdf))

The above are now complete in the Mono sources and building well into the variable font (353e189f6e9981544c25d6989985b8c9e47ef44c). However, the following glyphs will need adjustment for proportional widths in the Sans styles:

- [x] Gamma
- [x] Pi
- [x] Phi
- [x] phi

Also

- [x] Check whether these should have specific math Unicodes; if so, make them with both(?). UPDATE: Most of these don’t have math-specific Unicode values. I’ve learned that the `pi` glyph, present in most fonts but without a math-specific Unicode, already corrupts Greek text. This was already the case for Recursive, so at least at first, I won’t do anything too clever to try to split "math specific" fonts from the general release fonts.
- [x] Once these are made and built into final fonts, compare the output with a couple of fonts you trust, e.g. Roboto and Plex, to double-check that unicodes are correct
- [x] static fonts aren’t getting unicodes for Delta and mu ... figure out why not, and fix
  - This seems to be due to a slightly conflict in the [Adobe Glyph List](https://github.com/adobe-type-tools/agl-aglfn/blob/master/glyphlist.txt)... there, names `Delta` and `mu` point to their math-specific Unicodes, rather than their Greek letter Unicodes, whereas the source fonts point to math glyphs with names `increment` and `mu.math`. I probably need to set `uni` style postscript names in the font lib `public.postscriptNames` dict.
  - Update: I probably had to add the `Delta` and `mu` to `setProductionNames()` in `mastering/prep_fonts.py` ... testing it now with that edit.

- [ ] fix slightly-off interpolation in `mu`

**Additional context**

This is 10 letters of the 24 letter Greek alphabet. Sigma has 2 lowercase variants depending on medial/finial position, Kai seems to be a necessary symbol to make, and there are some accents and accented characters to build. And, of course, these would need kerning to work well in text.

So, I may add full Greek support in the future, but this is really just a first pass to better support math. If I can get funding from a client to add the full alphabet, I’d be excited to make it happen!

**Comment by arrowtype** [comment]
Here are some Glyph Construction recipes I’ll use to start.

Can be direct components (probably):

```
?Alpha = A | 0391
?Nu = N | 039d
?alpha = a.italic | 03b1
?nu = v | 03bd
```

Will need drawing (but here are glyphs to start with) – give these a different mark color until they are completed:

```
?Gamma = T | 0393
?Delta = A | 0394
?Theta = O + hyphen@center | 0398
?Lambda = A | 039b
?Pi = H | 03a0
?Phi = O + bar@center | 03a6
?gamma = v + bar@center | 03b3
?delta = o + s@top | 03b4
?theta = zero + hyphen@center | 03b8
?lambda = l + v | 03bb
?phi = o + bar@center | 03c6
```

**Comment by jwortmann** [comment]
I'm excited to read this, and look forward to a version with support for these characters! :rocket:

If I may ask for one request, because many fonts have issues with the following; it would be great if the small greek letter nu will be easy to distinguish from the latin letter v. (I'm mostly interested in the monospace fonts.)

For example in the Consolas font, it looks pretty bad in my opinion and they are very difficult to distinguish, especially on smaller font sizes:
![Consolas](https://user-images.githubusercontent.com/6579999/138577808-5223d53f-a6ad-499c-82ce-5a0325bd1737.png)

One example of a font which, in my opinion, does it very well is [JuliaMono](https://github.com/cormullion/juliamono):
![JuliaMono](https://user-images.githubusercontent.com/6579999/138577955-12618e5c-c8dd-4fd2-bf4d-3448fc183a01.png)

Another example where it looks good would be DejaVu Sans Mono:
![DejaVuSansMono](https://user-images.githubusercontent.com/6579999/138578273-2c10e570-3863-48e5-972a-a291d832ff0c.png)

**Comment by arrowtype** [comment]
Okay, this is all now building well, and I have tested that all characters, across styles, are building with the expected Unicode values. Here are several fonts from Recursive (in white) versus several other popular fonts (in gray):

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/45946693/140185905-4ffa0b15-c364-4d9e-95a2-96b8083404bb.png">
