### ISSUE TITLE
Are OpenType Features working properly in 1.084 Duotone?

### ISSUE THREAD

**Issue by konrad-straube** [arrowtype/recursive#504]
I've been using this font since yesterday and love it, it's the first font where I like the set of coding ligatures (good looking |>, ->, =>, &&, :: and others, no annoying ligatures for <>, <=>, .=, .- etc) and the overall look of the font without ligatures is also great! But I'm confused about the OpenType features, because using it without any extra settings I get the alternative f, l, Z, L, 6 and 9 instead of the default, and none of the OpenType settings seem to be changing anything (both in VS Code and in Sublime Text). I am using v1.084 RecMonoDuotone, but I quickly checked and the situation seems to be the same in RecMonoLinear. I'm attaching a picture of my Sublime settings:
![image](https://user-images.githubusercontent.com/74369576/175788926-f741d7aa-a81e-4d2c-ad5b-658fc853167f.png)

I'm on Windows 11, using up to date VS Code and Sublime Text.

The font is amazing but I would prefer the f, l, 6, 9 that are supposedly the default :)
Thanks!

**Comment by arrowtype** [comment]
Hey @konrad-straube, thanks for the kind words!

The "code" fonts have ligatures on, plus other OpenType features "frozen in" so they can work in basically any given code environment.

If you want to apply your own  set of OpenType features, there are two main options:

1. Use the "desktop" fonts instead
2. Make a custom build of a Recursive Code font, using @arrowtype/rec-mono-config

**Comment by arrowtype** [comment]
Please let me know if that works or if you have any questions about either process! Cheers

**Comment by konrad-straube** [comment]
Thank you!! I totally missed this characteristic of the code package, even though now I see that it says this info in the first paragraph of the readme... sorry about that!

I really like the Duotone mixture so I think I'm gonna try the configurator, if I just install desktop files the regular and casual versions have different names. Just a quick question: In the code readme it states that this package is made with a reduced slant instead of -15, can you tell me which slant value you used there? :)

Thank you! Sorry for not properly reading the readme haha

**Comment by arrowtype** [comment]
All good – it's a long readme with a lot of info in it!

To find the answer to the slant question, take a look at the YAML config files in the Code Config repo. That and other specifics are all in there, and can be tweaked to your liking!

But, I realize it can be a little confusing to set up, so let me know if you get stuck!

**Comment by arrowtype** [comment]
Closing this because I think it’s resolved, but let me know if there are any more questions here!
