### ISSUE TITLE
Quote marks (especially single quotes) are too heavy in Recursive Sans Regular (Linear and Casual)

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#505]
**Problem description**

The quote marks should be lighter in Recursive Sans, more similar to the commas. Here’s how they look in version 1.084:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/45946693/176320095-90d4822f-42b3-4283-bfc3-eba892149754.png">

This is somewhat distracting in running text. Fix it!

While working on this, it would also be good to also:
- [ ] Add a bit of spacing/kerning between `/rightquote /s`
- [ ] Make the `a` shape more similar between casual and linear, for more consistent kerning with quote marks
- [x] Fix misalignment between the comma and semicolon in Sans Linear ExtraBold
- [x] The Sans Linear Light `”` also appears to be slightly off-center, e.g. in `o“o` ... fix that

**Analysis:**

- The quotes weight issue seems to be fixable within the light sources – bolder styles look fine
- The quote weight issue is worst by far in the sans linear light & light italic sources

**Final Steps**
-  [ ] When you make this update & release it, request an update to google fonts & google docs

**Comment by kenmcd** [comment]
> Fix it!

You can really be quite demanding ... while talking to yourself. :-)

**Comment by arrowtype** [comment]
> You can really be quite demanding ... while talking to yourself. :-)

Lol, I wondered if anyone might see that and think, "geesh, what a jerk!"

**Comment by arrowtype** [comment]
Useful testing string: 

`mo'o"o“o”o‘o’os“s”s‘s’sH‘H’H“H”H„H‚H'H"H.;,`

**Comment by arrowtype** [comment]
Closed with https://github.com/arrowtype/recursive/releases/tag/v1.085
