### ISSUE TITLE
How can I get this shape of `i`

### ISSUE THREAD

**Issue by Lengdrich** [arrowtype/recursive#517]
I find recursive font in someone's code image. The font is so wonderful. But in his picture his shape of `i` is different with the default and the `ss04`. How can I get the shape of `i`.

This is the picture:
![shape_of_i](https://user-images.githubusercontent.com/80807272/223056409-420df10e-6c8d-45c2-a0b3-eedb31f6a8d3.png)

**Comment by arrowtype** [comment]
Hey @Lengdrich, thanks for the kind words!

Judging by the `i l r f` shapes, my guess is they might be using the Recursive Variable font in an app that doesn't support the `rvrn` OpenType feature, which is what changes shapes from the MONO=0 styles ("sans") to MONO=1 ("mono") styles.

I haven't tested this, but you could probably use Recursive Code Config project and turn off `rvrn` along with the other feature adjustments.

**Comment by arrowtype** [comment]
To be more specific, in https://github.com/arrowtype/recursive-code-config, you could clone the repo, then adjust the Python script to do this.

You would edit this line:

https://github.com/arrowtype/recursive-code-config/blob/c20977eb1f3cd59ca7ce03a740b4745f0d299b27/scripts/instantiate-code-fonts.py#L158

From this original:

```
        # freeze in rvrn & stylistic set features with pyftfeatfreeze
        pyftfeatfreeze.main([f"--features=rvrn,{','.join(fontOptions['Features'])}", outputPath, outputPath])

```

to remove `rvrn,` ... like this:

```

        # freeze in rvrn=OFF & stylistic set features with pyftfeatfreeze
        pyftfeatfreeze.main([f"--features={','.join(fontOptions['Features'])}", outputPath, outputPath])

```

And then run the rest of your config. I haven't tried this, but I think it should work!
