### ISSUE TITLE
Cannot get font to work in any code editor

### ISSUE THREAD

**Issue by lakshits11** [arrowtype/recursive#521]
**Problem description**
Downloaded the font and installed on windows. Using `"Recursive Mn Lnr St", Menlo, "Apple Color Emoji",  monospace` in vscode or any other editor is not working.

**Screenshots**
![image](https://user-images.githubusercontent.com/54276661/234325628-5c0eed9d-1342-4148-9dda-6484dabb7621.png)

**Environment (please complete the following information):**
- OS: Windows 10
- Fonts: Recursive Mono Linear Static v1.085

**Some comments**
Please name the fonts in short manner which are easy to use in code editor

**Comment by lakshits11** [comment]
There are only 4 fonts in code folder i.e regular, italic, bold bold italic... that's why i was using these. Also on google fonts, there is no italic variant availale although the naming there is convenient

**Comment by arrowtype** [comment]
https://github.com/arrowtype/recursive-code-config

**Comment by arrowtype** [comment]
> No there's an option in vscode to set the font weight where we can use as many font weights as the font offer.

Right, VS Code mostly uses whatever is defined as the Regular weight of a family, and code themes can also use italic, bold, and bold italic.

The [recursive code config](https://github.com/arrowtype/recursive-code-config) repo allows you to define Regular as whatever exact weight you want, if the usual regular of `400` isn't what you want.

But, no worries at all. If you find this font inconvenient to work with, you definitely shouldn't feel obligated to use it. Thanks for taking time to write the issue to let me know where it was difficult! It's helpful to know for the future.
