### ISSUE TITLE
Determine characters which should NOT slant for slant axis / italics

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#55]
Not all glyphs should be slanted in an italic design. This is a place to list them and track them.

Keep upright forms in Slanted Masters:
- /degree (it's a circle, and needs to stay that way)
- /numbersign (otherwise, this moves in an annoying way in code syntax themes that slant comments)
- /currency ? (we may or may not need this slanted – it seems like a character that is simply "round" – almost an icon more than a letter)

Keep slanted forms in upright masters:
- /florin

**Comment by arrowtype** [comment]
This was done in collaboration with Lisa & Katja
