### ISSUE TITLE
file issue with browsers: "font-style: italic; currently doesn't work in any major browser"

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#56]
Jason Pamental wrote about the currently-inconsistent implementation of `font-style` in browsers:

> if you specify ‘font-style: italic’ that should tell the browser to render the font with the Italic axis set to 1 instead of 0. The trouble is, it doesn’t actually work. At least not as you might expect.

https://mailchi.mp/444e7a454775/web-typography-news-20-contextual-stylistics-and-other-fake-band-names

He offers a CodePen demo to show the problem (see in Safari vs Chrome vs Firefox):

https://codepen.io/jpamental/pen/rEKQZq?editors=1100

However, `font-style: italic` doesn't seem to work for an early version of Recursive, at all (even though `font-variation-settings` does work as expected).
https://codepen.io/thundernixon/pen/ormaav

**Safari** - `italic` _almost_ does what it should, whether or not `font-style: oblique 0deg 20deg;` is included in the `@font-face` declaration.:

![image](https://user-images.githubusercontent.com/7355414/61010283-a6e9fe80-a343-11e9-98c8-c93f76cca7cc.png)

...but it is skewed, rather than using the proper `slnt` axis. This can be seen most easily in the distortion of the letter `O`.

**Chrome & Firefox** – no result from `italic` or `oblique`:

![image](https://user-images.githubusercontent.com/7355414/61010257-8621a900-a343-11e9-9fa8-1c66d21f1a39.png)

![image](https://user-images.githubusercontent.com/7355414/61010254-81f58b80-a343-11e9-81fd-9b9f4ec61374.png)

**Comment by thundernixon** [comment]
I split the font differently and did some further tests:

https://github.com/rsms/inter/issues/175

Summary: I changed from a Slant axis to an Italic axis, so "forward slanting" can be connected to a positive number (Italic must go from 0 to 1). I then created a Cursive (CRSV) axis to allow control over true-italic alternates. This also has problems in each main browser, though the problems are slightly different.

**Comment by thundernixon** [comment]
Also, look at `http://localhost:3002/var-test.html` in Inter project for some good specifics to include in bug reports.

![image](https://user-images.githubusercontent.com/7355414/62485200-14921a80-b78a-11e9-8ba4-c2bc6b9df20f.png)

![image](https://user-images.githubusercontent.com/7355414/62485210-1a87fb80-b78a-11e9-8ba5-c11a64e48e0b.png)

**Comment by arrowtype** [comment]
I did this. Details at http://arrowtype.github.io/vf-slnt-test
