### ISSUE TITLE
Check that component glyphs slant correctly

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#60]
There is a risk of component glyphs slanting in the incorrect direction, especially if they include any transformations to components.

This is a reminder to be aware of this issue, avoid transforming components too much, and check for it in the future.

https://github.com/rsms/inter/issues/169

https://github.com/fonttools/fonttools/issues/1662

**Comment by arrowtype** [comment]
These are working quite well, in part because the build scripts decompose the arrowhead component, which is transformed to make various arrows.
