### ISSUE TITLE
Make inktrap angles more consistent in the joints of vertical stems to horizontal serifs, across weights

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#64]
So far, I've been making almost all inktraps in the upright casual styles at 0° or 90° – except for where vertical stems to horizontal serifs, and a few other isolated instances (/Z).

However, this contradicted instructions to collaborators. For the moment, I'm shelving this to come back to. I will probably make the inktraps angled in the Casual Heavy masters, because I think that looks slightly nicer.

![image](https://user-images.githubusercontent.com/7355414/61255890-8d2c2b00-a738-11e9-9ae8-4a6baaa29810.png)

![image](https://user-images.githubusercontent.com/7355414/61255993-01ff6500-a739-11e9-89c8-02dd16b618fd.png)

![image](https://user-images.githubusercontent.com/7355414/61256040-2f4c1300-a739-11e9-98f0-a63cd415019e.png)

**Comment by arrowtype** [comment]
This was fixed in #155
