### ISSUE TITLE
Make mono-to-sans glyph copier more efficient

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#65]
Easy wins:
- [ ] double-check that the `newItalicGlyphs` list is comprehensive
- [ ] select just a `mono`, and automatically find the matching `sans` UFO
- [ ] have an (optional) controller script that will just run through all UFOs and copy glyphs
- [ ] _don't_ copy experimental glyphs (anything marked `(0.5, 0, 1, 0.75)`)

**Comment by arrowtype** [comment]
This wasn't really necessary to work on, in the end.
