### ISSUE TITLE
Make special RIBBI package combining Linear (regular + ital) and Casual (Bold + Bold Ital)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#77]
This has happened accidentally a few times, and I love it:

![image](https://user-images.githubusercontent.com/7355414/61833438-4d54fa00-ae42-11e9-8d22-002610eb3946.png)

It looks great in Markdown and Zshell themes.

This should be relatively straightforward to deliberately make into a code-specific font package.

**Comment by arrowtype** [comment]
Done in the latest release (v1.042)
