### ISSUE TITLE
/Tcommaaccent and /tcommaaccent are switched

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#79]
![image](https://user-images.githubusercontent.com/7355414/61887982-aec3aa00-aed0-11e9-997f-748c50ea7313.png)

/Tcommaaccent and /tcommaaccent are switched. Unicode `021B` holds an uppercase T form, while `021A` holds the lowercase. This needs to be fixed in glyph construction files.

**Comment by arrowtype** [comment]
![image](https://user-images.githubusercontent.com/45946693/72772002-b1c5fb80-3bd0-11ea-80f8-b27238b1c3ca.png)

This is working as of b8b1cee
