### ISSUE TITLE
Make first round of code ligatures

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#84]
We need a starter set of code ligatures to support the most noticeable and common syntax pieces in JavaScript, Python, and Markdown.

Here is a visual of these shown (the blue glyphs are currently placeholders set in Fira Code):

![image](https://user-images.githubusercontent.com/7355414/62156569-47936480-b2d9-11e9-88d3-828e553ff95f.png)

Notes:
- We will design these in mono masters, and they will be duplicated into the sans masters, where we will not touch them (similar to many other 600-unit glyphs)
- These will have widths going in units of 600, based on the number of glyphs in the ligature. If it's a ligature of 2 glyphs, that will mean 1200 units, etc.
- Along with some helpful input from Rafał, I have designed a foundational `ampersand_ampersand.code` in the mono weight B. This should be moved into other masters.

Steps:
- [ ] check/test whether common text editors (VS Code, Sublime, Atom) use contextual ligatures by default. If they do, consider making some ligatures default, and others opt-in (see `docs/coding-ligatures` for more details)

More details and up-to-date list of `priority 0` glyphs are here:

https://github.com/thundernixon/recursive/tree/master/docs/coding-ligatures

**Comment by arrowtype** [comment]
[Cascadia Code](https://github.com/microsoft/cascadia-code), by Aron Bell, just added code ligatures. It takes some interesting design choices.

- The `<=` and `>=` are more horizontally stretched, whereas they can height in Fira Coda (in both cases, they are correctly double-width)
- The `###` just uses components of the `#`, and places an extra rectangle to connect these. This isn't that surprising, but reminds me that we can probably use Glyph Construction to get a headstart on many of these. Previously, I was kind of thinking we would want to decompose these and get clever. Now, however, actually trying that out, I see that the "railroad" style connections are more clearly a ligature, and will add less filesize to keep as mostly-components.


![image](https://user-images.githubusercontent.com/45946693/65259279-6d1b3e00-dad2-11e9-80e5-b910419d1a21.png)
![image](https://user-images.githubusercontent.com/45946693/65259603-eadf4980-dad2-11e9-9132-2d66cc61ffff.png)

**Comment by arrowtype** [comment]
I'm hoping to generate most of the code ligatures, and then add any necessary manual fixes after that.

[Glyph Construction](https://github.com/typemytype/GlyphConstruction) will probably be helpful for this, but will probably need a bit of extra scripting to make work as needed.

As one example, I can generate something close to `==` with Glyph Construction by itself, but I don't think there is a way to maintain the sidebearings of each component. To do so, I think I will need to check the initial sidebearings with Python, then use that number in the Glyph Construction recipe. For most glyphs, the sidebearing will change from master to master, so this will need to check things and adjust the recipe slightly for each master.

![image](https://user-images.githubusercontent.com/45946693/65820428-bc5e1e80-e1f6-11e9-9deb-8e9585870481.png)

**Comment by arrowtype** [comment]
UPDATE: turns out, Glyph Construction just calls this [stacking horizontally](https://github.com/typemytype/GlyphConstruction#stacking-horizontally). It works like this:

```
ffi = f & f & i
```

and

```
equal_equal.code = equal & equal
```

We will still want to adjust many of the resulting ligatures, but creating a set of recipes for "template glyphs," then running those in all mono masters, will be a good place to start.

**Comment by LisaHuang2017** [comment]
New glyphs added from this [commit](https://github.com/arrowtype/recursive/pull/182/commits/301037bc34f6b60d1d07dee804cbfca8ba0cbeab)
with proof PDF at this location : recursive/src/proofs/working-proofs/102019-code-ligatures

**Comment by arrowtype** [comment]
The /percent_percent.code wasn't quite compatible yet, and there were some different point orders in `equal_greater.code`. However, these were both really quick to fix in Prepolator. :)

I still need to test a few different ways to implement these, and we may find some ways to further refine these, but with https://github.com/arrowtype/recursive/commit/f7d26981216edbac0784a65e3b2d7c25a8045da9, I think we can feel good about closing this issue.

![image](https://user-images.githubusercontent.com/45946693/66442133-85161b80-ea07-11e9-9cf3-4bc44842423b.png)
