### ISSUE TITLE
Draw Vietnamese accents, build Vietnamese composite glyphs

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#87]
We need to draw first versions of the horn and the hook, and compose for /o, /u, /O, and /U (probably in Mono casual & linear weight B).

From that, we will draw these accents in other masters.

As these are drawn, their anchors should be added to the base glyphs, as well as to the Glyph Construction recipes so they can be built along with other diacritics: https://github.com/thundernixon/recursive/tree/master/src/glyph-recipes

---

Super basic early sketches of what I have in mind for this:

![IMG_0882](https://user-images.githubusercontent.com/7355414/62263116-0f7b4700-b3e9-11e9-81bf-fb75fb5d32a6.jpg)

---

**Resources:**

- This is an excellent guide: https://vietnamesetypography.com/
- Glyph Construction is one very useful tool for building diacritics. This is explained here:
- https://robofont.com/documentation/how-tos/building-accented-glyphs/
- https://vi.wikipedia.org/wiki/Trang_Ch%C3%ADnh

**Comment by thundernixon** [comment]
To make these work in this monospace design, we need to move the horn in quite a bit more, to avoid crashes.

For the hook, I think they are looking fine in the Casual, but the contrast feels wrong in the Linear style. I don't know for sure, but I think that the diagonal should be a bit thinner than the horizontal bar.

![image](https://user-images.githubusercontent.com/7355414/63448921-050f0480-c40d-11e9-8a87-f748d1b09416.png)

![image](https://user-images.githubusercontent.com/7355414/63448929-0a6c4f00-c40d-11e9-9c4c-12e256963bed.png)

**Comment by LisaHuang2017** [comment]
Need last check on the updates before closing this issue

**Comment by arrowtype** [comment]
I reached out to Donny Trương about this, and I'll be getting a critique from him on it next week. :) So, we should plan on making any suggested fixes after that.

**Comment by arrowtype** [comment]
Surprising things I'm learning about Vietnamese accents:
- whereas many accents have both "combining" versions and solo versions (e.g. `acutecomb` and `acute`, `hookcomb` and `horncomb` don't seem to have solo versions. There is currently a `hook` with unicode `2440`, but this Unicode links to [OCR HOOK (U+2440)](https://www.fileformat.info/info/unicode/char/2440/index.htm), which is something to do with OCR – not with Vietnamese
- there is not a clear list of Vietnamese diacritics to add to the UFOs, so I'm printing names and unicodes from the GlyphsApp default Vietnamese glyphs, and then adding these into UFOs with my [unicode-adding script](https://github.com/arrowtype/recursive/blob/26069fd3d159ad1a58208b0904b7fbeb88eaf380/src/00-recursive-scripts-for-robofont/clean-up/add-unicodes-from-adobe_glyph_list.py).

GlyphsApp script:
```
f = Glyphs.font # frontmost font

for g in f.selection:
	name = '"' + g.name + '":'
	print '    ' + name.ljust(25) + '"' + g.unicodes[0] + '",'
```

**Comment by arrowtype** [comment]
Open to-do items:

- [ ] get critique from Donny and make updates
- [ ] copy/adapt these diacritics over to Sans masters
- [ ] create combined comb glyphs in the glyphConstruction recipes: `brevecomb_acutecomb brevecomb_gravecomb brevecomb_hookabovecomb brevecomb_tildecomb circumflexcomb_acutecomb circumflexcomb_gravecomb circumflexcomb_hookabovecomb circumflexcomb_tildecomb `

**Comment by arrowtype** [comment]
[Here is the current latest version of Recursive with Vietnamese diacritics (mono only)](https://github.com/arrowtype/recursive/blob/496bc73c251fd0a8933118c68e693db5cb701fd5/src/proofs/vietnamese-diacritics/recursive-mono--xprn_wght_slnt_ital--2019_09_23.ttf)

[Here is the current latest proof of these, as a PDF with outlined text](https://github.com/arrowtype/recursive/blob/496bc73c251fd0a8933118c68e693db5cb701fd5/src/proofs/vietnamese-diacritics/exports/recursive-vietnamese-diacritics-2019_09_24-17_12.pdf)

**Comment by arrowtype** [comment]
Adding /ydot. This most often has the dot to the bottom-right of the /y, to avoid line messing with line heights too much:

![image](https://user-images.githubusercontent.com/45946693/65629396-3f863700-dfa1-11e9-938b-5138bf55d8a0.png)

**Comment by arrowtype** [comment]
Donny Trương sent some feedback, plus answered a few questions I had.

![image](https://user-images.githubusercontent.com/45946693/65721439-11bff180-e078-11e9-9f94-a15279a75426.png)

## Questions

#### Should the horn be at the same level in /o and /u glyphs, or is it fine/good if the /u horn goes a bit higher?

> Ideally, they should be on the same level for consistency, but I understand it is almost impossible in some design. It is fine for the u horn to be a tiny bit higher, but not too noticeable. 

#### Do you think of the combined accents as a “single” mark, or two marks? My real question is: is it fine for the accents to be closer to one another than to the main glyph?

> The combined accents should always be two marks. They can be closed to one other but should not be touched or appeared to be as one.

#### Do people tend to draw the /uhorn and /ohorn as single glyphs, then use those as components in more-complex glyphs like /ohornacute? Or, are the /uhorn and /ohorn typically component glyphs?

> Sorry,  I don’t know the answer to this question. The tricky part is that the horn should not crash with the accents, particularly the tilde.

**Comment by arrowtype** [comment]
![image](https://user-images.githubusercontent.com/45946693/65904355-4c819c80-e38c-11e9-8b5b-d5533bf234ba.png)

Me:

> One thing I'm slightly confused by: in your PDF, the expressive (casual) letters still have the non-expressive (linear) hook accents. I could see this being the result of a software glitch with variable fonts ... out of curiosity, what app (and version) did you make that PDF with?

> Finally, you said in the Light weight, you asked whether we could "attach the horn seamlessly." Do you mean something like this, where the right stem of the /u doesn't have any visible flat part?

From Donny:

> I am using Adobe Illustrator CC. It is the latest version, which I updated a few days ago. I did see the half circle in my AI doc, but I didn’t realize the PDF was wrong. Either case, I still recommend the ? for the hook about. 

> Yes, the seamless u horn you just did is what I meant.

**Comment by arrowtype** [comment]
To do:

I've added the `tildeviet` anchor to the /o, /u, and /tildevietcomb.case glyphs of Mono masters, to make the glyph builder recipes work without variables (which are challenging to use for controlling positioning between different masters). These must get copied over into the sans.
