### ISSUE TITLE
Symbol set: remove exterior overlap, add inktraps, make slanted versions

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#89]
These instructions have been shared through another channel, but I'm documenting this here along with other critical beta 1 needs. :)

**Comment by KatjaSchimmel** [comment]
Lisa and I are both working on this task. We split the task list in half (https://paper.dropbox.com/doc/Recursive-symbols--Ah1kea0zUWs0LpNbBOaxZ8f0Ag-veLNBPdIxhfTutv8yfavI)

**Comment by KatjaSchimmel** [comment]
There will be on round of corrections. A proof with all the symbols (Lisa + Katja) is [here](https://github.com/thundernixon/recursive/tree/katja/src/proofs/working-proofs/080319-mono-symbols)

**Comment by KatjaSchimmel** [comment]
corrections are done and compatibility is checked. only some research about the vertical position of the /overline glyph has to be done. for this I created a new issue: https://github.com/arrowtype/recursive/issues/120
