### ISSUE TITLE
Double-check opentype features, add any that are still needed

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#92]
Will add more here in the future, when I'm at this stage.

- [x] `one.prop` for proportional figures
- [x] `Q.titl` for titling
- [x] `.case` punctuation (can /at simply be translated up on Y axis? What about in slanted masters? Maybe this should be a component)

**Comment by arrowtype** [comment]
I'm working on this here:

https://github.com/arrowtype/recursive/tree/f434f37f896648bd49772fa08be5609493df6f95/docs/001-opentype_features
