### ISSUE TITLE
Useful glyphs to add

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#93]
- [x] `Q.titl` (no descender)
- [x] `b.italic`, (no "spur" at bottom left)

**Comment by LisaHuang2017** [comment]
@thundernixon  In both Mono and Sans ?

**Comment by thundernixon** [comment]
Yes, needed in both because the /O and /Q are wider in Sans.

It's quite a bit like the /g

![image](https://user-images.githubusercontent.com/7355414/63099163-86185880-bf42-11e9-9248-37033b2a9b95.png)

**Comment by thundernixon** [comment]
These sketches obviously don't match the type design 1-to-1, but they do show what I mean be an "italic b," I hope.

![image](https://user-images.githubusercontent.com/7355414/63099248-b6f88d80-bf42-11e9-94e6-8c6d37614170.png)

![image](https://user-images.githubusercontent.com/7355414/63099267-c24bb900-bf42-11e9-82f7-7f59ea5f94cb.png)

**Comment by thundernixon** [comment]
Reopening this so it's a reminder for me to proof and adjust as needed.

I think that generally, this is a very good start on the /b.italic, but it needs to be somewhat more round, in both Linear and Casual styles. Overall, it should be much closer to the /v.italic. In the Linear, the bottom right corner is too square, and needs a larger curve radius. In the Casual, it needs a bit more contrast.

This is a sampling of masters and not comprehensive, but shows the overall change I'm hoping to make.

![image](https://user-images.githubusercontent.com/7355414/63448462-f5db8700-c40b-11e9-9845-0177461bf03d.png)

![image](https://user-images.githubusercontent.com/7355414/63448470-f8d67780-c40b-11e9-9f49-858b9a965c10.png)

![image](https://user-images.githubusercontent.com/7355414/63448483-fecc5880-c40b-11e9-9388-f884085f1727.png)

![image](https://user-images.githubusercontent.com/7355414/63448490-012eb280-c40c-11e9-927e-9264b88b604d.png)

**Comment by LisaHuang2017** [comment]
@thundernixon this issue can be closed if you validate the latest changes on those letters :)
