### ISSUE TITLE
QA script: check that code ligature widths are consistent across all masters

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#94]
This is started in [src/00-recursive-scripts-for-robofont/check-for-nonconforming-widths.py](https://github.com/thundernixon/recursive/blob/master/src/00-recursive-scripts-for-robofont/check-for-nonconforming-widths.py)

**In Mono:**
- [x] all widths should be in units of 600 (code ligatures may be 1200 or 1800, etc)
- [ ] each glyph must be consistent across masters 
- [ ] code ligatures should have widths that correspond to their names – `(len(underscores) + 1) * 600`. For example, `numbersign_numbersign_numbersign.code` must be 1800 in all masters.

**In Sans:**
- [x] all widths should be in units of 50
- [ ] ach glyph must be consistent across masters
- [ ] all kerning in units of 25, consistent between all masters (part of https://github.com/thundernixon/recursive/issues/91)

**Comment by thundernixon** [comment]
This is partway done with https://github.com/thundernixon/recursive/blob/4ae8daa60d9642345b3bcf755c8a720a52f18b77/src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-for-nonconforming-widths.py

**Comment by arrowtype** [comment]
Actually, the noncomforming width checks plus the fact that these glyphs are compatible for interpolation is a strong indication. There is a small chance that something has a mismatched width, but I think I would have found it in design & code work by now, as it would have to be off by 600 units to fail the nonconforming width check. If there is something that needs fixing, it will be fixable very quickly.
