### ISSUE TITLE
Make alternate diacritics (.italic, .mono, .sans)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#95]
- [x] reduce files to one version (maybe two, if it must be split for mono vs sans)
- [x] add combined glyphs for all `.italic`, `.mono`, and `.sans` glyphs

**Comment by thundernixon** [comment]
Generally, lowercase letters with variants need diacritics.

```
a.italic c.italic d.italic e.italic f.italic g.italic h.italic i.italic j.italic k.italic m.italic n.italic r.italic s.italic u.italic v.italic w.italic x.italic y.italic z.italic

i l r i.mono l.mono r.mono l.sans
```

Note: this excludes the flat-topped /g, because its `.mono` form has an ear that would clash.

**Comment by arrowtype** [comment]
Started with https://github.com/arrowtype/recursive/commit/5cc3776dcd4b27600649724930ee6430d698dea6

**Comment by arrowtype** [comment]
This has since been (almost entirely) completed. There is a [lingering issue](https://github.com/arrowtype/recursive/issues/274) in diacritics of `l`.
