### ISSUE TITLE
Make mono-sans compatible ligatures, where necessary. Find if OT features can be controlled by axes.

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#96]
- [ ] Glyphs that should probably be 600 in mono (check before making): `ǆ ǉ ǌ ǳ ǅ ǈ ǋ ǲ`
- [ ] Glyphs that should not look like ligatures in mono, but should in sans: `f_i f_l f_f_l`

- [ ] important ligatures for design reliability:
  - [ ] fl (and /fl.mono)

![image](https://user-images.githubusercontent.com/7355414/62343925-f8585a00-b4b9-11e9-9442-29e04d8b11d2.png)

**Comment by thundernixon** [comment]
- [ ] `ǆ ǉ ǌ ǳ ǅ ǈ ǋ ǲ`
- [ ] `f_i f_l f_f_l`

**Comment by thundernixon** [comment]
So far...

## fl.mono
- [ ] /fl.mono is in:
- Recursive Mono Casual B
- Recursive Sans Casual B

...but not in:
  - [ ] Recursive Mono Casual A
  - [ ] Recursive Mono Casual A Slanted
  - [ ] Recursive Mono Casual B Slanted
  - [ ] Recursive Mono Casual C
  - [ ] Recursive Mono Casual C Slanted
  - [ ] Recursive Mono Linear A
  - [ ] Recursive Mono Linear A Slanted
  - [ ] Recursive Mono Linear B
  - [ ] Recursive Mono Linear B Slanted
  - [ ] Recursive Mono Linear C
  - [ ] Recursive Mono Linear C Slanted
  - [ ] Recursive Sans Casual A
  - [ ] Recursive Sans Casual A Slanted
  - [ ] Recursive Sans Casual B Slanted
  - [ ] Recursive Sans Casual C
  - [ ] Recursive Sans Casual C Slanted
  - [ ] Recursive Sans Linear A
  - [ ] Recursive Sans Linear A Slanted
  - [ ] Recursive Sans Linear B
  - [ ] Recursive Sans Linear B Slanted
  - [ ] Recursive Sans Linear C
  - [ ] Recursive Sans Linear C Slanted

**Comment by arrowtype** [comment]
This issue is fixed / out of date
