### ISSUE TITLE
Measure impact of shared glyph outlines on filesize. Find if filesize can be further reduced.

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#99]
​​Characters that don’t need to change width to work well in both Mono & Sans styles are shared between them.

I suspect this allows better compression in the resulting woff2 files, but I don't know. I am fairly certain it would reduce filesize in OTF files because in OTF (AKA "CFF," or "compact font format") repeated contours can be stored once and referenced, almost like mini-components. However, I don't think that happens in TTFs.

However, from what I can tell, that is one of the compression techniques in woff2:

> WOFF 2.0 adds a preprocessing step, before entropy coding.The reason for this is that many fonts contain redundant or duplicate information, or information that can be deduced from other items of data also present. Data may also be padded to a convenient multiple of 8 bits, because aligned data is faster to access. They are thus optimized for convenience and speed of access at the expense of size. Preprocessing detects and eliminates redundant data, more efficiently encodes derived data, and stores data in the minimal number of bits. Following decompression, a reconstruction step is needed to re-align data and to compute derived values.

– from https://www.w3.org/TR/WOFF20ER/

Digging further, I can't find anything more clear than that. It should be relatively simple to test: I could make one mono–sans VF into a woff2. I could then edit those masters with a script that randomizes points, make that into a new woff2 VF, and compare their sizes.

**Comment by arrowtype** [comment]
This was more for specimen content than a requirement for the project. I may come back to it for a future blog post or for the website, but I am closing this as irrelevant to the font itself.
